Random bark revamp
Simple-Station/Einstein-Engines pull request #1003
Opened 2024-10-03 12:36 UTC by Mnemotechnician

# Description
This improves the random barks by:
- Fully moving the random barks to localization files, with the ability to re-use existing types
- Adding many new (english) random bark types
- Making the random bark system add a random punctuation mark at the end of a random bark
- Adjusting some existing random bark configs

This also reparents MobSecurityDog to MobCorgi and MobArcticFox to MobFox because for some reason delta-v decided to copy the original mobs instead of using inheritance??? Either way, laika and siobhan will now also have random barks, can be carried, etc.

<details><summary><h1>Media</h1></summary>
<p>

![image](https://github.com/user-attachments/assets/2f429d8d-fa3a-4ac1-8f04-0eefa2541de3)
![image](https://github.com/user-attachments/assets/84a2bf32-07a5-4b7b-9afc-d077333ee620)
![image](https://github.com/user-attachments/assets/b4b099c3-4c59-444b-b2f8-f13d11d93f30)
![image](https://github.com/user-attachments/assets/f9d8de0d-06ff-4f9a-8358-e5dd38e9571d)

</p>
</details>

# Changelog
:cl:
- add: Animals now have more unique things to say when not controlled by a player.

2024-10-03 20:07 UTC, FoxxoTrystan requested changes

2024-10-03 20:07 UTC, FoxxoTrystan commented on Content.Server/Speech/Systems/RandomBarkSystem.cs
> +            if (_entity.TryGetComponent<MindContainerComponent>(uid, out var actComp) && actComp.HasMind
```suggestion
            if (TryComp<MindContainerComponent>(uid, out var actComp) && actComp.HasMind
```

2024-10-03 20:54 UTC, Mnemotechnician commented
Ugh, I forgot some bark types. I'll uh, add them later.

2024-10-03 21:31 UTC, FoxxoTrystan submitted a review, later dismissed
Yep, Test fails valid.

2024-10-09 00:56 UTC, VMSolidus approved these changes

2024-10-09 15:45 UTC, OldDanceJacket approved these changes

2024-10-09 15:48 UTC, merged