Keybind Search Bar
Simple-Station/Einstein-Engines pull request #1005
Opened 2024-10-04 00:33 UTC by xTheLifex

# Description

This PR adds a Search bar to the Keybinds menu as a QOL feature.

---

# TODO

- [x] Search bar
- [ ] Search by the key bind values as well (maybe?)
- [ ] Hide categories that have no results for them

---

<details><summary><h1>Media</h1></summary>
<p>

https://github.com/user-attachments/assets/b23555f1-b945-4848-87a2-1af70c8a9a5c

</p>
</details>

---

# Changelog

:cl:
- add: Added a search bar to the keybinds menu

2024-10-19 08:23 UTC, DEATHB4DEFEAT requested changes

2024-10-19 08:23 UTC, DEATHB4DEFEAT commented on Content.Client/Options/UI/Tabs/KeyRebindTab.xaml
> +            <Label Text="{Loc 'ui-options-binds-search'}"
```suggestion
            <Label Text="{Loc 'ui-options-binds-search'}"
                   Margin="5 0 5 0"
```

2024-10-19 08:23 UTC, DEATHB4DEFEAT commented on Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
> +                return optionText.StartsWith(_searchText, StringComparison.OrdinalIgnoreCase) || _searchText.Contains(optionText, StringComparison.OrdinalIgnoreCase);
```suggestion
                return optionText.StartsWith(_searchText, StringComparison.OrdinalIgnoreCase)
                    || _searchText.Contains(optionText, StringComparison.OrdinalIgnoreCase);
```

2024-10-19 08:23 UTC, DEATHB4DEFEAT commented on Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
> +                return optionText.StartsWith(_searchText, StringComparison.OrdinalIgnoreCase) || _searchText.Contains(optionText, StringComparison.OrdinalIgnoreCase);
```suggestion
                return optionText.StartsWith(_searchText, StringComparison.OrdinalIgnoreCase)
                    || _searchText.Contains(optionText, StringComparison.OrdinalIgnoreCase);
```

2024-10-19 08:23 UTC, DEATHB4DEFEAT commented on Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
> +                var optionText = Loc.GetString(checkBoxName);
```suggestion

                var optionText = Loc.GetString(checkBoxName);
```

2024-10-19 08:23 UTC, DEATHB4DEFEAT commented on Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
> +                    return;
```suggestion
                    return;

```

2024-10-19 08:23 UTC, DEATHB4DEFEAT commented on Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
> +                    return;
```suggestion
                    return;

```

2024-10-19 08:23 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/escape-menu/ui/options-menu.ftl
> +ui-options-binds-search = Search:
```suggestion
ui-options-binds-search = Search
```

2024-10-19 08:23 UTC, DEATHB4DEFEAT commented on Content.Client/Options/UI/Tabs/KeyRebindTab.xaml
> +            <Label Text="{Loc 'ui-options-binds-search'}"
Also make this use the header style class

2024-12-07 01:24 UTC, DEATHB4DEFEAT approved these changes

2024-12-07 01:25 UTC, sleepyyapril approved these changes

2025-01-26 03:56 UTC, stellar-novas approved these changes
Looks fine, will test in game and merge

2025-04-10 15:02 UTC, merged