Port all delta-v mail improvements
Simple-Station/Einstein-Engines pull request #1011
Opened 2024-10-05 16:45 UTC by Mnemotechnician

# Description
Showing some love to our hard-working couriers.

This cherry-picks the following PRs from delta-v:
- https://github.com/DeltaV-Station/Delta-v/pull/1472 - Adds a MailMetrics PDA cartridge for couriers and the LO
- https://github.com/DeltaV-Station/Delta-v/pull/1652 - Ports mail tweaks from frontier to delta-v, adding large packages, RPDs (mail cannons), and more mail
- https://github.com/DeltaV-Station/Delta-v/pull/1788 - Adding a couple more packages
- https://github.com/DeltaV-Station/Delta-v/pull/1925 - Fixing the non-functional "last known location" part of mail descriptions

Some mail items, such as the opporozidone syringe and rainbow joints/blunts, had to be disabled because we don't have them (yet?) 

<details><summary><h1>Media</h1></summary>
<p>

![image](https://github.com/user-attachments/assets/2299ffc3-17ce-4743-886c-7705e8789e96)

![image](https://github.com/user-attachments/assets/a2ee1a07-d765-41e7-8f70-f94a50412398)

![image](https://github.com/user-attachments/assets/03b16b8e-0eff-4332-99ad-d4a201ee8f2b)

![image](https://github.com/user-attachments/assets/44d2e5c2-db79-4d8d-8877-693648edd35d)

![image](https://github.com/user-attachments/assets/f3d7bdbb-fc14-4f2f-bf30-aa54fdf49099)

![image](https://github.com/user-attachments/assets/b1e4c53f-c9d8-496b-a72e-f4f4b702e368)

</p>
</details>

---

# Changelog
:cl:
- add: The Courier and Logistics Officer now have a new program in their PDA for tracking mail delivery performance, including earnings and percent of packages opened, damaged, or expired.
- add: The list of possible mail packages has been greately expanded, and now includes large parcels.
- add: The CourierDrobe now offers a rapid mail delivery device, along with capsules for it.

2024-10-08 01:53 UTC, VMSolidus requested changes
There's simply too many to count here, but everything in this PR needs to be moved out of specific fork namespaces, and down into the core namespace.

2024-10-09 14:43 UTC, Mnemotechnician commented
> There's simply too many to count here, but everything in this PR needs to be moved out of specific fork namespaces, and down into the core namespace.

ugh, remind me like on Saturday maybe...

2024-10-13 18:46 UTC, VMSolidus requested changes

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/Components/MailTeleporterComponent.cs
> +        // End Frontier: Large mail
```suggestion
        /// <summary>
        /// What's the bonus for delivering a large package intact?
        /// </summary>
        [DataField]
        public int LargeBonus = 1500; //DeltaV; 5000 to 1500

        /// <summary>
        /// What's the malus for failing to deliver a large package?
        /// </summary>
        [DataField]
        public int LargeMalus = -500; //DeltaV; -250 to -500
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/Components/MailTeleporterComponent.cs
> +        public string MailPool = "RandomDeltaVMailDeliveryPool"; // Frontier / DeltaV: Mail rework
```suggestion
        public string MailPool = "RandomDeltaVMailDeliveryPool";
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/Components/MailComponent.cs
> +        // End Frontier: large mail
```suggestion
        /// <summary>
        ///     Whether this parcel is large.
        /// </summary>
        [DataField]
        public bool IsLarge;
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailCommands.cs
> +        // End Frontier
```suggestion
        var isLarge = false;
        if (args.Length > 4 && !Boolean.TryParse(args[4], out isLarge))
        {
            shell.WriteError(Loc.GetString("shell-invalid-bool"));
            return;
        }
        var mailPrototype = isLarge ? _blankLargeMailPrototype : _blankMailPrototype;
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailCommands.cs
> +        if (!_prototypeManager.HasIndex<EntityPrototype>(mailPrototype)) // Frontier: _blankMailPrototype<mailPrototype
```suggestion
        if (!_prototypeManager.HasIndex<EntityPrototype>(mailPrototype))
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailCommands.cs
> +        shell.WriteLine(Loc.GetString("command-mailto-no-blankmail", ("blankMail", mailPrototype))); // Frontier: _blankMailPrototype<mailPrototype
```suggestion
        shell.WriteLine(Loc.GetString("command-mailto-no-blankmail", ("blankMail", mailPrototype)));
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailCommands.cs
> +        var mailUid = _entityManager.SpawnEntity(mailPrototype, _entityManager.GetComponent<TransformComponent>(containerUid).Coordinates); // Frontier: _blankMailPrototype<mailPrototype
```suggestion
        var mailUid = _entityManager.SpawnEntity(mailPrototype, _entityManager.GetComponent<TransformComponent>(containerUid).Coordinates);
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailCommands.cs
> +            shell.WriteLine(Loc.GetString("command-mailto-bogus-mail", ("blankMail", mailPrototype), ("requiredMailComponent", nameof(MailComponent)))); // Frontier: _blankMailPrototype<mailPrototype
```suggestion
            shell.WriteLine(Loc.GetString("command-mailto-bogus-mail", ("blankMail", mailPrototype), ("requiredMailComponent", nameof(MailComponent))));
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailCommands.cs
> +        mailComponent.IsLarge = isLarge; //Frontier Mail
```suggestion
        mailComponent.IsLarge = isLarge;
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailSystem.cs
> +        // DeltaV - system that keeps track of mail and cargo stats
```suggestion
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailSystem.cs
> +            // DeltaV - Add earnings to logistic stats
```suggestion
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailSystem.cs
> +            MailEntityStrings mailEntityStrings = component.IsLarge ? MailConstants.MailLarge : MailConstants.Mail; //Frontier: mail types stored per type (large mail)
```suggestion
            MailEntityStrings mailEntityStrings = component.IsLarge ? MailConstants.MailLarge : MailConstants.Mail;
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailSystem.cs
> +                args.PushMarkup(Loc.GetString(mailEntityStrings.DescFar)); // Frontier: mail constants struct
```suggestion
                args.PushMarkup(Loc.GetString(mailEntityStrings.DescFar));
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailSystem.cs
> +            args.PushMarkup(Loc.GetString(mailEntityStrings.DescClose, ("name", component.Recipient), ("job", component.RecipientJob))); // Frontier: mail constants struct
```suggestion
            args.PushMarkup(Loc.GetString(mailEntityStrings.DescClose, ("name", component.Recipient), ("job", component.RecipientJob)));
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailSystem.cs
> +                // DeltaV - Tampered mail recorded to logistic stats
```suggestion
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailSystem.cs
> +                // DeltaV - Broken mail recorded to logistic stats
```suggestion
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailSystem.cs
> +            // End Frontier
```suggestion
            MailEntityStrings mailEntityStrings = mailComp.IsLarge ? MailConstants.MailLarge : MailConstants.Mail;
            if (mailComp.IsLarge)
            {
                mailComp.Bounty += component.LargeBonus;
                mailComp.Penalty += component.LargeMalus;
            }
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailSystem.cs
> +                        // DeltaV - Expired mail recorded to logistic stats
```suggestion
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailSystem.cs
> +            _metaDataSystem.SetEntityName(uid, Loc.GetString(mailEntityStrings.NameAddressed, // Frontier: move constant to MailEntityString
```suggestion
            _metaDataSystem.SetEntityName(uid, Loc.GetString(mailEntityStrings.NameAddressed,
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailSystem.cs
> +                _tagSystem.AddTag(mail, "Mail"); // Frontier
```suggestion
                _tagSystem.AddTag(mail, "Mail");
```

2024-10-13 18:46 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Mail/MailSystem.cs
> +        // DeltaV - Helper function that executes for each StationLogisticsStatsComponent
```suggestion
        // Helper function that executes for each StationLogisticsStatsComponent
```

2024-10-13 19:07 UTC, VMSolidus commented
Probably going to merge this after the last batch of requested changes are made.

2024-10-13 19:19 UTC, Mnemotechnician commented
Inshalla; nynanotrasen, delta-v and frontier mail code is now merged

2024-10-13 19:22 UTC, VMSolidus commented
> Inshalla; nynanotrasen, delta-v and frontier mail code is now merged

Fuck yea

2024-10-13 19:22 UTC, VMSolidus approved these changes

2024-10-13 19:25 UTC, OldDanceJacket approved these changes

2024-10-13 19:28 UTC, Peptide90 approved these changes

2024-10-13 19:38 UTC, merged