Port Gax From Estação Pirata
Simple-Station/Einstein-Engines pull request #1019
Opened 2024-10-07 19:23 UTC by Ichaie

# Description

This PR ports the "Gax" map directly from Estação Pirata, making some changes and corrections.
This PR ports https://github.com/rbertoche/space-station-14/pull/80
Gax is a recreated ss13 map, originally from YogStation (SS13)

---

# TODO

---

<details><summary><h1>Media</h1></summary>
<p>

![Gax-0](https://github.com/user-attachments/assets/88e4daa5-0de1-4a68-b6ae-d957056a1b29)

</p>
</details>

---

# Changelog

:cl:
- add: A new map called NCS Gax has been added to rotation.

2024-10-07 19:42 UTC, FoxxoTrystan requested changes

2024-10-07 19:42 UTC, FoxxoTrystan commented on Resources/Prototypes/Maps/gaxstation.yml
> +          emergencyShuttlePath: /Maps/Shuttles/EstacaoPirata/emergency_neol.yml
Im not sure if we have that shuttle file, was it forgotten?

2024-10-07 19:42 UTC, FoxxoTrystan commented on Resources/Prototypes/Maps/gaxstation.yml
> +          path: /Maps/Shuttles/EstacaoPirata/cargo_gax.yml
Again i dont think we have this shuttle file.

2024-10-08 00:04 UTC, VMSolidus commented
So I don't normally do map reviews, but luckily they aren't that crazy to do since it's pretty self evident if a map is good or not(to me at least), and I have a checklist of things our maps will need. So I'll start off with the Good, the Amazing, the Okay, and the Missing Content.

**Good!**
The layout of this map is awesome, and I appreciate that pretty much every department has their own special interactions for a lot of things. The fully enclosed arrivals dock with meteor shielding is PEAK. I've never seen a map with that before. All of the departments except for Epistemics are incredibly spacious. 

**Awesome:**
I will admit, that in exchange for Epistemics feeling more cramped than the other departments, you have completely knocked it out of the fucking park by futureproofing the map for content that isn't even in the game yet, by including things such as an AI Satellite, a Xenobiology lab, an AI Upload Room(Separate from the Satellite), a fully stocked Robotics Bay with Surgical Room, Server room completely separate from the Mystagogue's office is great. 

You have probably the best medbay I've ever seen in a map. Congratulations on absolutely killing it here. Having Virology, Genetics, Security Checkpoint, Chemistry, Cloning Lab, Cryo bay, Surgery Room, and hell there's even a break room, and a Paramedic checkpoint! There is very little this medbay is missing!

**Okay:** 
Security can stand to be improved most, but luckily its improvements aren't that crazy. I absolutely love that Security has a shuttle dock, presumably in preparation for things like Lavaland Deportation. That's awesome!

The Permabrig could probably be livened up a little, it's unusually barebones I will admit.
![image](https://github.com/user-attachments/assets/9f5d69ba-eccb-4e65-a2a5-743a287a970c)

**Armory is unusually vulnerable:** Lastly, the Armory has a potential access route that would allow for breaching the armory to space via only a single C4. There should be an extra layer of walls on the outside of the armory, which will prevent the armory from being entered with only a single C4. It's important for game balance that Security have time to react when they first hear the beeping that indicates Nukies are trying to take the Armory.
![image](https://github.com/user-attachments/assets/9280c4d5-4f4b-48b5-864b-20503d7dcc48)

**Missing Content:**
Okay, here's where the nit and gritty needs to happen.

**Missing Oracle**: We require that the entity called Oracle(A statue usually paired with Sophia) be placed somewhere on the map, preferably in the Science/Epistemics lobby.
![image](https://github.com/user-attachments/assets/00e87fee-d832-4dd8-bd98-92ecb00b384e)

**Missing Biomass Reclaimer Drain**: The biomass reclaimer is in an odd spot, placed inside the cloning bay. Usually we'd see it tucked away in the morgue. But I'm not going to ask you to move the reclaimer all the way to the morgue seeing as it's on the exact opposite side of the medbay. It'll just need to have a Drain placed under or in front of it.

**Missing Forensic Mantis:** We require a space be added for the ForensicMantis role be placed somewhere in the map, as well as a Job Spawner for the role. Given the map's unusual layout, you will probably want to convert one of the Maintenance Rooms into a sort of office/drugden for the Mantis to spawn in. Either of these two rooms are suitable(Although the second room may need to be expanded 1 or 2 tiles down):
![image](https://github.com/user-attachments/assets/e24f5b05-a53e-43ca-863b-d4a8c34414c6)

![image](https://github.com/user-attachments/assets/9f1763a3-22c7-4418-a8a5-7e264ddb2ef8)

**Science-Security Checkpoint is Inaccessible:** This security checkpoint into Science cannot be reached by Security officers. This could be rectified by adding a Security airlock door leading into Maintenance.
![image](https://github.com/user-attachments/assets/6b2e64f9-f8eb-417c-9a86-efb5e9cfa222)

**Artifact Lab is missing Wall-Mounted Geiger Counters:**
![image](https://github.com/user-attachments/assets/68fdb066-888a-4297-92d2-5b7cbd6b7e58)

2024-10-08 00:11 UTC, DEATHB4DEFEAT commented on Content.IntegrationTests/Tests/PostMapInitTest.cs
> +			"Submarine", //DeltaV
```suggestion
            "Submarine", //DeltaV
```

2024-10-08 00:12 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Maps/gaxstation.yml
> +            Lawyer: [ 1, 1 ]
```suggestion
            Lawyer: [ 1, 1 ]
```

2024-10-08 00:20 UTC, VMSolidus requested changes

2024-10-08 00:20 UTC, VMSolidus commented on Resources/Prototypes/Maps/gaxstation.yml
> +            #Supply
```suggestion
            PrisonGuard: [ 1, 2 ]
            Brigmedic: [ 1, 1 ]
            Lawyer: [ 1, 1 ]            
            #Supply
```
You also need to add a spawner for said Brigmedic(Localized as Corpsman in our repo)

2024-10-08 00:20 UTC, VMSolidus commented on Resources/Prototypes/Maps/gaxstation.yml
> +            #Security
```suggestion
            Chaplain: [ 1, 1 ]
            Librarian: [ 1, 1 ]
            ForensicMantis: [ 1, 1 ]
            #Security
```
Will also need a spawner added.

2024-10-08 14:31 UTC, rbertoche commented
Can't miss the opportunity to say the map is awesome though, me myself and players in general like it! It's surely been a milestone on original maps on Pirata, thanks mostly to @Ichaie, also others but I think it's mostly Ichai's.

2024-10-08 15:04 UTC, VMSolidus commented
In any case, the changes I've requested are small and easy to do, so I don't mind approving this after they're done. :)

2024-10-08 15:09 UTC, VMSolidus commented
Also the map yml has some "INVALID" entries in it. Those will need to be deleted.

2024-10-08 23:05 UTC, Ichaie commented
![imagem_2024-10-08_200311191](https://github.com/user-attachments/assets/58fde524-9797-410a-83fd-64092907a476)
![imagem_2024-10-08_200347614](https://github.com/user-attachments/assets/278320ce-8b63-4edc-909a-eac60f04f6a0)
![image](https://github.com/user-attachments/assets/840f008f-a1e9-468c-8fee-9513daa0ebdc)
@VMSolidus Here are some images of the changes to the map

2024-10-08 23:09 UTC, VMSolidus commented
Oh my gosh that Permabrig is gorgeous now.

2024-10-08 23:40 UTC, VMSolidus commented
![image](https://github.com/user-attachments/assets/95748011-493e-4cf3-ae2e-0bbd2b20cfac)

Looks like it needs to have a spawn point added for the medical borg. But all the rest of the tests are fine. :)

2024-10-09 00:39 UTC, VMSolidus approved these changes

2024-10-09 01:36 UTC, FoxxoTrystan approved these changes

2024-10-09 01:37 UTC, merged