Canister texture porting
Simple-Station/Einstein-Engines pull request #1028
Opened 2024-10-09 16:32 UTC by CilliePaint

# Description

This Pull Request seeks to start the porting of BayStation Textures to the EE engine, starting off with Canisters. These Canisters are from a 2022 PR of BayStation and are the latest of their texturing.

---

<details><summary><h1>Media</h1></summary>
<p>

![Example Media Embed](https://file.garden/Yy0ydNX23DJlLOUl/SS14EE/Cans.png)

</p>
</details>

---

# Changelog

:cl:
- tweak: Atmos tanks have been given a fresh new design, Atmosians rejoice!

2024-10-09 18:19 UTC, Mnemotechnician commented
finally, explosive barrels in ss14

2024-10-09 18:21 UTC, CilliePaint commented
> finally, explosive barrels in ss14

make sure to shoot them

2024-10-09 19:05 UTC, FoxxoTrystan requested changes
Is there some missing files?

Files can-oa1.png and red.png are still unmodified, and pretty sure thats not indended.

2024-10-09 19:51 UTC, CilliePaint commented
> Is there some missing files?
> 
> Files can-oa1.png and red.png are still unmodified, and pretty sure thats not indended.

yeah, couldn't figure out what oa1 actually was, i did just forget the red.png one though, oopsies

2024-10-09 20:03 UTC, CilliePaint commented
oa1 is a unused texture, so i didn't change it, forgot to say that......

2024-10-13 18:40 UTC, VMSolidus requested changes
Actually these could totally be added as new "High Capacity Canister" objects, rather than replace our similar, admittedly pretty nice canister sprites from Paradise. :)

2024-10-13 18:50 UTC, Evgencheg commented
> Actually these could totally be added as new "High Capacity Canister" objects, rather than replace our similar, admittedly pretty nice canister sprites from Paradise. :)

Yea, good idea. I want to add this now…

2024-10-13 23:22 UTC, CilliePaint commented
> Actually these could totally be added as new "High Capacity Canister" objects, rather than replace our similar, admittedly pretty nice canister sprites from Paradise. :)

I am not particularly good with programming, especially in SS14's jank-ass codebase, sorry

2025-04-10 15:02 UTC, closed without merging