[Feature] Generic Radial Selector Menu
Simple-Station/Einstein-Engines pull request #1071
Opened 2024-10-17 04:33 UTC by Remuchi

# Description

Introduced a generic radial selector menu. Switched shortconstructionsystem from it's own BUI to radial selector.

---

<details><summary><h1>Media</h1></summary>
<p>

![Example Media Embed](https://example.com/thisimageisntreal.png)

</p>
</details>

---

# Changelog

no cl no fun (no changelog for players)

2024-10-17 17:11 UTC, VMSolidus requested changes
This is needed so that clicking on an item craft doesn't **instantaneously** craft between 7 and 14 of that item depending on your ping, and instead only crafts 1 per click. This also fixes the issue of the menu briefly following the cursor when opening it. The reason that was happening was because it was actually opening the menu 7 to 14 times in rapid succession under the mouse cursor due to misprediction.

Other than that, my testing shows that this system works just fine.

2024-10-17 17:11 UTC, VMSolidus commented on Content.Client/ShortConstruction/ShortConstructionSystem.cs
> +            return;
```suggestion
        if (!_proto.TryIndex(args.SelectedItem, out ConstructionPrototype? prototype)
            || !_gameTiming.IsFirstTimePredicted)
            return;
```

2024-10-17 17:11 UTC, VMSolidus commented on Content.Client/ShortConstruction/ShortConstructionSystem.cs
> +
```suggestion
    [Dependency] private readonly IGameTiming _gameTiming = default!;
```

2024-10-17 17:11 UTC, VMSolidus commented on Content.Client/ShortConstruction/ShortConstructionSystem.cs
> +using Robust.Shared.Prototypes;
```suggestion
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
```

2024-10-17 17:11 UTC, VMSolidus commented on Content.Client/RadialSelector/RadialSelectorMenuBUI.cs
> +using Robust.Shared.Prototypes;
```suggestion
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
```

2024-10-17 17:11 UTC, VMSolidus commented on Content.Client/RadialSelector/RadialSelectorMenuBUI.cs
> +        if (state is not RadialSelectorState radialSelectorState)
```suggestion
        if (state is not RadialSelectorState radialSelectorState
            || !_gameTiming.IsFirstTimePredicted)
```

2024-10-17 17:11 UTC, VMSolidus commented on Content.Client/RadialSelector/RadialSelectorMenuBUI.cs
> +    [Dependency] private readonly IPrototypeManager _protoManager = default!;
```suggestion
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IGameTiming _gameTiming = default!;
```

2024-10-20 03:38 UTC, VMSolidus approved these changes

2024-10-20 07:00 UTC, Aidenkrz approved these changes
need this for muh pr, maints merge faster, thanks!

2024-10-20 16:01 UTC, Peptide90 approved these changes

2024-10-20 16:01 UTC, merged