[Feature] Clicking on health alerty now displays health state
Simple-Station/Einstein-Engines pull request #1139
Opened 2024-10-24 06:11 UTC by Remuchi

# Description

I don't understand why it hasn't been done before tbf.

https://github.com/user-attachments/assets/6ea2a3eb-80ce-4905-b546-7b8902308533

---

# Changelog

:cl:
- add: Clicking on health alert now will print message in chat, displaying your health state.

2024-10-24 06:11 UTC, DEATHB4DEFEAT commented
> I don't understand why it hasn't been done before tbf.

'Cause it's in the examine menu

2024-10-24 06:12 UTC, Remuchi commented
> > I don't understand why it hasn't been done before tbf.
> 
> 'Cause it's in the examine menu

It's omega clunky to use.

2024-10-25 19:08 UTC, VMSolidus requested changes

2024-10-25 19:08 UTC, VMSolidus commented on Content.Shared/HealthExaminable/HealthExaminableSystem.cs
> +        return CreateMarkup(examinable, examinable.Comp, damageable);
```suggestion
        return (examiner == examinable.Owner && TryComp<SelfAwareComponent>(examinable, out var selfAware))
            ? CreateMarkupSelfAware(examinable, selfAware, examinable.Comp, damageable)
            : CreateMarkup(examinable, examinable.Comp, damageable);
```

2024-10-26 06:59 UTC, VMSolidus approved these changes

2024-10-27 09:29 UTC, Peptide90 approved these changes

2024-10-27 15:36 UTC, merged