Mirror: Vegan Meatball
Simple-Station/Einstein-Engines pull request #114
Opened 2024-04-21 09:49 UTC by SimpleStation14

## Mirror of  PR #24650: [Vegan Meatball](https://github.com/space-wizards/space-station-14/pull/24650) from <img src="https://avatars.githubusercontent.com/u/10567778?v=4" alt="space-wizards" width="22"/> [space-wizards](https://github.com/space-wizards)/[space-station-14](https://github.com/space-wizards/space-station-14)

###### `5f61380209146a83be27270372c4c54d62b007b2`

PR opened by <img src="https://avatars.githubusercontent.com/u/140123969?v=4" width="16"/><a href="https://github.com/Blackern5000"> Blackern5000</a> at 2024-01-28 04:07:26 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-07 19:37:57 UTC

---

PR changed 3 files with 1699 additions and 0 deletions.

The PR had the following labels:
- No C#
- Changes: Map
- Status: Needs Review

---

<details open="true"><summary><h1>Original Body</h1></summary>

> ## About the PR
> Adds a new salvage called "Vegan Meatball"
> I was sorta going for a "mystical plant orb" feel
> 
> ## Why / Balance
> Just one anomaly salvage wasn't enough
> 
> ## Media
> ![image](https://github.com/space-wizards/space-station-14/assets/140123969/c56babcb-254c-479d-9e84-71dd56800ef8)
> ![image](https://github.com/space-wizards/space-station-14/assets/140123969/3b1d52d6-e60e-48ec-8d11-39332d7620cc)
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> **Changelog**
> 
> :cl:
> - add: Salvagers can now pull in overgrown floral anomalies.
> 

</details>

2024-04-30 20:06 UTC, DangerRevolution approved these changes

2024-04-30 20:07 UTC, DangerRevolution requested changes
this should be checked in-game and brought up to standard actually

2024-05-09 03:33 UTC, VMSolidus approved these changes
This is fine actually, ironically it's one of the more dangerous salvage wrecks.

2024-05-13 13:44 UTC, DangerRevolution approved these changes

2024-05-13 13:44 UTC, merged