Emp Flashlight (#5)
Simple-Station/Einstein-Engines pull request #1189
Opened 2024-11-08 17:13 UTC by VMSolidus

* EmpFlashlight added

* Using namespace cleared

* Code Review problems solved

# Description

Ports https://github.com/WWhiteDreamProject/wwdpublic/pull/5

# Changelog

:cl:
- add: Added the EMP Flashlight to Syndicate Uplinks.

2024-11-09 19:17 UTC, FoxxoTrystan requested changes
Remove _White directory for nearly most files.

2024-11-16 01:21 UTC, VMSolidus commented
Ready to go.

2024-11-17 19:55 UTC, FoxxoTrystan approved these changes

2024-12-04 00:01 UTC, sleepyyapril approved these changes

2024-12-04 00:11 UTC, merged