Add Missing `DOTNET_ROOT` Environment Variable For Nix Devs
Simple-Station/Einstein-Engines pull request #1203
Opened 2024-11-10 12:36 UTC by DocNITE

# Description

Added missing environment variable for nix-shell. I don't like everytime write `export DOTNET_ROOT="/path/to/folder"`, so it should be done by post script in `shell.nix`

2024-11-10 18:11 UTC, stellar-novas commented
Why do you need to set the DOTNET_ROOT variable? I haven't needed to before

2024-11-10 18:21 UTC, stellar-novas commented
> > Why do you need to set the DOTNET_ROOT variable? I haven't needed to before
> 
> It's needed if you have a non-standard dotnet installation. I have this variable defined in my /etc/profile (linux).

I'm a nix user and I don't need to set it, that's why I'm confused

2024-11-10 20:54 UTC, DEATHB4DEFEAT requested changes

2024-11-10 20:54 UTC, DEATHB4DEFEAT commented on shell.nix
> +    export DOTNET_ROOT=${pkgs.dotnetCorePackages.sdk_8_0}
```suggestion
    export DOTNET_ROOT=${pkgs.dotnetCorePackages.sdk_8_0_1xx}
    export PATH="$PATH:/home/$(whoami)/.dotnet/tools"
```

2024-11-10 20:55 UTC, DEATHB4DEFEAT commented
> I'm a nix user and I don't need to set it, that's why I'm confused

I needed to set it to use dotnet tools to create a migration for #1164

2024-11-11 01:34 UTC, DocNITE commented on shell.nix
> +    export DOTNET_ROOT=${pkgs.dotnetCorePackages.sdk_8_0}
Done!

2024-11-11 01:49 UTC, stellar-novas approved these changes

2024-11-11 06:22 UTC, DEATHB4DEFEAT approved these changes

2024-11-11 06:41 UTC, merged