Cherry pick Improvised Weaponry, DeltaV
Simple-Station/Einstein-Engines pull request #1217
Opened 2024-11-13 22:52 UTC by Tmanzxd

# Description

Adds Muskets, Flintlocks, Pipebombs, Firebombs, gunpowder, and craftable ammo for flintlock weaponry from DeltaV.

---

# TODO

- [x] Cherry-picked Muskets, Pipebombs, Firebombs, and Gunpowder crafting

---

<details><summary><h1>Media</h1></summary>
<p>

![Example Media Embed](https://example.com/thisimageisntreal.png)

</p>
</details>

---

# Changelog

:cl:
- add: Muskets, Flintlocks, Pipebombs, Firebombs, gunpowder, and craftable ammo for flintlock weaponry.

2024-11-13 23:01 UTC, Tmanzxd commented
Ah, Duplicate ID, my weakness

2024-11-13 23:35 UTC, Tmanzxd commented
Zinga

2024-11-14 02:16 UTC, VMSolidus approved these changes
Fun

2024-11-15 19:19 UTC, Tmanzxd commented
Spoke to a goob maintainer, they mentioned that the Mosin has the same sprite as the Musket. Are we going to want to resprite one of them?

2024-11-21 15:57 UTC, FoxxoTrystan requested changes
Were heavly recomending to move everything out of forks namespaces as we are a hardfork.

Please move it to EE/Normal Namespace whenever possible.

2024-11-21 15:57 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/Entities/Objects/Misc/improvised_gun_parts.yml
Move to this to normal namespace.

2024-11-21 15:57 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/musket.yml
Move to this to normal namespace.

2024-11-21 15:57 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/musket.yml
Move to this to normal namespace.

2024-11-21 15:57 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
Move to this to normal namespace.

2024-11-21 15:57 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
Move to this to normal namespace.

2024-11-21 15:57 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/Recipes/Crafting/Graphs/improvised/bayonet.yml
Move to this to normal namespace.

2024-11-21 15:57 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/Recipes/Crafting/Graphs/improvised/modular_breech.yml
Move to this to normal namespace.

2024-11-21 15:57 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/Recipes/Crafting/Graphs/improvised/modular_trigger.yml
Move to this to normal namespace.

2024-11-21 15:57 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/Recipes/Crafting/Graphs/improvised/musket.yml
Move to this to normal namespace.

2024-11-21 15:57 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/Recipes/Crafting/Graphs/improvised/musket_cartridge.yml
Move to this to normal namespace.

2024-11-21 15:57 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/Recipes/Crafting/improvised.yml
Move to this to normal namespace.

2024-11-21 15:57 UTC, FoxxoTrystan commented on Resources/Prototypes/DeltaV/tags.yml
Move to this to normal namespace.

2024-11-21 15:57 UTC, FoxxoTrystan commented on Resources/Textures/DeltaV/Objects/Misc/bayonet.rsi/base.png
Move to this to normal namespace.

2024-12-03 19:33 UTC, Tmanzxd commented
Sorry for the hiatus, Thanksgiving Break and school stuff. Will try to get this done.

2025-02-27 02:25 UTC, VMSolidus commented
Closing this as these items were already added in another PR.

2025-02-27 02:25 UTC, closed without merging