Bounties Localization Fix
Simple-Station/Einstein-Engines pull request #1219
Opened 2024-11-14 02:06 UTC by sleepyyapril

# Description

The grammar and spelling police came... they took your mistakes (some).

2024-11-14 02:07 UTC, VMSolidus requested changes

2024-11-14 02:07 UTC, VMSolidus commented on Resources/Locale/en-US/cargo/bounties.ftl
> +bounty-description-wine = The new librarian and the Logistics Officer are falling head over heels for each other after she caught him disassembling the bookshelves for wood. Send a couple bottles of
```suggestion
bounty-description-wine = The new cataloger and the Logistics Officer are falling head over heels for each other after she caught him disassembling the bookshelves for wood. Send a couple bottles of wine (Or cans, if you must) to help make the date go well.
```

2024-11-14 02:09 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/cargo/bounties.ftl
> +bounty-description-knife = One of our top commanders recently won a brand new set of knives on an official Nanotrasen gameshow, but unforunately, we don't have a set on hand. Send us a bunch of sharp
```suggestion
bounty-description-knife = One of our top commanders recently won a brand new set of knives on an official Nanotrasen gameshow, but, unforunately, we don't have a set on hand. Send us a bunch of sharp things so we can throw something together.
```

2024-11-14 20:24 UTC, VMSolidus approved these changes

2024-11-15 09:02 UTC, Peptide90 approved these changes

2024-11-15 14:08 UTC, merged