the return of spray paint
Simple-Station/Einstein-Engines pull request #1222
Opened 2024-11-14 07:07 UTC by DEATHB4DEFEAT

# Description

Description.

---

# TODO

- [ ] Task
- [x] Completed Task

---

<details><summary><h1>Media</h1></summary>
<p>

![Example Media Embed](https://example.com/thisimageisntreal.png)

</p>
</details>

---

# Changelog

:cl:
- add: Added fun :D
- tweak: Tweaked fun
- fix: Fixed fun!
- remove: Removed fun :(

2024-11-14 20:22 UTC, VMSolidus requested changes

2024-11-14 20:22 UTC, VMSolidus commented on Content.Server/Paint/PaintSystem.cs
> +            }
```suggestion
            if (HasComp<InventoryComponent>(target) // Paint any clothing the target is wearing.
                && _inventory.TryGetSlots(target, out var slotDefinitions))
                foreach (var slot in slotDefinitions)
                {
                    if (!_inventory.TryGetSlotEntity(target, slot.Name, out var slotEnt)
                        || HasComp<PaintedComponent>(slotEnt.Value)
                        || !entity.Comp.Blacklist?.IsValid(slotEnt.Value, EntityManager) != true
                        || HasComp<RandomSpriteComponent>(slotEnt.Value)
                        || HasComp<HumanoidAppearanceComponent>(slotEnt.Value))
                        continue;

                    EnsureComp<PaintedComponent>(slotEnt.Value, out var slotToPaint);
                    EnsureComp<AppearanceComponent>(slotEnt.Value);
                    slotToPaint.Color = entity.Comp.Color;
                    _appearanceSystem.SetData(slotEnt.Value, PaintVisuals.Painted, true);
                    Dirty(slotEnt.Value, slotToPaint);
                }
```
Gaming.

2024-11-14 20:22 UTC, VMSolidus commented on Content.Server/Paint/PaintSystem.cs
> +            return;
```suggestion
        if (!args.CanReach
            || args.Target is not { Valid: true } target)
            return;
```

2024-11-14 20:22 UTC, VMSolidus commented on Content.Server/Paint/PaintSystem.cs
> +    }
```suggestion
    private void PrepPaint(EntityUid uid, PaintComponent component, EntityUid target, EntityUid user) =>
        _doAfterSystem.TryStartDoAfter(new DoAfterArgs(EntityManager, user, component.Delay, new PaintDoAfterEvent(), uid, target: target, used: uid)
        {
            BreakOnUserMove = true,
            BreakOnTargetMove = true,
            NeedHand = true,
            BreakOnHandChange = true,
        });
```
You don't have to do this particular one, I was just curious of it was possible. :3

2024-11-14 20:22 UTC, VMSolidus commented on Content.Server/Paint/PaintSystem.cs
> +        }
```suggestion
        if (HasComp<InventoryComponent>(target)
            && _inventory.TryGetSlots(target, out var slotDefinitions))
            foreach (var slot in slotDefinitions)
            {
                if (!_inventory.TryGetSlotEntity(target, slot.Name, out var slotEnt)
                    || blacklist.IsValid(slotEnt.Value, EntityManager))
                    continue;

                EnsureComp<PaintedComponent>(slotEnt.Value, out var slotToPaint);
                EnsureComp<AppearanceComponent>(slotEnt.Value);
                slotToPaint.Color = color;
                _appearanceSystem.SetData(slotEnt.Value, PaintVisuals.Painted, true);
                Dirty(slotEnt.Value, slotToPaint);
            }
```

2024-11-14 20:22 UTC, VMSolidus commented on Content.Server/Paint/PaintSystem.cs
> +    }
```suggestion
    private bool CanPaint(Entity<PaintComponent> reagent, EntityUid target)
    {
        if (HasComp<HumanoidAppearanceComponent>(target) 
            || HasComp<SubFloorHideComponent>(target)
            || !_solutionContainer.TryGetSolution(reagent.Owner, reagent.Comp.Solution, out _, out var solution))
            return false;

        var quantity = solution.RemoveReagent(reagent.Comp.Reagent, reagent.Comp.ConsumptionUnit);
        return (quantity > 0);
    }
```

2024-11-14 20:22 UTC, VMSolidus commented on Content.Client/Paint/PaintVisualizerSystem.cs
> +            return;
```suggestion
        var shader = _protoMan.Index<ShaderPrototype>(component.ShaderName).Instance();

        if (args.Sprite == null)
            return;

        // What is this even doing? It's not even checking what the value is.
        if (!_appearance.TryGetData(uid, PaintVisuals.Painted, out bool isPainted))
            return;
```
I'm reasonably sure that _protoMan has a TryIndex that can be used as a guard clause here, and thus all 3 of these can be combined.

2024-11-15 01:27 UTC, DEATHB4DEFEAT commented
Ignore the code style stuff in here; https://github.com/Simple-Station/Einstein-Engines/pull/1226

2024-11-15 01:43 UTC, VMSolidus approved these changes

2024-11-15 14:08 UTC, merged