More Dangerous Mindbreaking
Simple-Station/Einstein-Engines pull request #1249
Opened 2024-11-19 01:43 UTC by VMSolidus

# Description

Somehow people weren't getting the memo despite the **HORRIFYING** texts associated with Mindbreaking, that doing so is an almost comically evil act akin to murder. So this PR fixes that. By making it even more obvious.

<details><summary><h1>Media</h1></summary>
<p>

![image](https://github.com/user-attachments/assets/cf3280a5-42b3-4137-9191-f1ad26773ced)

</p>
</details>

# Changelog

:cl:
- add: Added a server option for "Scarier Mindbreaking". Mindbreaking now irreversibly converts a player character into a non-sentient NPC.

2024-11-19 01:57 UTC, bruhmogus commented
will this be on or off by default, since LSD + hypospray is able to really fuck up balance (just a tad)

2024-11-19 01:58 UTC, VMSolidus commented
> will this be on or off by default, since LSD + hypospray is able to really fuck up balance (just a tad)

Just don't take the Latent Psychic trait. 
![faridaiscute](https://github.com/user-attachments/assets/d278cdb9-6327-4094-bc2e-bd4a2ed84bd7)

2024-11-19 02:01 UTC, bruhmogus commented
> > will this be on or off by default, since LSD + hypospray is able to really fuck up balance (just a tad)
> 
> Just don't take the Latent Psychic trait.

iirc you can mindbreak someone who isnt even a psionic

2024-11-19 02:02 UTC, VMSolidus commented
> > > will this be on or off by default, since LSD + hypospray is able to really fuck up balance (just a tad)
> > 
> > 
> > Just don't take the Latent Psychic trait.
> 
> iirc you can mindbreak someone who isnt even a psionic

I'm going to fix that *right now*

2024-11-19 02:03 UTC, VMSolidus commented
> > > will this be on or off by default, since LSD + hypospray is able to really fuck up balance (just a tad)
> > 
> > 
> > Just don't take the Latent Psychic trait.
> 
> iirc you can mindbreak someone who isnt even a psionic

Done.
![image](https://github.com/user-attachments/assets/4f6bc6f3-1e08-4ea2-9857-44720c4cc976)

2024-11-19 02:04 UTC, bruhmogus commented
also how will this play with the trait that literally gives you the mindbroken component roundstart

2024-11-19 02:05 UTC, VMSolidus commented
> also how will this play with the trait that literally gives you the mindbroken component roundstart

It doesn't. 
![Chadly](https://github.com/user-attachments/assets/fd83d801-54b0-4338-b457-f7df3230fbb9)

2024-11-19 02:06 UTC, bruhmogus commented
> > also how will this play with the trait that literally gives you the mindbroken component roundstart
> 
> It doesn't. 

hm. maybe it should, but at the same time it'd be hilarious to instantly get ghosted for having the trait

2024-11-19 02:12 UTC, gluesniffler commented
> > > also how will this play with the trait that literally gives you the mindbroken component roundstart
> > 
> > 
> > It doesn't.
> 
> hm. maybe it should, but at the same time it'd be hilarious to instantly get ghosted for having the trait

It's better this way, because then you have to doubt whether or not the person you're talking to is an NPC or not IC, giving you more leeway to abuse them (killing a mindbroken person at best counts as animal abuse)

2024-11-19 02:14 UTC, VMSolidus commented
> > > > also how will this play with the trait that literally gives you the mindbroken component roundstart
> > > 
> > > 
> > > It doesn't.
> > 
> > 
> > hm. maybe it should, but at the same time it'd be hilarious to instantly get ghosted for having the trait
> 
> It's better this way, because then you have to doubt whether or not the person you're talking to is an "NPC" or not IC, giving you more leeway to abuse them (killing a mindbroken person at best counts as animal abuse)

It would be even funnier if we rebased the NPCConversationSystem from Nyano, and/or make the mindbroken NPCs talk using ChatGPT2.

2024-11-19 02:25 UTC, bruhmogus commented
> > > > also how will this play with the trait that literally gives you the mindbroken component roundstart
> > > 
> > > 
> > > It doesn't.
> > 
> > 
> > hm. maybe it should, but at the same time it'd be hilarious to instantly get ghosted for having the trait
> 
> It's better this way, because then you have to doubt whether or not the person you're talking to is an "NPC" or not IC, giving you more leeway to abuse them (killing a mindbroken person at best counts as animal abuse)

this confuses me, have we tested what actually happens if someone has the instant mindbreak trait? will it insta-ghost? will it let them keep playing?

2024-11-19 02:26 UTC, VMSolidus commented
> > > > > also how will this play with the trait that literally gives you the mindbroken component roundstart
> > > > 
> > > > 
> > > > It doesn't.
> > > 
> > > 
> > > hm. maybe it should, but at the same time it'd be hilarious to instantly get ghosted for having the trait
> > 
> > 
> > It's better this way, because then you have to doubt whether or not the person you're talking to is an "NPC" or not IC, giving you more leeway to abuse them (killing a mindbroken person at best counts as animal abuse)
> 
> this confuses me, have we tested what actually happens if someone has the instant mindbreak trait? will it insta-ghost? will it let them keep playing?

It doesn't lmao. It doesn't even call this function.

2024-11-19 02:28 UTC, bruhmogus commented
> > > > > > also how will this play with the trait that literally gives you the mindbroken component roundstart
> > > > > 
> > > > > 
> > > > > It doesn't.
> > > > 
> > > > 
> > > > hm. maybe it should, but at the same time it'd be hilarious to instantly get ghosted for having the trait
> > > 
> > > 
> > > It's better this way, because then you have to doubt whether or not the person you're talking to is an "NPC" or not IC, giving you more leeway to abuse them (killing a mindbroken person at best counts as animal abuse)
> > 
> > 
> > this confuses me, have we tested what actually happens if someone has the instant mindbreak trait? will it insta-ghost? will it let them keep playing?
> 
> It doesn't lmao. It doesn't even call this function.

oh! thats perfect! as someone with Zero Maintainer Authority™ i'd say this works really well

2024-11-20 02:22 UTC, Erisfiregamer1 commented
> > > > > also how will this play with the trait that literally gives you the mindbroken component roundstart
> > > > 
> > > > 
> > > > It doesn't.
> > > 
> > > 
> > > hm. maybe it should, but at the same time it'd be hilarious to instantly get ghosted for having the trait
> > 
> > 
> > It's better this way, because then you have to doubt whether or not the person you're talking to is an "NPC" or not IC, giving you more leeway to abuse them (killing a mindbroken person at best counts as animal abuse)
> 
> It would be even funnier if we rebased the NPCConversationSystem from Nyano, and/or make the mindbroken NPCs talk using ChatGPT2.

Just use the free Groq API and something like Llama3 on the server, I could probably help you write the code for it. It'd be funny!!

2024-11-21 15:51 UTC, FoxxoTrystan requested changes
Make it false a lot of servers will not enjoy this change if they update and they dont know about it, this should be toggled true on server choices.

2024-11-21 15:51 UTC, FoxxoTrystan commented on Content.Shared/CCVar/CCVars.cs
> +            CVarDef.Create("psionics.scarier_mindbreaking", true, CVar.SERVERONLY);
```suggestion
            CVarDef.Create("psionics.scarier_mindbreaking", false, CVar.SERVERONLY);
```

2024-11-30 21:04 UTC, sleepyyapril approved these changes

2024-11-30 21:11 UTC, bruhmogus commented
![20241130151052_1](https://github.com/user-attachments/assets/0545f346-3080-405a-a336-b5a3730be7d0)

mindbreaking's punishment should be changed if this is merged, as it basically kills them (and might be prevention of revival?)

2024-11-30 21:13 UTC, VMSolidus commented
> ![20241130151052_1](https://private-user-images.githubusercontent.com/104110869/391288431-0545f346-3080-405a-a336-b5a3730be7d0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMDE0MzAsIm5iZiI6MTczMzAwMTEzMCwicGF0aCI6Ii8xMDQxMTA4NjkvMzkxMjg4NDMxLTA1NDVmMzQ2LTMwODAtNDA1YS1hMzM2LWI1YTM3MzBiZTdkMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQyMTEyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2FhMmY4OGZmODQ1ZjcyZjRhNDZmNGIxZmU1ZDYyMTMzOGQ3MDdjNzMwYjM1Yzc2OGMyNWIzMjU2YmQ2Zjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qr9dXh09QrP6mAhRiYlNwojAFEMgxsYdcQnY00j4HDE)
> 
> mindbreaking's punishment should be changed if this is merged, as it basically kills them (and might be prevention of revival?)

I completely forgot this DeltaV feature even exists lmao. Yea mindbreaking people on EE is not like mindbreaking people on DeltaV. The design intention behind it is that mindbreaking someone is essentially a "Metaphysical" form of murder, and thus  should be reserved only as a capital punishment, or as Self-Defense in the case of being attacked by someone with psionic powers.

2024-11-30 22:48 UTC, bruhmogus commented
> > ![20241130151052_1](https://private-user-images.githubusercontent.com/104110869/391288431-0545f346-3080-405a-a336-b5a3730be7d0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMDE0MzAsIm5iZiI6MTczMzAwMTEzMCwicGF0aCI6Ii8xMDQxMTA4NjkvMzkxMjg4NDMxLTA1NDVmMzQ2LTMwODAtNDA1YS1hMzM2LWI1YTM3MzBiZTdkMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQyMTEyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2FhMmY4OGZmODQ1ZjcyZjRhNDZmNGIxZmU1ZDYyMTMzOGQ3MDdjNzMwYjM1Yzc2OGMyNWIzMjU2YmQ2Zjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qr9dXh09QrP6mAhRiYlNwojAFEMgxsYdcQnY00j4HDE)
> > mindbreaking's punishment should be changed if this is merged, as it basically kills them (and might be prevention of revival?)
> 
> I completely forgot this DeltaV feature even exists lmao. Yea mindbreaking people on EE is not like mindbreaking people on DeltaV. The design intention behind it is that mindbreaking someone is essentially a "Metaphysical" form of murder, and thus should be reserved only as a capital punishment, or as Self-Defense in the case of being attacked by someone with psionic powers.

yeah what im saying is just "this is literal murder, and should be treated as such"

2024-12-03 23:26 UTC, RustedBR commented
Isn't this, for the player, the same thing as getting sacrificed as a psion?

2024-12-07 02:28 UTC, DEATHB4DEFEAT approved these changes

2024-12-16 15:22 UTC, merged