You can now drag people into deep friers
Simple-Station/Einstein-Engines pull request #1279
Opened 2024-11-24 23:20 UTC by Erisfiregamer1

# Description

You can now drag entities like people into deep fryers. Yes, this will cook them. Yes, you can cannibalize your own dead crew.

---

# TODO

- [ ] Add a doafter
- [ ] Fix the mispredict if I do NOT add a doafter
- [ ] 

---

<details><summary><h1>Media</h1></summary>
<p>

obs is broken part 295

</p>
</details>

---

# Changelog

:cl:
- add: You can now shove people into deep fryers by drag-dropping them onto it.

2024-11-24 23:36 UTC, VMSolidus requested changes

2024-11-24 23:36 UTC, VMSolidus commented on Content.Server/Nyanotrasen/Kitchen/EntitySystems/DeepFryerSystem.cs
> +            oilToUse = 10; // Default until I figure out how in the 24 hells to get an entity's mass and just use that
```suggestion
            oilToUse = TryComp<PhysicsComponent>(item, out var physicsComponent) ? physicsComponent.Mass : 10;
```

2024-11-24 23:37 UTC, Erisfiregamer1 commented on Content.Server/Nyanotrasen/Kitchen/EntitySystems/DeepFryerSystem.cs
> +            oilToUse = 10; // Default until I figure out how in the 24 hells to get an entity's mass and just use that
ah, so *that's* how I do that

2024-11-25 01:24 UTC, Erisfiregamer1 commented
@VMSolidus your changes broke compiling (it compiled fine before then)

i am now going to deep fry my IDE

2024-11-25 01:24 UTC, Erisfiregamer1 commented
WHY DID IT CLOSE IT I HIT COMMENT

2024-11-25 01:26 UTC, DocNITE commented
mmmm... Fried harpy :woozy_face:

2024-11-25 02:26 UTC, Erisfiregamer1 commented
Ready for review, I've added the needed import and it should build.

Needs a Surgery fix though as when the affected burns up they don't actually dust and instead turn into a torsoless abomination

2024-11-29 12:55 UTC, BlueHNT commented
If you can deep-fry brains, why not deep-fry people huh? The court of judgement will view this as Prime Murder for sure!

2024-11-29 22:25 UTC, Erisfiregamer1 commented on Content.Shared/Nyanotrasen/Kitchen/SharedDeepfryerSystem.cs
> +    }
I'll keep that in mind!

2024-11-30 17:10 UTC, Erisfiregamer1 commented
Ready for merge pending next positive review- the neccesary Shitmed update was merged to make it function Correctly.

2024-11-30 20:41 UTC, sleepyyapril approved these changes

2024-12-03 23:33 UTC, merged