Fix melee weapon attack speed
Simple-Station/Einstein-Engines pull request #1330
Opened 2024-12-09 16:44 UTC by dge21

Description.

Melee weapons got swapped from attacks/second to second/attack but the actual attack rate value didn't get changed so weapons got all jumbled. I'm pretty sure I got them all but I might've missed a few in weird folders

:cl:
- fix: Fixed melee weapons.

2024-12-09 17:25 UTC, VMSolidus requested changes

2024-12-09 17:25 UTC, VMSolidus commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +    attackRate: .6
```suggestion
    attackRate: .6666
```

2024-12-09 17:25 UTC, VMSolidus commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +    attackRate: .6
```suggestion
    attackRate: .6666
```

2024-12-09 17:25 UTC, VMSolidus commented on Resources/Prototypes/Entities/Objects/Fun/Instruments/instruments_string.yml
> +    heavyRateModifier: 1.3
```suggestion
    heavyRateModifier: 1.3333
```

2024-12-09 17:25 UTC, VMSolidus commented on Resources/Prototypes/Entities/Objects/Materials/crystal_shard.yml
> +    attackRate: .6
```suggestion
    attackRate: .6666
```

2024-12-09 17:25 UTC, VMSolidus commented on Resources/Prototypes/Entities/Objects/Misc/utensils.yml
> +    attackRate: .6
```suggestion
    attackRate: .6666
```

2024-12-09 17:25 UTC, VMSolidus commented on Resources/Prototypes/Entities/Objects/Misc/utensils.yml
> +    attackRate: .6
```suggestion
    attackRate: .6666
```

2024-12-09 17:25 UTC, VMSolidus commented on Resources/Prototypes/Entities/Objects/Tools/cowtools.yml
> +    attackRate: .6
```suggestion
    attackRate: .6666
```

2024-12-09 17:53 UTC, angelofallars requested changes
We also need to adjust the attack speed values of the weapons in the `Nyanotrasen`, `DeltaV` and `WhiteDream` (blood cult) namespaces, and there are many of them. Except for the `LunchboxGeneric` in `DeltaV`, as I already dealt with its attack speed.

2024-12-09 20:06 UTC, dge21 commented
alright, I think I got everything now

2024-12-09 21:53 UTC, VMSolidus approved these changes

2024-12-10 00:42 UTC, OldDanceJacket commented
Did a glance over, everything looks good, thank you a ton.

2024-12-10 00:42 UTC, OldDanceJacket approved these changes

2024-12-10 00:43 UTC, merged