Revert bad "SS13" action bar
Simple-Station/Einstein-Engines pull request #1333
Opened 2024-12-11 06:00 UTC by DEATHB4DEFEAT

<details><summary><h1>Media</h1></summary>
<p>

https://github.com/user-attachments/assets/701512ce-1bf2-4020-a2eb-ba1e35b18669

</p>
</details>

---

# Changelog

:cl:
- tweak: Added back support for the action bar to have "loadouts" or quick layouts of actions (man, how many things are called loadouts?)

2024-12-11 06:13 UTC, Remuchi commented
I like it

2024-12-11 06:51 UTC, DEATHB4DEFEAT commented
> This pull request has conflicts, please resolve those before we can evaluate the pull request.

Took you a while.. How's that conflicting?? I made sure to branch off latest master!

2024-12-22 20:01 UTC, Remuchi requested changes

2024-12-22 20:02 UTC, DEATHB4DEFEAT commented on Content.Client/UserInterface/Systems/Actions/Controls/ActionButtonContainer.cs
> +        return;
it is

2024-12-22 20:09 UTC, Remuchi approved these changes

2024-12-22 20:24 UTC, sleepyyapril approved these changes

2024-12-23 09:33 UTC, sleepyyapril commented
test fails look real?

2024-12-23 09:49 UTC, Remuchi commented
![image](https://github.com/user-attachments/assets/bdad8dfb-3474-4ba1-81d1-c9c67697a249)
yeah this one is real

2024-12-30 02:24 UTC, merged