Switches off throw in MakeAntag to a log.Error to prevent further errors
Simple-Station/Einstein-Engines pull request #1339
Opened 2024-12-12 06:15 UTC by rbertoche

We might never see the end of new antags being added using MakeAntag so better just cut it off by the root and mitigating the issue by preventing it from causing the round to not start.

# Description

Since [this issue](https://discord.com/channels/1218698320155906090/1218701887990140999/1314367545226166333) still persisted to manifest even after an attempt to fix it, this PR simply prevents the rounds from not starting due to the error by changing the exception into a log error.

Catching and treating could be done instead, but I don't see many benefits from that at all, so an error it is. 

Cheers.

Description.

---

# TODO

- [ ] Task
- [x] Completed Task

---

<details><summary><h1>Media</h1></summary>
<p>

![Example Media Embed](https://example.com/thisimageisntreal.png)

</p>
</details>

---

# Changelog

:cl:
- add: Added fun :D
- tweak: Tweaked fun
- fix: Fixed fun!
- remove: Removed fun :(

2024-12-12 06:23 UTC, rbertoche commented
I tried to figure a way to still add the same antagonist it failted to assign in ChooseAntags, and considered decrementing i inside that loop, but then I didn't due to how decrementing i would make the loop prone to stalling. So we lose one antagonist, but get the round to start, best effort.

2024-12-12 07:00 UTC, Remuchi commented
Current implementation can lead to no antags being selected in the round at all. IMO if this error happens, the antag selection should reselect player for that role

2024-12-12 21:43 UTC, rbertoche commented
Agreed, but given the reason why it fails to assign I didn't figure a way to retry to assign the role without risking freezing on that loop on the case every candidate is not going to pass the checks.
I would do a change in that direction otherwise

2024-12-12 21:44 UTC, rbertoche commented
Well.
I can do a silly hack and like retry 5 times. That would retry, and would not risk a forever stalling loop. Is that a better change?

2024-12-12 21:46 UTC, rbertoche commented
Set a constant to determine the max number of attempts. Retry until that number or until the required slots are assigned. It wouldn't be too bad. I can do that later tonight.

2024-12-13 21:27 UTC, sleepyyapril requested changes
Make it return a bool. If it fails, try try again up to a constant number of tries.

2024-12-18 02:43 UTC, rbertoche commented
Would changing the signature of MakeAntag for this be worth it? It would make EE antag code less compatabol.
A new method on the other hand would have less potential of requiring conflicts.
For one I could do a new method, keep the exception and intercept it... But it would have the downside of not working properly for code which just calls MakeAntag. I am not even sure other code calls it... Maybe I am worrying for nothing.
But right now I would think making a retry count inside ChooseAntags would be the less impactful change which still would fix not picking enough antags.
But if you insist I will just make it return bool sure.

2024-12-19 14:37 UTC, sleepyyapril commented
> Would changing the signature of MakeAntag for this be worth it? It would make EE antag code less compatabol. A new method on the other hand would have less potential of requiring conflicts. For one I could do a new method, keep the exception and intercept it... But it would have the downside of not working properly for code which just calls MakeAntag. I am not even sure other code calls it... Maybe I am worrying for nothing. But right now I would think making a retry count inside ChooseAntags would be the less impactful change which still would fix not picking enough antags. But if you insist I will just make it return bool sure.

Mm, true, should be fine as is.

2024-12-22 07:42 UTC, rbertoche commented
So. I ended up changing MakeAntag a lot while preserving APIs. But now I need to properly test this, since it's not tiny anymore.
I think previous code was not great as a consequence of the lack of features on AntagSelectionPlayerPool - or maybe it shouldn't have become a named type at all and having to duplicate Random and List methods is a code smell? Anyway
The added methods make it way easier to write proper code to get N antags, and to filter the pool in a sane way.

2024-12-22 07:46 UTC, rbertoche commented
There's only one thing which I'm not sure about these last changes. Calling MakeAntag(ent, null, def) to fill up unused slots makes sense, but it may have unintended consequences.
What is better? Just leave some antags missing if count does not get to 0, or calling MakeAntag(ent, null, def)?

2024-12-22 08:13 UTC, rbertoche commented
Instead of writing a quick hack I tried to make MakeAntag better in a non-hacky way.

2024-12-22 09:22 UTC, rbertoche commented
Tested it briefly with a single connection. It did add Thief at roundstart with no issues and didn't break when there weren't any thief available at roundstart either.

2024-12-22 09:56 UTC, rbertoche commented
https://github.com/Simple-Station/Einstein-Engines/actions/runs/12452770702/job/34762138592#step:10:405

This looks relevant but I am not sure how to fix it. It's the Log.Error in the changes.

2024-12-22 10:04 UTC, rbertoche commented
I think this error is supposed to happen in the tests. This new ChooseAntags will detect the failure and try to assign the roles, so I could change it from an error to a info or at least a warning. But since I already copied the state of that code region from wizden I don't think it's worth it to change it to reduce the log level.

Feel free to fix the test as you think is appropriate and merge if you want, if it's convenient

2024-12-22 20:25 UTC, sleepyyapril commented
> https://github.com/Simple-Station/Einstein-Engines/actions/runs/12453149394/job/34762931010#step:10:362
> 
> This looks relevant but I am not sure how to fix it. It's the Log.Error in the changes.

Could check if the player is valid, like IsTerminatingOrDeleted, and if not choose another.

2024-12-23 11:30 UTC, rbertoche commented
Right, after you say it is seems so obvious :P
I assumed there weren't enough candidates in the test, I'm gonna try that

2025-03-20 07:21 UTC, Timfa2112 requested changes
Two style comments, the rest seems OK
Have you verified that this works? A video of it doing what it needs to do (if that's possible for this PR) would be nice

2025-03-20 07:21 UTC, Timfa2112 commented on Content.Server/Antag/AntagSelectionPlayerPool.cs
> +        List<ICommonSession> session_list = [];
```suggestion
        var session_list = new List<ICommonSession>();
```

2025-03-20 07:21 UTC, Timfa2112 commented on Content.Server/Antag/AntagSelectionSystem.cs
> +            List<ICommonSession> failed = [];
```suggestion
            var failed = new List<ICommonSession>();
```

2025-04-03 18:17 UTC, Timfa2112 approved these changes

2025-04-03 19:18 UTC, merged