Pointy Ears For Harpies And Arachne
Simple-Station/Einstein-Engines pull request #1348
Opened 2024-12-14 16:04 UTC by VMSolidus

# Description

Like half the art references I have for Harpies have them with elf-like pointed ears, another half have them with their feather tufts. We have pointy ears markings, so this PR makes it so that Harpies can have them. Actually it also gives them to Arachne, for similar reasons(It's an oddly common thing on Arachne/Lamia art depictions). 

# Changelog

:cl:
- add: Added a variety of Pointy Ears markings for Harpy and Arachne characters.

2024-12-14 16:13 UTC, sleepyyapril approved these changes

2024-12-14 16:15 UTC, angelofallars requested changes
Need to make sure Harpy and Arachne have at least 3 Head (Side) markings so they can have ears and two earrings at the same time.

2024-12-14 16:18 UTC, VMSolidus commented
> Need to make sure Harpy and Arachne have at least 3 Head (Side) markings so they can have ears and two earrings at the same time.

Done

2024-12-14 16:27 UTC, angelofallars approved these changes

2024-12-15 19:13 UTC, Remuchi approved these changes

2024-12-15 19:13 UTC, merged