Adjusts cargo market
Simple-Station/Einstein-Engines pull request #1377
Opened 2024-12-24 00:34 UTC by BlueHNT

# Description

Long story short, cargo and command abuses the new reverse-engineered suits and warning them as admins about it is getting quite tiring. So I decided to put my hand to the craft and comment them out for now, until a better way for them to be gotten is made.

I have also taken this opportunity to fix some of the longstanding issues with cargo I have had, such as there missing sec masks in the riot crate or there not being a way to get the swat items.

While I am still missing the properly developed versions with space proofing and minor cold/head protection, the old non ARCS riot suit will do for now.

This PR fixes https://github.com/Simple-Station/Einstein-Engines/issues/1376

---

# TODO

- [x] Remove problematic items from cargo
- [x] Add proper swat crate

Opt:
- [ ] Make proper swat set (soon:tm:)
- [ ] Adjust the armor values to fit better (can be delayed)

---

<details><summary><h1>Media</h1></summary>
<p>

I ain't got nothing chief.

</p>
</details>

---

# Changelog

:cl:
- add: Added swat crate
- tweak: Tweaked riot crate
- remove: Removed reverse-engineered syndicate suits from cargo
- remove: Removed MK32 "Universal" from cargo

2024-12-28 19:37 UTC, sleepyyapril commented
test fail real

2024-12-30 00:46 UTC, VMSolidus approved these changes

2024-12-30 03:28 UTC, VMSolidus commented
Test fails are legitimate.

2024-12-30 03:39 UTC, BlueHNT commented
I'm unable to find the issue.

2024-12-30 03:41 UTC, VMSolidus requested changes

2024-12-30 03:41 UTC, VMSolidus commented on Resources/Prototypes/Catalog/Fills/Crates/security.yml
> +      - id: Clothing
```suggestion
```

2024-12-30 03:48 UTC, VMSolidus approved these changes
It was a stray "-type: Clothing" in a place where there shouldn't have been one.

2024-12-30 04:26 UTC, BlueHNT commented
Yeah that 100% shouldn't have been there. No wonder I couldn't find it.

2024-12-30 19:34 UTC, VMSolidus requested changes

2024-12-30 19:34 UTC, VMSolidus commented on Resources/Prototypes/Damage/modifier_sets.yml
> +    Structural: 30
```suggestion
    Structural: 80
```
![image](https://github.com/user-attachments/assets/05f7734c-facb-4c8b-87e5-457b3c24acc3)
Pickaxe actually does 52.5 damage on a wide swing, and if you stack modifiers you can get it up to 78.75 structural. So to make it pickaxe-proof, it needs to be MUCH higher.

2024-12-30 21:12 UTC, OldDanceJacket approved these changes

2024-12-30 21:15 UTC, VMSolidus approved these changes

2024-12-30 21:23 UTC, merged