Mirror: Space damage now causes heat along with blunt
Simple-Station/Einstein-Engines pull request #154
Opened 2024-04-21 09:57 UTC by SimpleStation14

## Mirror of  PR #25770: [Space damage now causes heat along with blunt](https://github.com/space-wizards/space-station-14/pull/25770) from <img src="https://avatars.githubusercontent.com/u/10567778?v=4" alt="space-wizards" width="22"/> [space-wizards](https://github.com/space-wizards)/[space-station-14](https://github.com/space-wizards/space-station-14)

###### `c2d52e45404f09b95f87dbb8e12d2a0c7217a023`

PR opened by <img src="https://avatars.githubusercontent.com/u/134914314?v=4" width="16"/><a href="https://github.com/UbaserB"> UbaserB</a> at 2024-03-02 07:11:43 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-12 02:38:40 UTC

---

PR changed 2 files with 4 additions and 2 deletions.

The PR had the following labels:
- Needs Discussion
- No C#
- Status: Needs Review

---

<details open="true"><summary><h1>Original Body</h1></summary>

> ## About the PR
> 
> 
> Space burns your skin from the ionizing radiation and intense light. Also, your blood boils. Radiation would be too difficult to implement and generally not a good idea, so i decided to just do burn. The reason why it's under barotrauma instead of general space damage is because even if you're not in space your blood still boils from lack of pressure (aka barotrauma)
> 
> Makes space a tiny teensy little bit more dangerous by 0.5 damage increase per second along with making treatment more complex considering there is another added damage type.
> 
> ![image](https://github.com/space-wizards/space-station-14/assets/134914314/3a8b25c7-306c-4157-9da0-2ed334fbc3bb)
> 
> **Changelog**
> 
> :cl: Ubaser
> - tweak: Unpressurized areas now deal heat damage along with blunt.

</details>

2024-04-30 20:23 UTC, DangerRevolution requested changes
is heat the same as cold damage? if it is, okay. if it's not, should be changed

2024-05-11 21:02 UTC, stellar-novas commented
Applying any form of heat damage is odd. The only damage players should really take is asphyx and blunt due to barotrauma. 

Vacuum insulated thermoses exist for a reason, radiative heat transfer is *very* slow. 

The only additional damage types that *could* exist are heat and radiation, and those should be based on line of sight to the star. For context, https://github.com/space-wizards/space-station-14/pull/25770 and https://github.com/space-wizards/space-station-14/issues/26478.

I'm saying we close this, remove cold damage, and add solar damage soon :tm:

2024-05-11 21:05 UTC, DangerRevolution commented
just gonna mark this with discussion, :shrug:

2024-05-29 04:22 UTC, VMSolidus submitted a review, later dismissed

2024-05-29 04:23 UTC, VMSolidus commented
I'll agree with Nova that this isn't a needed change, and also, that's not even how space works either. Space isn't hot for any conventional reason, at least not in any reason that could be abstracted away as "Heat damage".

2024-05-29 04:23 UTC, closed without merging