Mirror: Contraband Storage Crate
Simple-Station/Einstein-Engines pull request #181
Opened 2024-04-22 09:28 UTC by SimpleStation14

## Mirror of  PR #25974: [Contraband Storage Crate](https://github.com/space-wizards/space-station-14/pull/25974) from <img src="https://avatars.githubusercontent.com/u/10567778?v=4" alt="space-wizards" width="22"/> [space-wizards](https://github.com/space-wizards)/[space-station-14](https://github.com/space-wizards/space-station-14)

###### `49c819373919d6ad2c7e1d802025782ecdce370b`

PR opened by <img src="https://avatars.githubusercontent.com/u/91865152?v=4" width="16"/><a href="https://github.com/PursuitInAshes"> PursuitInAshes</a> at 2024-03-10 18:12:13 UTC

---

PR changed 1 files with 12 additions and 0 deletions.

The PR had the following labels:
- No C#

---

<details open="true"><summary><h1>Original Body</h1></summary>

> ## About the PR
> Adds a Contraband Storage Crate for the armory. This can be used by mappers to provide better and more suitable storage then an empty rack.
> 
> ## Why / Balance
> Dumping items that were confiscated from the syndicate on the ground or in exposed racks felt wrong and unfitting for more stations. This provides an armory locked crate to fill that purpose.
> 
> ## Media
> ![Content Client_JYZIEQmEgm](https://github.com/space-wizards/space-station-14/assets/91865152/e458cda6-791c-4145-92c3-ae052482813a)
> 
> **Changelog**
> 
> No CL, not really player facing.
> 

</details>

2024-04-30 20:47 UTC, DangerRevolution requested changes
should have a locker too for variability + Delta uses lockers for this purpose

2024-05-06 01:06 UTC, VMSolidus commented
> should have a locker too for variability + Delta uses lockers for this purpose

That really should be a separate PR to be honest. Also this is a required Mirror for the DeltaV pile it seems.

2024-05-06 01:06 UTC, VMSolidus approved these changes

2024-05-06 20:04 UTC, DangerRevolution approved these changes
needs a locker one day

2024-05-09 03:25 UTC, merged