Mirror: Trading Outpost now has half buy-only and half sell-only pallets
Simple-Station/Einstein-Engines pull request #191
Opened 2024-04-22 09:30 UTC by SimpleStation14

## Mirror of  PR #25955: [Trading Outpost now has half buy-only and half sell-only pallets](https://github.com/space-wizards/space-station-14/pull/25955) from <img src="https://avatars.githubusercontent.com/u/10567778?v=4" alt="space-wizards" width="22"/> [space-wizards](https://github.com/space-wizards)/[space-station-14](https://github.com/space-wizards/space-station-14)

###### `c0bbbc33c19eafcc8defaa7f1ec2df42e485b435`

PR opened by <img src="https://avatars.githubusercontent.com/u/1471082?v=4" width="16"/><a href="https://github.com/wafehling"> wafehling</a> at 2024-03-10 02:47:02 UTC

---

PR changed 8 files with 226 additions and 123 deletions.

The PR had the following labels:
- Changes: Sprites
- Status: Needs Review

---

<details open="true"><summary><h1>Original Body</h1></summary>

> ## About the PR
> I added two new entity types, a buy and sell only cargo pallet, and added them to the trading outpost in place of the old pallets.
> 
> ## Why / Balance
> Since the day this was added, every single shift, at some point I'll hear someone in cargo yelling about how **"You sold stuff I just bought!"**
> 
> This seemed like the easiest way to fix the problem.
> 
> ## Technical details
> Added a variable to the cargo pallet component for labeling which type it is, added two new varieties of the cargo pallet to the yml, and adjusted all the calls for GetCargoPallets() to have boolean variables for buyOnly and sellOnly to tell the function what kind of call you're looking for. 
> 
> If you don't give it any specifics it'll still treat any pallet as a two-way one, but this function is only called 2 or 3 times and I've adjusted them all and commented the function itself for anyone looking to change/add it in the future. 
> 
> The old pallet is still in the game and is set to "both" by default, so it should work just fine for backwards compatibility. 
> 
> ## Media
> ![image](https://github.com/space-wizards/space-station-14/assets/1471082/38cdf849-3e05-4f98-957f-65a719c2280d)
> ![image](https://github.com/space-wizards/space-station-14/assets/1471082/56e471e9-b45e-4332-bd55-7220566542ab)
> ![image](https://github.com/space-wizards/space-station-14/assets/1471082/a5e8e651-d301-420a-b2d7-cc4cf07a50af)
> ![image](https://github.com/space-wizards/space-station-14/assets/1471082/fdf2cf4c-fba8-46c9-9a30-7313a2204b5e)
> ![image](https://github.com/space-wizards/space-station-14/assets/1471082/3811edd0-bb32-44cf-b884-e0a9f4bf16fa)
> 
> 
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> ## Breaking changes
> 
> Shouldn't break anything, I've left the old pallets fully in, and updated them to work with the new GetCargoPallets() function just like they used to. Not sure if/where you'd still need them, but better safe than sorry.
> 
> **Changelog**
> :cl:
> - tweak: The trading outpost now has dedicated buy-only and sell-only pallets. No more accidentally selling orders you just bought. Cargonians rejoice!
> 

</details>

2024-04-30 20:51 UTC, DangerRevolution requested changes
this needs to be tested to work on Delta trade station

2024-05-04 15:49 UTC, VMSolidus approved these changes
![image](https://github.com/Simple-Station/Einstein-Engines/assets/16548818/d7c8d22d-0abc-42e4-9196-755563493650)

The C# side of things is fine, and it does also modify the tradepost grid to add these new pallets.

2024-06-14 13:52 UTC, DangerRevolution approved these changes

2024-06-14 13:52 UTC, DangerRevolution commented
Will be merged if tests pass

2024-06-16 15:39 UTC, merged