Mirror: Added cheap sunglasses into ClothesMate
Simple-Station/Einstein-Engines pull request #209
Opened 2024-04-22 09:33 UTC by SimpleStation14

## Mirror of  PR #25479: [Added cheap sunglasses into ClothesMate](https://github.com/space-wizards/space-station-14/pull/25479) from <img src="https://avatars.githubusercontent.com/u/10567778?v=4" alt="space-wizards" width="22"/> [space-wizards](https://github.com/space-wizards)/[space-station-14](https://github.com/space-wizards/space-station-14)

###### `d370f16e04fc12c8fa2b89c41c3fce12225334b4`

PR opened by <img src="https://avatars.githubusercontent.com/u/140359015?v=4" width="16"/><a href="https://github.com/shampunj"> shampunj</a> at 2024-02-22 21:58:13 UTC

---

PR changed 3 files with 15 additions and 7 deletions.

The PR had the following labels:
- No C#
- Status: Needs Review
- Merge Conflict

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 
> 
> 
> ## About the PR
> 
> Added cheap sunglasses that wasnt protect against flashing into ClothesMate
> 
> ## Why / Balance
> 
> To replace removed regular sunglasses in ClothesMate https://github.com/space-wizards/space-station-14/pull/25221
> ## Technical details
> 
> n/a
> ## Media
> 
> 
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> ![Screenshot_53](https://github.com/space-wizards/space-station-14/assets/140359015/7799a6e3-45e5-4b1b-b403-7c8675ec1b3b)
> ![Screenshot_54](https://github.com/space-wizards/space-station-14/assets/140359015/5d48f59f-8b62-4874-bb66-6a7c582ac213)
> 
> 
> ## Breaking changes
> 
> 
> **Changelog**
> 
> 
> 
> - add: Added cheap sunglasses that wasnt protect against flashing into ClothesMate
> 

</details>

2024-04-30 20:59 UTC, DangerRevolution requested changes
needs price changes

2024-05-05 21:09 UTC, VMSolidus approved these changes
Price changes are done, and this is next on the Pre-requisites list for DeltaV PRs

2024-05-05 21:33 UTC, DangerRevolution requested changes

2024-05-05 21:33 UTC, DangerRevolution commented on Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
> +  cost: 7245
okay i don't wanna be *that* guy but this should be 7250 or something 😢

2024-05-05 21:35 UTC, VMSolidus commented on Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
> +  cost: 7245
Infinite money exploit obtained, repeatedly buying and reselling clothesmate stocks for 5 spesos each lmao.

2024-05-05 21:37 UTC, DangerRevolution commented on Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
> +  cost: 7245
buy and sell prices are the same? that's insane.

2024-05-05 21:37 UTC, DangerRevolution commented on Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
> +  cost: 7245
put it back on 7245

2024-05-05 21:38 UTC, VMSolidus commented on Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
> +  cost: 7245
Lol. Yea it's to prevent people from doing cargo exploits.

2024-05-05 21:39 UTC, DangerRevolution approved these changes
There *really* should be different buy / sell prices. So you can buy something for 10K and sell for 0. As an example.

2024-05-05 21:42 UTC, VMSolidus commented
I mean you can, it's just that we can't actually set the sell price of crates directly because it's summed by all the contents of the crates. The system only cares that sell price must be equal to or less than buy price, but we can only set the buy price directly.

2024-05-05 21:52 UTC, merged

2024-05-05 22:05 UTC, AeraAuling commented
> I mean you can, it's just that we can't actually set the sell price of crates directly because it's summed by all the contents of the crates. The system only cares that sell price must be equal to or less than buy price, but we can only set the buy price directly.

i'd suggest asking frontier about stuff like this, they have stuff like the cargo crates that don't adhere to this system by selling for more then you buy them for. dunno how they do it, but they might have worked out a way to set sell prices as well

2024-05-05 22:15 UTC, DEATHB4DEFEAT commented
> they have stuff like the cargo crates that don't adhere to this system by selling for more then you buy them for

That's not good.

2024-05-05 22:16 UTC, VMSolidus commented
> > they have stuff like the cargo crates that don't adhere to this system by selling for more then you buy them for
> 
> That's not good.

For context the crates in question can only be sold at a profit at an entirely different station than the one you bought them at. You get money in exchange for transporting them to another station.