Mirror: Sleep on Stasis Beds
Simple-Station/Einstein-Engines pull request #216
Opened 2024-04-22 09:34 UTC by SimpleStation14

## Mirror of  PR #26129: [Sleep on Stasis Beds](https://github.com/space-wizards/space-station-14/pull/26129) from <img src="https://avatars.githubusercontent.com/u/10567778?v=4" alt="space-wizards" width="22"/> [space-wizards](https://github.com/space-wizards)/[space-station-14](https://github.com/space-wizards/space-station-14)

###### `5912b062503841ad8adc6a4a959f97670063f1fb`

PR opened by <img src="https://avatars.githubusercontent.com/u/58439124?v=4" width="16"/><a href="https://github.com/Plykiya"> Plykiya</a> at 2024-03-15 05:47:26 UTC

---

PR changed 1 files with 5 additions and 0 deletions.

The PR had the following labels:
- No C#

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 
> 
> 
> ## About the PR
> 
> Made stasis beds heal you at the same rate as normal beds and allows you to sleep on it.
> Edit: I have made the healing 100x worse than normal beds.
> 
> ## Why / Balance
> 
> I kinda just wanted to sleep on a stasis bed and was sad I couldn't. I'm open to any arguments for changing the numbers...
> 
> ## Technical details
> 
> .yml component that adds a sleep action
> 
> ## Media
> 
> 
> - [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> **Changelog**
> 
> 
> 
> no changelog cause this feels like it shoulda already been a thing...

</details>

2024-04-30 21:04 UTC, DangerRevolution requested changes
needs testing, does this actually let you sleep?

2024-05-11 02:08 UTC, FoxxoTrystan reviewed
HOW THE HELL JUST "HealOnBuckle" DOES THIS!
Do they?

Anywho its... works?

![image](https://github.com/Simple-Station/Einstein-Engines/assets/45297731/1b598021-5f3b-473d-b4a4-a41c07d66661)

2024-05-12 03:47 UTC, VMSolidus approved these changes

2024-05-13 13:53 UTC, DangerRevolution approved these changes
it works

2024-05-13 13:53 UTC, merged