Mirror: Fix StrippableSystem blunders
Simple-Station/Einstein-Engines pull request #224
Opened 2024-04-22 09:35 UTC by SimpleStation14

## Mirror of  PR #26166: [Fix StrippableSystem blunders](https://github.com/space-wizards/space-station-14/pull/26166) from <img src="https://avatars.githubusercontent.com/u/10567778?v=4" alt="space-wizards" width="22"/> [space-wizards](https://github.com/space-wizards)/[space-station-14](https://github.com/space-wizards/space-station-14)

###### `8ecb78ee5ac879ef0c79e9c35f3d05e72faf72fd`

PR opened by <img src="https://avatars.githubusercontent.com/u/42424291?v=4" width="16"/><a href="https://github.com/Krunklehorn"> Krunklehorn</a> at 2024-03-16 02:33:20 UTC

---

PR changed 2 files with 13 additions and 7 deletions.

The PR had the following labels:

---

<details open="true"><summary><h1>Original Body</h1></summary>

> ## About the PR
> 
> #25994 wasn't airtight. I never thought to test on animals, zombies or dead / crit players.
> 
> This PR fixes the following issues:
> #26144
> #26145
> #26150
> 
> - Zombies and animals couldn't be stripped because I was checking for target hands too early
> - Dead/Crit was instantly stripping because I turned the strip time multiplier into a TimeSpan
> 
> 
> ## Media
> 
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> 
> **Changelog**
> 
> :cl: Krunk
> - fix: Zombies and animals can be stripped once again.
> - fix: Dead or critical mobs can no longer be stripped instantly.
> 

</details>

2024-04-30 21:06 UTC, DangerRevolution requested changes
this needs to be tested with Felinids

2024-07-01 18:40 UTC, VMSolidus approved these changes

2024-07-01 18:52 UTC, VMSolidus commented
Oh for fucks sakes.

2024-07-01 18:58 UTC, VMSolidus commented
I accidentally bungled this in a way that's hard to untangle. So I have just made a new PR where I redid the cherrypicks and did the   merge conflict handling through VSCode rather than github's web UI. In the future, let's not use the web UI for that lol. It's waaay too easy to screw it up. :trollface:

2024-07-01 19:00 UTC, closed without merging