Mirror: Suit slot weapon consistency + visuals
Simple-Station/Einstein-Engines pull request #247
Opened 2024-04-22 09:39 UTC by SimpleStation14

## Mirror of  PR #26152: [Suit slot weapon consistency + visuals](https://github.com/space-wizards/space-station-14/pull/26152) from <img src="https://avatars.githubusercontent.com/u/10567778?v=4" alt="space-wizards" width="22"/> [space-wizards](https://github.com/space-wizards)/[space-station-14](https://github.com/space-wizards/space-station-14)

###### `6c239890c5c63c2e058fe9d7dfddcd36e25ca221`

PR opened by <img src="https://avatars.githubusercontent.com/u/61917534?v=4" width="16"/><a href="https://github.com/Vaaankas"> Vaaankas</a> at 2024-03-15 17:12:35 UTC

---

PR changed 84 files with 166 additions and 0 deletions.

The PR had the following labels:
- No C#
- Changes: Sprites

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 
> 
> 
> ## About the PR
> 
> 
> Changed weapons to be equippable in the suit slot where they weren't for consistency.
> 
> Also copied visuals from the backpack and belt slots where appropriate to the suit slot.
> 
> ## Why / Balance
> 
> 
> It makes it easier to recognize when someone is armed and looks cool with a lot of previously almost unused sprites being used.
> 
> A byproduct of #26116 discussion and feedback.
> 
> ## Technical details
> 
> 
> ## Media
> 
> 
> - [+] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> ![Screenshot_27](https://github.com/space-wizards/space-station-14/assets/61917534/0eec7fea-b005-43a8-b505-c089b36794be)
> ![Screenshot_26](https://github.com/space-wizards/space-station-14/assets/61917534/74b2a277-ab08-4196-a847-202c21e1751e)
> ![Screenshot_25](https://github.com/space-wizards/space-station-14/assets/61917534/f7c6cb37-6e3b-4f83-b465-ef4ba9838d7c)
> 
> 
> ## Breaking changes
> 
> 
> **Changelog**
> 
> :cl: vanx
> - tweak: You can now wear most guns in the suit slot, and see them on yourself!
> 
> 

</details>

2024-04-30 21:24 UTC, DangerRevolution requested changes
needs to be carried over to Delta weapons

2024-05-12 03:33 UTC, VMSolidus commented
> needs to be carried over to Delta weapons

We can make that happen in a separate PR

2024-05-12 04:00 UTC, VMSolidus approved these changes

2024-05-13 13:55 UTC, DangerRevolution approved these changes

2024-05-13 13:55 UTC, merged