Mirror: fix decoy bomb uplink category
Simple-Station/Einstein-Engines pull request #254
Opened 2024-04-22 09:40 UTC by SimpleStation14

## Mirror of  PR #26205: [fix decoy bomb uplink category](https://github.com/space-wizards/space-station-14/pull/26205) from <img src="https://avatars.githubusercontent.com/u/10567778?v=4" alt="space-wizards" width="22"/> [space-wizards](https://github.com/space-wizards)/[space-station-14](https://github.com/space-wizards/space-station-14)

###### `21c527d6d09847a742202613d8aefce62c79b334`

PR opened by <img src="https://avatars.githubusercontent.com/u/57039557?v=4" width="16"/><a href="https://github.com/Ilya246"> Ilya246</a> at 2024-03-17 10:11:15 UTC

---

PR changed 1 files with 10 additions and 10 deletions.

The PR had the following labels:
- No C#

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 
> 
> 
> ## About the PR
> moves the decoy syndicate bomb from explosives category to deception category
> 
> ## Why / Balance
> PR was made before the uplink categories update so the bomb ended up miscategorised
> 
> ## Technical details
> this is a webedit but it should be sufficiently simple to be fine
> 
> ## Media
> 
> not tested
> 
> - [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

</details>

2024-04-30 21:31 UTC, DangerRevolution approved these changes

2024-05-12 04:57 UTC, VMSolidus requested changes

2024-05-12 04:57 UTC, VMSolidus commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +# Disruption
Needs fixing

2024-05-29 00:30 UTC, VMSolidus commented
We're missing a Deception category somewhere it seems. I'll take a look at this again later

2024-07-10 00:03 UTC, VMSolidus approved these changes

2024-07-10 00:03 UTC, merged