Mirror: Bumps LoneOps minimum required players to 20
Simple-Station/Einstein-Engines pull request #263
Opened 2024-04-22 09:41 UTC by SimpleStation14

## Mirror of  PR #26244: [Bumps LoneOps minimum required players to 20](https://github.com/space-wizards/space-station-14/pull/26244) from <img src="https://avatars.githubusercontent.com/u/10567778?v=4" alt="space-wizards" width="22"/> [space-wizards](https://github.com/space-wizards)/[space-station-14](https://github.com/space-wizards/space-station-14)

###### `61e31f4062b568591448ff5be83ba8be851269e9`

PR opened by <img src="https://avatars.githubusercontent.com/u/149967078?v=4" width="16"/><a href="https://github.com/Boaz1111"> Boaz1111</a> at 2024-03-18 20:52:10 UTC

---

PR changed 1 files with 1 additions and 1 deletions.

The PR had the following labels:
- No C#

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 
> 
> 
> ## About the PR
> 
> I bumped LoneOps minimum required players to 20
> ## Why / Balance
> 
> It was at 10, and loneops are extremely dangerous especially if there's no sec.
> ## Technical details
> 
> 
> ## Media
> 
> 
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> ## Breaking changes
> 
> 
> **Changelog**
> 
> 
> 
> :cl: Boaz1111
> - tweak: Lone operatives now require a minimum of 20 players to spawn

</details>

2024-04-30 21:34 UTC, DangerRevolution requested changes
more players should be kept, rest reverted

2024-05-12 04:09 UTC, VMSolidus approved these changes
Yea this is fine, 20 player minimums means a loneop with a china lake isn't going to solo an entire lowpop station.

2024-05-13 13:56 UTC, DangerRevolution submitted a review, later dismissed
this needs to be changed to the weight and start time of Delta

2024-06-20 22:26 UTC, DangerRevolution approved these changes

2024-06-20 22:26 UTC, merged