Mirror: Fix recycled containers deleting items inside them
Simple-Station/Einstein-Engines pull request #267
Opened 2024-04-22 09:42 UTC by SimpleStation14

## Mirror of  PR #26045: [Fix recycled containers deleting items inside them](https://github.com/space-wizards/space-station-14/pull/26045) from <img src="https://avatars.githubusercontent.com/u/10567778?v=4" alt="space-wizards" width="22"/> [space-wizards](https://github.com/space-wizards)/[space-station-14](https://github.com/space-wizards/space-station-14)

###### `d7484ae9f57477a5ec5c575e3077aa94c0564db6`

PR opened by <img src="https://avatars.githubusercontent.com/u/83650252?v=4" width="16"/><a href="https://github.com/SlamBamActionman"> SlamBamActionman</a> at 2024-03-12 16:16:42 UTC

---

PR changed 2 files with 19 additions and 1 deletions.

The PR had the following labels:
- Status: Awaiting Changes

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 
> 
> 
> ## About the PR
> 
> 
> Right now you can delete any item that fits in a survival box by placing it inside of one and then recycling the box in a Recycler/Material Reclaimer. This PR fixes this by dumping out any item inside containers.
> 
> - For Reclaimers,  any recyclable items inside the container get placed on top of the Reclaimer.
> - For Recyclers, any recyclable items inside the container get recursively recycled as well.
> 
> ## Why / Balance
> 
> 
> I doubt it's intended behavior to be able to effectively delete any item that fits in a box. Also ensures a recycled box provides the correct amount of material as its contents also get recycled.
> 
> ## Technical details
> 
> 
> When trying to recycle, once all checks are passed it iterates through the object's containers if it has any and dumps out any items onto the machine doing the recycling.
> 
> ## Media
> 
> ![image](https://github.com/space-wizards/space-station-14/assets/83650252/9e95b099-ab95-449d-b5a1-25b80afda8cd)
> The result of recycling a survival box in a Recycler/Reclaimer.
> 
> - [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> ## Breaking changes
> 
> 
> **Changelog**
> 
> 
> :cl:
> - fix: Recyclers no longer delete items stored inside of recycled entities.
> 

</details>

2024-04-30 21:35 UTC, DangerRevolution requested changes
think this messed with Nyano code, this should also be tested to **NOT** recycle Felinids

2024-05-12 04:14 UTC, VMSolidus approved these changes
Felinids shoved into either machine via duffel bag just get spat out by the machine.

2024-05-12 04:29 UTC, VMSolidus requested changes

2024-05-12 04:29 UTC, VMSolidus commented on Content.Shared/Storage/EntitySystems/SharedStorageSystem.cs
> +using Content.Shared.Materials;
Oh goddamnit it needs Pseudoitem added back in.

2024-07-10 00:35 UTC, VMSolidus approved these changes

2024-07-12 00:43 UTC, DEATHB4DEFEAT approved these changes

2024-07-12 00:43 UTC, merged