Mirror: Sanitize "ig"
Simple-Station/Einstein-Engines pull request #298
Opened 2024-04-22 09:47 UTC by SimpleStation14

## Mirror of  PR #26328: [Sanitize "ig"](https://github.com/space-wizards/space-station-14/pull/26328) from <img src="https://avatars.githubusercontent.com/u/10567778?v=4" alt="space-wizards" width="22"/> [space-wizards](https://github.com/space-wizards)/[space-station-14](https://github.com/space-wizards/space-station-14)

###### `4f816b4b2f74db8da32cd157110df538e50eed1a`

PR opened by <img src="https://avatars.githubusercontent.com/u/77215380?v=4" width="16"/><a href="https://github.com/Doctor-Cpu"> Doctor-Cpu</a> at 2024-03-22 05:20:30 UTC

---

PR changed 2 files with 7 additions and 3 deletions.

The PR had the following labels:
- No C#

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 
> 
> 
> ## About the PR
> 
> "ig" gets replaced with "i guess"
> 
> ## Why / Balance
> 
> Common slang online which I've seen being attempted to be used before.
> 
> ## Technical details
> 
> N/A
> 
> ## Media
> 
> 
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> ## Breaking changes
> 
> N/A
> 
> **Changelog**
> 
> 
> 
> Don't feel like one is needed.

</details>

2024-04-30 21:47 UTC, DangerRevolution requested changes
need to see what 
` chatsan-word-38: chatsan-replacement-38
    chatsan-word-39: chatsan-replacement-etcetera
    chatsan-word-40: chatsan-replacement-etcetera
    chatsan-word-41: chatsan-replacement-41
    chatsan-word-42: chatsan-replacement-42
    chatsan-word-43: chatsan-replacement-43`

is

2024-04-30 21:49 UTC, stellar-novas commented
```
chatsan-word-38 = mf
chatsan-replacement-38 = motherfucker

chatsan-word-39 = etc
chatsan-word-40 = etc.
chatsan-replacement-etcetera = etcetera

chatsan-word-41 = wyd
chatsan-replacement-41 = what are you doing

chatsan-word-42 = ofc
chatsan-replacement-42 = of course

chatsan-word-43 = ig
chatsan-replacement-43 = i guess
```

2024-04-30 21:50 UTC, DangerRevolution commented
> ```
> chatsan-word-38 = mf
> chatsan-replacement-38 = motherfucker
> 
> chatsan-word-39 = etc
> chatsan-word-40 = etc.
> chatsan-replacement-etcetera = etcetera
> 
> chatsan-word-41 = wyd
> chatsan-replacement-41 = what are you doing
> 
> chatsan-word-42 = ofc
> chatsan-replacement-42 = of course
> 
> chatsan-word-43 = ig
> chatsan-replacement-43 = i guess
> ```

saying any of these in-game should just instantly smite you

2024-05-28 23:52 UTC, DangerRevolution approved these changes

2024-05-29 03:42 UTC, VMSolidus approved these changes

2024-05-29 03:42 UTC, merged