start of debranding
Simple-Station/Einstein-Engines pull request #3
Opened 2024-03-17 05:15 UTC by VMSolidus

We have a repository with a surprising amount of things in it that makes the claim that this repository is DeltaV. We need to remove basically everything from this repository that says "This is DeltaV". Since all of that is hiding basically everywhere in the repository, this is going to be a fun cooperative assignment.

2024-03-18 00:09 UTC, VMSolidus commented
I have updated both the title, summary, and objectives of this PR to reflect a more realistic scope.

2024-03-18 02:05 UTC, VMSolidus commented
![image](https://github.com/Simple-Station/Einstein-Engines/assets/16548818/ca97d047-fffd-4137-8a2d-a80466bf119e)
Wew, and now I have tests plus compiler pass. This is nearly as far as I can tell, all of the species code that previously existed spread across DeltaV, Nyanotrasen, and Simplestation14, now placed inside Content.X.Species. Not all of it should stay there indefinitely, but for the sake of organization they're all now in a unified place that's easy to find.

2024-03-24 00:23 UTC, DEATHB4DEFEAT requested changes

2024-03-24 00:23 UTC, DEATHB4DEFEAT commented on Content.Client/Species/Felinids/Systems/PseudoItemSystem.cs
Rename the `Felinids` folder to `Felinid`

2024-03-24 00:23 UTC, DEATHB4DEFEAT commented on Content.Server/Species/Felinids/Components/CoughingUpHairballComponent.cs
Rename the `Felinids` folder to `Felinid`

2024-03-24 00:23 UTC, DEATHB4DEFEAT commented on Content.Server/Species/Spider/Systems/SpiderSystem.cs
I think this is used by things other than Arachne, put it back

2024-04-02 23:46 UTC, VMSolidus commented
I'm closing this as per a notice for our new policy regarding code respacing. As stated on our discord at this link:
https://discord.com/channels/1218698320155906090/1218698321053356059/1224795186689867818

2024-04-02 23:46 UTC, closed without merging