Mirror: Throwing Knives: Syndicate Kit
Simple-Station/Einstein-Engines pull request #310
Opened 2024-04-22 09:49 UTC by SimpleStation14

## Mirror of  PR #26026: [Throwing Knives: Syndicate Kit](https://github.com/space-wizards/space-station-14/pull/26026) from <img src="https://avatars.githubusercontent.com/u/10567778?v=4" alt="space-wizards" width="22"/> [space-wizards](https://github.com/space-wizards)/[space-station-14](https://github.com/space-wizards/space-station-14)

###### `393bcbfc1346589075ad960473685c78bdbf46e5`

PR opened by <img src="https://avatars.githubusercontent.com/u/134914314?v=4" width="16"/><a href="https://github.com/UbaserB"> UbaserB</a> at 2024-03-12 06:57:41 UTC

---

PR changed 13 files with 101 additions and 8 deletions.

The PR had the following labels:
- No C#
- Changes: Sprites

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 
> 
> 
> ## About the PR
> 
> 
> This PR adds throwing knives and a syndicate bundle in the bundle category for 6 TC which comes with 4 throwing knives in a box. Each knife does 10 slash + 15 pierce damage on throw, and 5 flash per hit (10 DPS). This makes it better than a kitchen knife, but worse than a combat knife, which is what security is fitted with.
> 
> ## Why / Balance
> 
> 
> This kit is built for weakening an enemy from a distance (from chasing, etc) while being able to fight back if cornered into a 1v1 CQC fight. Sure, you can kill several people with the kit; hence why it's so expensive, but there are drawbacks. Firstly, once it embeds into a target they are able to pull it out. Secondly, when you are pulling them out of a target, YOU are vulnerable. Thirdly, if you miss your hits the target will probably not die. Good things you have four knives and can stab them to death.. better than punches!
> 
> ## Media
> 
> 
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> **It embeds and kills in 4 throws on an unarmoured target.**
> ![image](https://github.com/space-wizards/space-station-14/assets/134914314/05f4112d-a08c-4bde-9b34-8a5ecde0b270)
> 
> **Item description.**
> ![image](https://github.com/space-wizards/space-station-14/assets/134914314/87704a6e-8501-4f19-a158-bf89d6b4a83e)
> 
> **4 knives.**
> ![image](https://github.com/space-wizards/space-station-14/assets/134914314/44dc4c40-add3-46be-b224-b71e2f14f1e9)
> 
> **Kit on uplink.**
> [IMG NEEDS UPDATING]
> 
> **Changelog**
> 
> :cl: Ubaser
> - add: You can now purchase a set of 4 throwing knives in the uplink as a bundle for 12 TC.

</details>

2024-04-30 21:55 UTC, DangerRevolution requested changes
why does this overwrite observation kit lol

2024-05-01 13:54 UTC, VMSolidus commented
> why does this overwrite observation kit lol

Because that's just the main downside of how mirrors work. Technically things like this also happen while cherrypicking. I'm trying to work things out with Death and Pspsrite so that full Maintainers can actually make edits to the Mirror PRs to fix issues like these. Trial maintainers should be able to make code suggestions to fix issues like this, and then a full maintainer can come in and hit commit on said suggestions.

2024-05-29 02:43 UTC, VMSolidus approved these changes

2024-06-29 22:46 UTC, DangerRevolution approved these changes

2024-06-29 22:46 UTC, merged