Fix Double Trade Station Bug
Simple-Station/Einstein-Engines pull request #351
Opened 2024-05-01 01:21 UTC by VMSolidus

# Description

This fixes a bug introduced inadvertently by https://github.com/Simple-Station/Einstein-Engines/pull/344 by adding a CVar that makes it a choice to be made by our downstreams. Also, welcome to our new CVar standard where they should be included in other systems.

2024-05-01 01:39 UTC, DangerRevolution requested changes

2024-05-01 01:39 UTC, DangerRevolution commented on Content.Server/Cargo/Systems/CargoSystem.CVars.cs
> +        ///     This does NOTHING to the trade station that spawns on the default map.
```suggestion
        ///     This does NOTHING to the trade station that spawns on the default map.
        ///     To change that, in Resources/Prototypes/Entities/Stations/base.yml, comment out the "trade:" section.
```
And a similar comment should be left in trade.yml so it's *obvious* how to have either mode.

2024-05-04 21:40 UTC, DangerRevolution approved these changes

2024-05-12 05:03 UTC, FoxxoTrystan reviewed
👍

2024-05-12 05:21 UTC, Peptide90 commented
Tested with no issues

2024-05-12 05:21 UTC, Peptide90 approved these changes

2024-05-12 05:22 UTC, merged