Mirror: Church Bells
Simple-Station/Einstein-Engines pull request #388
Opened 2024-05-03 15:57 UTC by SimpleStation14

## Mirror of  PR #26030: [Church Bells](https://github.com/space-wizards/space-station-14/pull/26030) from <img src="https://avatars.githubusercontent.com/u/10567778?v=4" alt="space-wizards" width="22"/> [space-wizards](https://github.com/space-wizards)/[space-station-14](https://github.com/space-wizards/space-station-14)

###### `a0cc87c2673bc0930adafe9ab8650700d8ecf2e3`

PR opened by <img src="https://avatars.githubusercontent.com/u/145869023?v=4" width="16"/><a href="https://github.com/SphiraI"> SphiraI</a> at 2024-03-12 08:33:08 UTC

---

PR changed 9 files with 68 additions and 0 deletions.

The PR had the following labels:
- No C#
- Changes: Sprites
- Status: Awaiting Changes

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 
> 
> 
> ## About the PR
> - Adds a church bell to be used with station chapels
> *idea and sprites by Kezu, proto/sounds put together by me.*
> 
> 
> ## Why / Balance
> "if the jani gets their jani light for convenience and rp, the chapel gets a church bell to signal for sermons" -Kezu
> RP purposes, and to give something to chap similar to something like Clown's horn. Would let Chaps use it to get passerby's attention and whatnot.
> 
> 
> ## Media
> ![image](https://github.com/space-wizards/space-station-14/assets/145869023/565ced49-0eb7-4a34-a5e9-da06ec67aa29)
> 
> **_There is a .ogg sound added, but I'm not sure how to make it play nice with git, please someone bwoink me with how_**
> 
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> **Changelog**
> 
> 
> :cl: Sphiral&Kezu
> - add: Added Church Bells! You may hear otherworldly chimes near your local chapel soon...
> 

</details>

2024-05-04 21:52 UTC, DangerRevolution requested changes

2024-05-04 21:52 UTC, DangerRevolution commented on Resources/Prototypes/Entities/Structures/Specific/church-bell.yml
> +    interactDelay: 1
should probably be slower to stop spam

2024-05-04 21:52 UTC, DangerRevolution commented on Resources/Textures/Structures/Specific/church-bell.rsi/church-bell.png
is that a wooden pole? might look weird in a space station, i wanna see this in game first.

2024-05-05 02:15 UTC, DangerRevolution approved these changes
approving

people said this looks okay, and it's not like I could draw a better version lol

2024-05-12 04:27 UTC, VMSolidus approved these changes

2024-05-12 04:27 UTC, merged