Benos
Simple-Station/Einstein-Engines pull request #413
Opened 2024-05-19 12:16 UTC by Kai518

# Description

Alien infestation event from ss13. Also some of the facehugger bugs and missing localizing, shown in video are fixed by the time of publishing this PR. 

---

# TODO

-[] Add vent crawling, when this system will be implemented in future.

---

<details><summary><h1>Media</h1></summary>
<p>

![Example Media Embed](https://drive.google.com/uc?export=download&id=1bRX8p-w7OSSD9QRHwISNcarjIr4O55O9)

</p>
</details>

---

# Changelog

:cl Kai5:
- add: Some of xenomorph larvas were spotted on the stations.

2024-05-19 12:18 UTC, Kai518 commented
https://drive.google.com/uc?export=download&id=1bRX8p-w7OSSD9QRHwISNcarjIr4O55O9 Showcase video link

2024-05-19 12:29 UTC, DangerRevolution requested changes
Very nice surprise PR; I'm assuming you're still working on this so this is all I'll review

2024-05-19 12:35 UTC, DangerRevolution commented
.rsi is the only valid test fail, others are related to Microsoft

2024-05-19 12:55 UTC, Kai518 commented
> .rsi is the only valid test fail, others are related to Microsoft

Can you please say, what is actually wrong with rsi. I am new to contributing...

2024-05-19 14:24 UTC, DangerRevolution commented
> > .rsi is the only valid test fail, others are related to Microsoft
> 
> Can you please say, what is actually wrong with rsi. I am new to contributing...

https://github.com/Simple-Station/Einstein-Engines/actions/runs/9147685738/job/25149458256?pr=413

It's all in here, it doesn't like how some of the licenses are typed in and some of the meta.jsons are missing states I think.

2024-05-19 14:28 UTC, Peptide90 requested changes
null isn’t valid for license and version and yeah missing states.

did you also actually make the sprites for the plasma power display or are they ported from SS13 like the other CM stuff? As you’ll need to reference the commit it’s taken from. RSI edit is good for this.

2024-05-19 14:28 UTC, DangerRevolution commented
> null isn’t valid for license and version and yeah missing states.
> 
> did you also actually make the sprites for the plasma power display or are they ported from SS13 like the other CM stuff? As you’ll need to reference the commit it’s taken from. RSI edit is good for this.

Yuh, I'm also curious as to where these Sprites are from

2024-05-19 14:32 UTC, Kai518 commented
> null isn’t valid for license and version and yeah missing states.
> 
> did you also actually make the sprites for the plasma power display or are they ported from SS13 like the other CM stuff? As you’ll need to reference the commit it’s taken from. RSI edit is good for this.

Background for them I've got from tgstation (license is written in screen-alien.rsi), and paitned numbers on it, cuz I haven't found any way to display actual numbers on status icon

2024-05-19 15:00 UTC, VMSolidus commented
So I'll preface this that we aren't really going to be accepting sprites ported from /tg/station, when far better sprites can be found on Baystation and its downstreams, such as Paradise.

2024-05-19 19:22 UTC, FoxxoTrystan reviewed
This PR lack a ton of documentation and TG Sprite/Gameplay seem, off...
I feel theres better ways to do this in SS14 then just following what SS13 Did.

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Client/Aliens/Systems/AlienSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Client/Aliens/Systems/AlienSystem.cs
> +    private void OnStartup(EntityUid uid, AlienComponent component, ComponentStartup args)
This function is not used at all, is it needed?

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Client/Aliens/Systems/PlasmaVesselSystem.cs
> +/// This handles...
Summary Needed

Also is this... System... used for anything?

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Client/Overlays/ShowInfectedIconsSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Components/AlienAcidComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Components/AlienEggHatchComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Components/QueenEvolutionComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Systems/AlienAcidSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Systems/AlienEggHatchSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Systems/AlienEvolutionSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Systems/AlienInfectedSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Systems/AlienInfectedSystem.cs
> +    private void OnComponentShutdown(EntityUid uid, AlienInfectedComponent component, ComponentShutdown args)
This is just emtpy.

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Systems/AlienQueenSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Systems/AlienSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Systems/FacehuggerSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Systems/InsideAlienLarvaSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Systems/PlasmaVesselSystem.cs
> +/// This handles...
Summary Needed

Again this same system is emtpy, why?

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Systems/PraetorianEvolutionSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Systems/QueenEvolutionSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Systems/ResinSpinnerSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Aliens/Systems/ResinSpinnerSystem.cs
> +    public void CreateStructure(EntityUid uid, ResinSpinnerComponent component, string structurePrototype, bool offset = true)
CreateStructure is in multiple scripts, is that normal?
Because if they all do the same, just... make one script with it and all it upon.

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Chat/Commands/AliensayCommand.cs
> +        public string Command => "aliensay";
This command need .ftl support.

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Chat/Systems/ChatSystem.cs
> +    HiveXeno
OOC Type?
I feel this should be moved and used the same way "Telepathic" does.
Or even hook it.

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Server/Medical/VomitActionSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/AcidMakerComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/AlienComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/AlienEvolutionComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/AlienInfectedComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/AlienJumpComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/AlienQueenComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/AlienRoleComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/AlienStalkComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/FacehuggerComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/InsideAlienLarvaComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/PlasmaTransferComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/PlasmaVesselComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/PraetorianEvolutionComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/ResinSpinnerComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/ShowInfectedIconsComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Components/TailLashComponent.cs
> +/// This is used for...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Systems/AcidMakerSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Systems/AlienJumpSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Systems/SharedAlienEvolutionSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Systems/SharedAlienEvolutionSystem.cs
> +    public override void Initialize()
Emtpy init, okay?

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Systems/SharedAlienQueenSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Systems/SharedAlienStalkSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Systems/SharedFacehuggerSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Systems/SharedPlasmaGainModifierSystem.cs
> +/// This handles...
Summary Needed

Again this system is... emtpy.

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Systems/SharedPlasmaTransferSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Systems/SharedPlasmaVesselSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Systems/SharedPraetorianEvolutionSystem.cs
> +/// This handles...
Summary Needed

Emtpy System again.

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Systems/SharedResinSpinnerSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Aliens/Systems/TailLashSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Chat/ChatChannel.cs
> +        XenoHivemind = 2 << 2,
This should be 16

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Chat/ChatSelectChannel.cs
> +        XenoHivemind = ChatChannel.XenoHivemind,
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Medical/SharedVomitActionSystem.cs
> +/// This handles...
Summary Needed

2024-05-19 19:22 UTC, FoxxoTrystan commented on Content.Shared/Medical/VomitActionComponent.cs
> +/// This is used for...
Summary Needed

2024-06-14 13:50 UTC, DangerRevolution commented
Closed as derelict; reopen if you come back to this :)

2024-06-14 13:50 UTC, closed without merging