More Loadout Items Wave 1
Simple-Station/Einstein-Engines pull request #425
Opened 2024-05-30 00:49 UTC by VMSolidus

# Description
The original release of Loadouts to EE did not have much in the way of actual implementation as far as the item list was concerned. This PR seeks to get a head start at fixing that by implementing a fairly sizeable chunk of new items that can be bought with loadout points.

One important addition is the use of "non-clothing-job-related items", which helps further set this version of Loadouts apart from the /tg/ style of loadouts implemented elsewhere. One of the key strengths of this loadout system is that it's not limited to just replacing a job's clothing selections, but can also add items unrelated to clothing. My given example for this is the new option for Security characters(provided they have sufficient number of hours as a Security Officer) can spend roughly half their loadout points to start with a spare magazine for their handgun. 

Secondly, we also now have an opportunity to place non-nanotrasen corporate items in the game, in such a way that players can tie their characters to other corporations. Ostensibly this is to build up to the idea of "Contractor" characters. I hope that this will help broaden people's horizons. 

# On "Syndie" items
I'd like to take this as an opportunity to kind of push people away from the whole thing of "THATS A SYNDICATE ITEM!!!!" wherever possible. For the most part this is very much NRP behavior that I'd like to discourage. With some notable exceptions, this doesn't mean outright antag items should be obtainable through Loadouts. To that end, items such as Interdyne branded smokes, Cybersun branded clothing, and other items with "In-Universe Company Brands" should be moved away from their identity as strictly antag objects, and instead things characters could reasonably have bought with their paycheck. 

# Technical Changes
I had to make some improvements to the way Loadouts handles species, namely it wasn't previously possible to have an item require any entry from a list of species. I updated it so that SpeciesRequirement takes a list of Species, and will accept any entry from that list. My given example for this is the entries for Nitrogen air tanks, which can only be purchased in loadouts by SlimePersons and Vox(who are not currently playable, but I am accounting for them). Other usage of this is in the Oni-specific Security items. I do hope to use this as an opportunity to introduce more species-specific goods in the future. 

# Media

Outerwear
![image](https://github.com/Simple-Station/Einstein-Engines/assets/16548818/8d0d9286-7758-45f3-aaff-506dddd35da6)

More job-related selections available to some departments
![image](https://github.com/Simple-Station/Einstein-Engines/assets/16548818/7b214593-7111-42d7-966e-2a340c766f61)

More variety of trinkets and items, including instruments!
![image](https://github.com/Simple-Station/Einstein-Engines/assets/16548818/1b7befaf-c94c-4238-b93b-cbdf14e939dd)

# Changelog

:cl: VMSolidus
- add: The catalog of items available via Loadouts has been greatly expanded. Have fun customizing your characters!

2024-05-30 01:09 UTC, DangerRevolution approved these changes

2024-06-03 22:56 UTC, VMSolidus commented
![image](https://github.com/Simple-Station/Einstein-Engines/assets/16548818/7491fc97-d4b0-4fc4-9de5-ddb3d7675442)

I have significantly increased the number of existing categories, as well as moved things around, and added more items to fit said categories. I think for a lot of things, any items listed as "exclusive: true" should probably be discounted if they're a job related item that is replacing something you already start with. Such as for example, the option for Security to start with security webbing instead of a belt(I had to add a FILLED webbing just for this purpose). 

Also fun fact, the "Insulated gloves" that are for assistant only, are actually budget insuls. By popular request, assistants can now gamble loadout points on killing themselves with the budget roulette.

2024-06-16 15:34 UTC, VMSolidus commented
I've added the Sol Common Translator to loadouts, as a somewhat cheap entry for the items tab. This will serve as a way of simply introducing to players that the translator items exist, and gives an easy tie-in with Languages and Loadouts. 
![image](https://github.com/Simple-Station/Einstein-Engines/assets/16548818/a1a7d043-acee-449d-ae0f-84bd658254a2)

2024-07-03 02:22 UTC, VMSolidus commented
How the hell has this not already been merged?

2024-07-03 02:23 UTC, DEATHB4DEFEAT commented
uhhhhhhhhhhhhhhhhh

2024-07-03 02:28 UTC, DEATHB4DEFEAT requested changes

2024-07-03 02:28 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Loadouts/Jobs/engineering.yml
> -
Our eggmos suit... @Pspritechologist

2024-07-03 02:28 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Loadouts/categories.yml
> +  id: Uncategorized
Put this at the top, like the comment says.

2024-07-03 02:28 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Loadouts/uniform.yml
> +  cost: 4 #The legendary black dress
```suggestion
  cost: 4
```

2024-07-05 20:56 UTC, VMSolidus commented
@DEATHB4DEFEAT Done.

2024-07-05 22:53 UTC, Peptide90 approved these changes

2024-07-05 22:53 UTC, merged