Default to Separated UI Layout
Simple-Station/Einstein-Engines pull request #433
Opened 2024-06-03 02:40 UTC by DEATHB4DEFEAT

# Description

<sub>~~Change from Nyano~~</sub>
Uses space a lot better. The old layout still exists if people want it for whatever reason.
I also renamed "Default" to "Overlay", which should stay anyway if the default change is denied.

---

# Changelog

:cl:
- tweak: UI layout now defaults to separated, the old one is still available in settings

2024-06-08 21:33 UTC, DangerRevolution approved these changes

2024-06-16 15:37 UTC, VMSolidus requested changes
Do you mind including screenshots of the two different UIs, so that we can see in the PR the differences visually of what's being changed?

2024-06-16 21:07 UTC, DEATHB4DEFEAT commented
> Do you mind including screenshots of the two different UIs, so that we can see in the PR the differences visually of what's being changed?

Done.

2024-06-16 22:38 UTC, VMSolidus approved these changes
OH. Yea that's a significant improvement.

2024-06-16 22:38 UTC, merged