Misc Resprites!
Simple-Station/Einstein-Engines pull request #435
Opened 2024-06-06 21:47 UTC by FoxxoTrystan

# Description

This PR add a bunch of Misc Repsrites and others fixes that i have missed.

Here is the following list of Changed Sprites:

• Rust Solid/Reinforced Walls
• Stunbaton
• Banners
• Radiation Collector
• Riot Suit
• Bulletproof Vest
• Armor Vest
• Slim Armor Vest
• Fire Extinguisher
• Stock Parts
• Rack
• Screen

# TODO

- [x] Port/Resprites.

---

<details><summary><h1>Media</h1></summary>
<p>

![image](https://github.com/Simple-Station/Einstein-Engines/assets/45297731/3ad4521e-093c-4e3a-a088-6e61e8e66a49)

</p>
</details>

---

# Changelog

:cl:
- tweak: Rust Walls Sprites.
- tweak: Armor, Bulletproof, Riot Suit Resprites.
- tweak: New Banners Sprites.
- tweak: Stunbaton, Fire Extinguisher New Sprites.
- tweak: Rack/WallScreen resprites.
- tweak: Stock Parts new sprites!
- tweak: Radiation Collector has now a new sprite!

2024-06-06 23:42 UTC, DangerRevolution approved these changes

2024-06-07 03:56 UTC, DEATHB4DEFEAT requested changes
Add permalinks to every meta.

2024-06-07 18:37 UTC, FoxxoTrystan commented
> Add permalinks to every meta.

Missing Permalink and a tiny fix to a meta file has been done.

2024-06-11 00:33 UTC, VMSolidus approved these changes
These look great! Thank you Trystan!

2024-06-11 00:34 UTC, merged