Rebase Blood Drinker System, Arachne, Oneirophage
Simple-Station/Einstein-Engines pull request #438
Opened 2024-06-10 16:58 UTC by VMSolidus

# Description
This is a simple rebase of the Blood Drinker System, and its related features that have been commented out and/or omitted due to its lack of rebase. I am NOT substantially updating any of this code at this time, outside of the barest minimum updates needed to make it run in the first place. The reason I am doing this is that I require the Blood Drinker system functional as a per-requisite for future features, and I will update or refactor it when needed. 

Arachne are still pending a Full Rework, but that is beyond the scope of this PR. 

# TODO

- [ ] Make the code functional
- [ ] Port Arachne
- [ ] Uncomment Oneirophages
- [ ] Re-add Oneirophage midround event

# Changelog

:cl: VMSolidus
- add: Arachne have been reimplemented!
- add: Oneirophages are back!

2024-06-10 20:25 UTC, VMSolidus commented
DONE

2024-06-11 01:22 UTC, FoxxoTrystan commented
What about the "normal" spooders?

2024-06-11 01:28 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Mobs/Species/arachne.yml
Now That "Languages" got merged, specie should have a LanguageSpeaker Component.

Or they will go to the fallback as MobBase (if its is the right one)

2024-06-11 01:30 UTC, VMSolidus commented on Resources/Prototypes/Entities/Mobs/Species/arachne.yml
They're using MobBaseHuman right now, so they are defaulted to Galactic Common + Sol Common. I haven't had a chance to really think about what language they should use to be fair.

2024-06-20 22:38 UTC, DangerRevolution requested changes
They need a language to come with; and I also wanted to ask what the plan would be for Arachnids, what direction to take them if Arachnes become the vampires.

2024-06-20 22:38 UTC, DangerRevolution commented on Content.Server/Vampire/BloodSuckerComponent.cs
> +        public bool InjectWhenSucc = false;
Woah; cool possibities here for snake people

2024-06-20 22:38 UTC, DangerRevolution commented on Content.Server/Vampire/Injector/BloodSuckerGlandInjectorComponent.cs
> +    /// Item that gives a bloodsucker injection glands (for poison, usually)
Very cool

2024-06-20 22:47 UTC, VMSolidus commented
> They need a language to come with; and I also wanted to ask what the plan would be for Arachnids, what direction to take them if Arachnes become the vampires.

So longer term, I'm actually going to comprehensively rework the Vampirism mechanic to later go with Arachne. I just needed this system rebased for other purposes, and changed as little as feasibly possible to get it working. 

Arachnids are meant to be parallel to it, it sort of fits in with a longer term goal that server hosts should just be able to toggle on or off any species they want for their server. If that means toggling off Arachnids and turning on Arachne, or vice versa, or having both enabled at the same time, that's on them. We can have defaults set(and the default for EE species is just, "All of them on by default".) 

For now I think I'm going to leave it as Sol Common in keeping with the "Humans & Human Mutants" theme. When I rework them it'll be fine for me to write a language just for Arachne.

2024-06-20 22:52 UTC, DangerRevolution requested changes
I'm actually going to say that Arachne *do* need a language; even if it's the lowest effort thing you can drum up where they just make different variants of "Hisssss"; people are going to want to play Arachne even if you don't see them as finished (AKA it's going to be merged pre-emptively by people) and a language would flesh them out further; while also expanding on the language system. Makes us look cooler.

2024-06-20 22:52 UTC, DangerRevolution commented
> I'm actually going to say that Arachne _do_ need a language; even if it's the lowest effort thing you can drum up where they just make different variants of "Hisssss"; people are going to want to play Arachne even if you don't see them as finished (AKA it's going to be merged pre-emptively by people) and a language would flesh them out further; while also expanding on the language system. Makes us look cooler.

If you don't want to, I'll drum something up tomorrow morning.

2024-06-20 22:53 UTC, VMSolidus commented
> > I'm actually going to say that Arachne _do_ need a language; even if it's the lowest effort thing you can drum up where they just make different variants of "Hisssss"; people are going to want to play Arachne even if you don't see them as finished (AKA it's going to be merged pre-emptively by people) and a language would flesh them out further; while also expanding on the language system. Makes us look cooler.
> 
> If you don't want to, I'll drum something up tomorrow morning.

Alright! I'm not opposed to you doing that, I'd actually really appreciate it if you did.

2024-07-09 07:59 UTC, DangerRevolution commented
Completely forgot to make a language lol, now saw this as it's mirrored to Delta. Will make one in 12 hours...

2024-07-09 09:05 UTC, FoxxoTrystan commented
> Completely forgot to make a language lol, now saw this as it's mirrored to Delta. Will make one in 12 hours...

If mutan they should use Sol Common but also if you do have a good design for a spooder langauge il give it to others spiders, tho if no design idea come in mind , i have one already.

2024-07-09 09:21 UTC, DangerRevolution commented
> > Completely forgot to make a language lol, now saw this as it's mirrored to Delta. Will make one in 12 hours...
> 
> If mutan they should use Sol Common but also if you do have a good design for a spooder langauge il give it to others spiders, tho if no design idea come in mind , i have one already.

honestly idm; languages can always be re-visited with lore, whatever works

2024-08-05 18:15 UTC, DangerRevolution approved these changes

2024-08-06 04:52 UTC, OldDanceJacket approved these changes

2024-08-06 04:52 UTC, merged