Make Space Frictionless (#46)
Simple-Station/Einstein-Engines pull request #464
Opened 2024-06-16 14:59 UTC by VMSolidus

# Description

This ports Parkstation Rebase PR46, Make Space Frictionless. This PR is something I consider a key feature adjacent to Space Wind Rework and its accompanying updates, and is an essential part of the space station experience. In practice this weirdly enough makes being launched into space a bit easier to survive, since instead of needing to throw potentially hundreds of items, you can simply throw enough items to get started flying in the direction of the station, and will eventually float back to the station. 

# Changelog

:cl: VMSolidus
- tweak: Space is now frictionless!

2024-06-16 21:39 UTC, DEATHB4DEFEAT requested changes

2024-06-16 21:39 UTC, DEATHB4DEFEAT commented on Content.Shared/Movement/Components/MovementSpeedModifierComponent.cs
> +        public const float DefaultWeightlessFrictionNoInput = 0f; // Parkstation-FrictionlessSpace
```suggestion
        public const float DefaultWeightlessFrictionNoInput = 0f;
```

2024-06-16 21:39 UTC, DEATHB4DEFEAT commented on Content.Shared/SimpleStation14/Physics/FrictionRemoverSystem.cs
Respace this

2024-06-16 21:43 UTC, DEATHB4DEFEAT reviewed
I changed the PR description.
- Don't add your name to the CL unless there are multiple people in there, or you want to be seen as something other than your GitHub username in-game
- When porting something, add the original author to the CL name
- Add the original or new PR media to the description
- Link the PR or a permalink
- Put sentences on newlines and paragraphs on double newlines

2024-06-16 22:54 UTC, DEATHB4DEFEAT approved these changes

2024-06-17 07:58 UTC, DangerRevolution approved these changes

2024-06-17 07:58 UTC, merged