Restore old event rates
Simple-Station/Einstein-Engines pull request #509
Opened 2024-07-04 02:07 UTC by Mnemotechnician

# Description
This restores the old basic/survival event rates to how they were before before #486 (however, it keeps the CVars created in it).

- 5-25 minutes for basic instead of 15-35
- 4-12 minutes for survival instead of 15-45

---

# Why
The PR made it so that survival rounds actually have less events than extended - that is considering that survival rounds are supposed to be troublesome and filled with events while extended ones are supposed to be a chill alternative.

Other forks don't bother with editing CVars every 5 minutes, so this "opportunity to configure their experience" was never addressed. Based on the feedback I've received from other players, the change was rather negative.

From my personal experience, survival rounds became an extended extended, where during a 2-hour shift you can get a grand total of one power outage and two mice infestations, and nothing else at all.

---

# Changelog

:cl:
- tweak: Events should now occur as frequently as before. Note: server owner can configure the frequency on their server manually.

2024-07-04 02:08 UTC, VMSolidus approved these changes

2024-07-04 02:41 UTC, DEATHB4DEFEAT requested changes
I accidentally swapped the initial values in my PR, but survival is supposed to get way more events than extended over the shift, just change its' modifier CVars instead if it doesn't and correct the swap.

2024-07-04 02:52 UTC, Mnemotechnician commented
The issue is that even if we swap the values, events will still be extremely rare compared to any other fork.

2024-07-05 15:22 UTC, Mnemotechnician commented
I am an active player and I have never heard anyone complain about how there's too many events, ever. However, I did hear others complain that even with the old event rates there were way too little actually dangerous events.

2024-07-05 19:07 UTC, DangerRevolution approved these changes
I personally believe that it's better to have events be more frequent; and have forks tune it down rather than vice versa. I also believe it lets EE show off some of it's more mechanical changes.

2024-07-05 21:03 UTC, VMSolidus commented
So since our default is MRP, it really wasn't a terrific idea to have the default for other servers to use be that of HRP style event timers. People had a bit of an odd disconnect with it, expecting the event timers to be relatively consistent, but then had servers with extremely uneventful rounds be the default.

Really, long term I still want to do a Director System, but that'll be on hold until after we get our hands on the Antag Refactor(Having ALL antags being a function you can call is incredibly nice for that.)

2024-07-05 21:03 UTC, merged