Despecialize Jobs And Events
Simple-Station/Einstein-Engines pull request #515
Opened 2024-07-05 23:14 UTC by VMSolidus

# Description

A common complaint I have gotten from server hosts looking to setup servers on our codebase is that we have all of these leftover job and event modifications from DeltaV, which serve a purpose not present in our repository. I've taken the liberty of cleaning up and uncommenting a majority of events that DeltaV commented out for one reason or another at various times, and have also removed every single instance of pre-existing job playtime and whitelist requirements, as well as the antag factors. These especially are a point of contention for anyone wishing to setup a new server, because it's quite literally impossible for anyone on a brand new server that has only been existing for 20 minutes so far, to have the ~200 hours of playtime + whitelist that DeltaV would have required them to have to play Captain. 

This update in turn leaves the onus on server hosts to set their own desired whitelist requirements as needed, rather than enforce DeltaV's unusually strict requirements that we inherited. Furthermore, the sheer number of commented out events from DeltaV was giving server hosts the false impression that we were lacking content compared to Wizden, when truthfully, our predecessor disabled a majority of the game's content, and it was simply never re-enabled. The only events I left commented out are the Terminator(which in our codebase has been superceded by the much better Paradox Anomaly), and the GlimmerWispSpawn, which remains commented due to Glimmer Wisps not yet being rebased.

2024-07-05 23:52 UTC, DangerRevolution requested changes

2024-07-05 23:52 UTC, DangerRevolution commented on Resources/Prototypes/GameRules/events.yml
> -#  parent: BaseGameRule # DeltaV - this shit is busted most of the time
Very bad; this shit is indeed busted, remember when it caused a CTD when getting gibbed?

2024-07-05 23:52 UTC, DangerRevolution commented on Resources/Prototypes/GameRules/events.yml
> -    minimumPlayers: 10 #Enough to hopefully have at least one engineering guy
Not sure this is necessary

2024-07-05 23:52 UTC, DangerRevolution commented on Resources/Prototypes/GameRules/events.yml
> -    duration: null #ending is handled by MeteorSwarmRule
There's a good reason for this comment

2024-07-05 23:52 UTC, DangerRevolution commented on Resources/Prototypes/GameRules/events.yml
> -# - type: entity # DeltaV - Removes the random sentience.
This weight needs to be dropped to 1 or something; sentient vending machines are 0 RP.

2024-07-05 23:52 UTC, DangerRevolution commented on Resources/Prototypes/GameRules/events.yml
> -#- type: entity # DeltaV - Why does this exist??
This is mid. Probably should stay removed. But :shrug:

2024-07-05 23:52 UTC, DangerRevolution commented on Resources/Prototypes/Nyanotrasen/Roles/Jobs/Epistemics/forensicmantis.yml
> -  antagAdvantage: 5 # DeltaV - From 4 to 5
Why?

2024-07-05 23:52 UTC, DangerRevolution commented on Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
> -  antagAdvantage: 3 # DeltaV - Reduced TC: External Access + Free hardsuit and weapons
Why?

2024-07-05 23:52 UTC, DangerRevolution commented on Resources/Prototypes/Roles/Jobs/Civilian/service_worker.yml
> -  antagAdvantage: 1 # DeltaV - Reduced TC: Accesses
Why?

2024-07-05 23:52 UTC, DangerRevolution commented on Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
> -  # I mean they'll give themselves the rest of the access levels *anyways*.
Bringing back HoP AA needs to be in a different PR.

2024-07-05 23:52 UTC, DangerRevolution commented on Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
> -  antagAdvantage: 2 # DeltaV - Reduced TC: External Access
Why?

2024-07-05 23:53 UTC, DangerRevolution commented
HoP AA and TC Disadvantage removal needs to have it's own PR's if intended.

2024-07-06 09:23 UTC, DangerRevolution requested changes

2024-07-06 09:23 UTC, DangerRevolution commented on Resources/Prototypes/GameRules/events.yml
> +    weight: 10
Just going to say this again; this is an insanely 0RP event, vending machines talking isn't as fun as one imagined an having this take up and event slot is BAD.

This needs to have lower weight.
```suggestion
    weight: 1
```

2024-07-06 09:23 UTC, DangerRevolution commented on Resources/Prototypes/GameRules/events.yml
> +    weight: 5
```suggestion
    weight: 0.5
```
Same as before, an immovable rod is 0 RP and shouldn't be taking up an event slot unless there's a good roll for it

2024-07-10 00:40 UTC, VMSolidus commented
Yea, that's all good. I pretty wholeheartedly agree with you that RandomSentience & ImmovableRod should be *extremely rare*. Having that ultra low 0.5 weight for both is fine.

2024-07-10 00:47 UTC, DEATHB4DEFEAT approved these changes

2024-07-11 17:28 UTC, DangerRevolution commented
Will review tonight unless someone beats me to it

2024-07-12 19:46 UTC, DangerRevolution requested changes

2024-07-12 19:46 UTC, DangerRevolution commented on Resources/Prototypes/GameRules/events.yml
> +    weight: 10
Why does this change the comment and the value?

2024-07-12 19:46 UTC, DangerRevolution commented on Resources/Prototypes/GameRules/events.yml
> -    minStartDelay: 0 #let them know immediately
this comment has a reason for being there

2024-07-12 19:46 UTC, DangerRevolution commented on Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/martialartist.yml
> -        coefficients: # These only apply to unarmed
This comment has a reason to be here...

2024-07-12 19:46 UTC, DangerRevolution commented on Resources/Prototypes/Roles/Jobs/Civilian/musician.yml
> -  - Maintenance # TODO Remove maint access for all gimmick jobs once access work is completed
Why are you removing a TODO?

2024-07-12 19:46 UTC, DangerRevolution commented on Resources/Prototypes/Roles/Jobs/Science/research_director.yml
> -    - type: BibleUser # Nyano - Lets them heal with bibles
This comment should stay; just remove the Nyano

2024-07-12 19:46 UTC, DangerRevolution commented on Resources/Prototypes/Roles/Jobs/Wildcards/boxer.yml
> -        coefficients: # These only apply to unarmed
This comment should be here...

2024-08-21 05:55 UTC, closed without merging