The Lightning-factor
Simple-Station/Einstein-Engines pull request #543
Opened 2024-07-12 15:16 UTC by WarMechanic

# Description

So, the lightning system in the current back-end is actually a little bit smelly. Different levels of charge are determined by prototypes, and lightning targeting is hard fixated on ground rods. You can technically generate infinite power with a fork, a microwave, and a tesla coil, as tesla coils generate flat amounts of charge.

This PR aims to improve the lightning system by first grounding it in reality. Lightning has an established charge that is absorbed by entities as it bounces. To accomplish this, lightning now pre-calculates a path before executing any effects, as well as implementing lightning forking behaviours. Lightning has been made more unpredictable by swapping targeting priorities for probability weightings. If you have live sparks near machinery, you are probably doing something wrong.

This PR isn't done yet, I have yet to adjust the effects based on charge although the concept is implemented. Everything should eventually be overrideable with code.

---

# TODO

Must-have
- [ ] (In-progress) Rework the lightning system so behaviour may be configured in-code rather than in-prototype. Must be VM approved if Noospheric Chain-Lightning has even a slim chance of existing.
- - [ ] Function parameters should be able to parse functions for dynamic behaviour.
- [X] Adjust lightning targeting to use probability weightings, rather than a hard targeting priority.
- - [ ] Adjust LightningTarget on prototypes to use new probability weightings.
- [X] Implements forking lightning.
- [X] Implements the concept of lightning charge.
- - [ ] Allow tesla coils to generate power based on incoming charge, multiplied by some efficiency multiplier.
- [ ] Remove the electrified component from lightning prototypes, and use events to determine electrocute effects
- [ ] Separate exploding behaviours from LightningTarget and have it trigger an explosive component instead (or something else?)

Nice
- [X] Lightning can now be configured to disable looping (lightning chaining between two targets)

The future
- [ ] Translate lightning charge to overvolt behaviours in a future overvoltage system
- [ ] Find a connection between this lightning refactor and my other EMP overhaul

---

<details><summary><h1>Media</h1></summary>
<p>

![Example Media Embed](https://example.com/thisimageisntreal.png)

</p>
</details>

---

# Changelog

:cl:
- tweak: Revamped lightning to be craazy!

2024-07-15 17:16 UTC, WarMechanic commented
id like to say that this PR is relatively stable, ive run out of time to work on it so i can look at any reviews after im done with my trip :)

2024-07-21 07:01 UTC, DangerRevolution approved these changes

2024-08-22 21:26 UTC, VMSolidus approved these changes

2024-09-01 23:24 UTC, DEATHB4DEFEAT requested changes

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Electrocution/ElectrocutionSystem.cs
> +        im pretty sure this was removed in a cherry-pick, but id like to keep it around for future overvoltage stuff
```suggestion
        I'm pretty sure this was removed in a cherry-pick, but I'd like to keep it around for future overvoltage stuff
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Electrocution/ElectrocutionSystem.cs
> +        const float LogGrowth = 0.00001f; // Adjusts the growth speed of the curve
These should be arguments on the function

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/Components/LightningTargetComponent.cs
> +    /// The probability weighting of being stuck by lightning, compared against other nearby lightning targets.
```suggestion
    /// The probability weighting of being struck by lightning, compared against other nearby lightning targets.
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/Components/LightningTargetComponent.cs
>      /// </summary>
```suggestion
    /// </summary>
    /// <remarks>For the love of god, do not make this number negative.</remarks>
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +    // a priority queue is required to iterate through Arcs of various depth
```suggestion
    // A priority queue is required to iterate through Arcs of various depth
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +    private PriorityQueue<LightningArc, int> _lightningQueue = new PriorityQueue<LightningArc, int>();
Cool, didn't know this type existed
```suggestion
    private PriorityQueue<LightningArc, int> _lightningQueue = new();
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +    // don't worry, the data gets deleted afterwards
```suggestion
    // A dictionary allows insertion/removal of new lightning bolt data "infinitely" without throwing errors
    // Don't worry, the data gets deleted afterwards
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +    private int NextId() { return _lightningId++; }
```suggestion
    private int NextId() => _lightningId++;
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +        string lightningPrototype = "Lightning",
```suggestion
        ProtoId<EntityPrototype> lightningPrototype = "Lightning",
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +    public void ShootRandomLightnings(EntityUid user, float lightningRadius, int lightningCount, float lightningChargePer, EntityCoordinates? queryPosition = null, bool lightningStacking = true,
```suggestion
    public void ShootRandomLightnings(
        EntityUid user,
        float lightningRadius,
        int lightningCount,
        float lightningChargePer,
        EntityCoordinates? queryPosition = null,
        bool lightningStacking = true,
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +    public void ShootRandomLightnings(EntityUid user, float lightningRadius, int lightningCount, LightningContext context, EntityCoordinates? queryPosition = null, bool lightningStacking = true,
```suggestion
    public void ShootRandomLightnings(
        EntityUid user,
        float lightningRadius,
        int lightningCount,
        LightningContext context,
        EntityCoordinates? queryPosition = null,
        bool lightningStacking = true,
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +        // default the query location to the user's position
```suggestion
        // Default the query location to the user's position
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +        // remove the user to prevent lightning striking self
```suggestion
        // Remove the user to prevent lightning striking self
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +        // get the context and check to see if there are any arcs remaining
```suggestion
        // Get the context and check to see if there are any arcs remaining
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +        // add this arc to the pool of arcs
```suggestion
        // Add this arc to the pool of arcs
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +        // send an event to the staged target to be influenced by resistance
```suggestion
        // Send an event to the staged target to be influenced by resistance
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +        // depending on ArcStacking, remove previously visited entities from the targeting list
```suggestion
        // Depending on ArcStacking, remove previously visited entities from the targeting list
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +            // remove the user regardless to prevent lightning striking self
```suggestion
            // Remove the user regardless to prevent lightning striking self
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +        // do the bounce
```suggestion
        // Do the bounce
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +        // update the context and select the next lightning arc
```suggestion
        // Update the context and select the next lightning arc
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +            // use up charge from the total pool
```suggestion
            // Use up charge from the total pool
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +            // zap
```suggestion
            // Zap
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +            // send an event to the target to be affected by lightning, also inherit information
```suggestion
            // Send an event to the target to be affected by lightning, also inherit information
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningSystem.cs
> +}
```suggestion
}

```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Lightning/LightningTargetSystem.cs
> +            // don't delete the target because it looks jarring, the explosion destroys most things anyhow
```suggestion
            // Don't delete the target because it looks jarring, the explosion destroys most things anyhow
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Kitchen/EntitySystems/MicrowaveSystem.cs
> +                _lightning.ShootRandomLightnings(ent, 1.0f, 2, 5000f,
```suggestion
                _lightning.ShootRandomLightnings(
                    ent,
                    1.0f,
                    2,
                    5000f,
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Anomaly/Effects/ElectricityAnomalySystem.cs
> +            maxArcs: 3
```suggestion
        _lightning.ShootRandomLightnings(anomaly, range, anomaly.Comp.MaxBoltCount * 3, 100000f, maxArcs: 3
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Psionics/Glimmer/GlimmerReactiveSystem.cs
> +            _lightning.ShootRandomLightnings(ent, 10f, 2, 50000f,
```suggestion
            _lightning.ShootRandomLightnings(
                ent,
                10f,
                2,
                50000f,
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Server/Tesla/Components/LightningArcShooterComponent.cs
> +    /// Increasing this value can lead to increasingly unpredictable ranges
```suggestion
    /// Increasing this value can lead to increasingly unpredictable ranges
    /// </summary>
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Shared/Lightning/SharedLightningSystem.cs
> +    public virtual void ShootLightning(EntityUid user, EntityUid target, float totalCharge,
```suggestion
    public virtual void ShootLightning(
        EntityUid user,
        EntityUid target,
        float totalCharge,
```

2024-09-01 23:24 UTC, DEATHB4DEFEAT commented on Content.Shared/Lightning/SharedLightningSystem.cs
> +    public virtual void ShootRandomLightnings(EntityUid user, float lightningRadius, int lightningCount, float lightningChargePer, EntityCoordinates? queryPosition = null, bool lightningStacking = tr
```suggestion
    public virtual void ShootRandomLightnings(
        EntityUid user,
        float lightningRadius,
        int lightningCount,
        float lightningChargePer,
        EntityCoordinates? queryPosition = null,
        bool lightningStacking = true,
```

2024-09-17 19:19 UTC, FoxxoTrystan commented
Any updates on this PR?

2024-10-14 06:45 UTC, FoxxoTrystan commented
Closing this PR: Derelict

2024-10-14 06:45 UTC, closed without merging