random announcer fixes
Simple-Station/Einstein-Engines pull request #557
Opened 2024-07-17 07:23 UTC by DEATHB4DEFEAT

# Description

In theory the test works, too tired to want to figure it out right now.

---

# TODO

- [x] XMLDocs instead of random comments
- [x] Announcer audio test
	- [ ] Fix the resource error
- [x] Remove random extra announcement files
- [ ] Fix test errors
- [ ] Confirm the random random announcer bug Solidus has
- [ ] Add alert announcements to every announcer

---

# Changelog

:cl:
- add: Added fun :D
- tweak: Tweaked fun
- fix: Fixed fun!
- remove: Removed fun :(

2024-07-17 07:28 UTC, DEATHB4DEFEAT commented
![image](https://github.com/user-attachments/assets/e65cc604-22f0-41ba-a2a1-168ca30f9650)

2024-07-21 03:25 UTC, VMSolidus approved these changes
Das a lot of file deletions lol.
But we DID pull the same audio library twice lmao.

2024-07-21 06:53 UTC, DangerRevolution requested changes

2024-07-21 06:53 UTC, DangerRevolution commented on Content.IntegrationTests/Tests/Announcers/AnnouncerAudioTest.cs
> +///     Checks if every station event wanting the announcerSystem to send audios has a sound file
```suggestion
///     Checks if every station event using the announcerSystem has a valid audio file associated with it.
```

Call me stupid but this took me a couple of re-reads to understand, just slightly iffy wording.

2024-07-26 19:29 UTC, OldDanceJacket approved these changes

2024-07-26 19:29 UTC, merged