Soft-Refactor Geiger Counters
Simple-Station/Einstein-Engines pull request #615
Opened 2024-07-30 23:16 UTC by VMSolidus

# Description

This refactors Geiger Counters so that their behavior of "Only making sound to a person holding them" is no longer hardcoded. The GeigerCounterComponent now can define how loud it ticks, how far away people can hear the ticks, and whether it plays only for the person holding it or for anyone nearby. This PR partially fulfills one of the "Nice To Have" features requested for https://github.com/Simple-Station/Einstein-Engines/pull/341 by making it possible to create stationary radiation alarm objects. It also serves as a substantial quality of life improvement for Engineering and Science crew, since it's now possible to place an active Geiger counter in the artifact lab, and then be able to audibly hear if the lab becomes radioactive due to an artifact. 

<details><summary><h1>Media</h1></summary>
<p>

https://github.com/user-attachments/assets/74122135-7345-4995-bb0e-d1216e1d53b6

</p>
</details>

# Changelog

:cl:
- add: Geiger Counters other than ones installed in Hardsuits now generate an audible sound when active and exposed to radiation.

2024-07-31 03:28 UTC, VMSolidus commented
https://github.com/user-attachments/assets/050d001e-ff3d-4dcc-ad5d-fb8f318867dc

And now for Wall Mounted Geiger Counters!

2024-08-01 06:28 UTC, DangerRevolution requested changes

2024-08-01 06:28 UTC, DangerRevolution commented on Content.Shared/Radiation/Components/GeigerComponent.cs
> +    public float VolumeParams = -4f;
Rename all these components to say Parameter

2024-08-04 00:09 UTC, DangerRevolution approved these changes

2024-08-04 00:51 UTC, DEATHB4DEFEAT requested changes

2024-08-04 00:51 UTC, DEATHB4DEFEAT commented on Content.Server/Radiation/Systems/GeigerSystem.cs
> +                                     .WithMaxDistance(component.MaxDistanceParameters);
```suggestion
            var param = sounds.Params.WithLoop(true)
	            .WithVolume(component.VolumeParameters)
	            .WithRolloffFactor(component.RolloffFactorParameters)
	            .WithMaxDistance(component.MaxDistanceParameters);
```

2024-08-04 00:51 UTC, DEATHB4DEFEAT commented on Content.Server/Radiation/Systems/GeigerSystem.cs
> +            component.Stream = _audio.PlayEntity(sound, Filter.Pvs(uid), uid, true, param)?.Entity;
```suggestion

            component.Stream = _audio.PlayEntity(sound, Filter.Pvs(uid), uid, true, param)?.Entity;
```

2024-08-04 00:51 UTC, DEATHB4DEFEAT commented on Content.Shared/Radiation/Components/GeigerComponent.cs
> +    public float MaxDistanceParameters = 10f;
AudioParams are serializable, use that instead.
```suggestion
    public float AudioVolume = -4f;

    /// <summary>
    ///     Controls how quickly the sound gets quieter as a player moves away from the geiger counter.
    /// </summary>
    [DataField]
    public float AudioRolloffFactor = 4f;

    /// <summary>
    ///     Controls the maximum distance that players can hear geiger counter ticks.
    /// </summary>
    [DataField]
    public float AudioMaxDistance = 10f;
```

2024-08-04 16:49 UTC, VMSolidus commented
@DEATHB4DEFEAT swapped it out for its own component set AudioParameters.

2024-08-09 11:13 UTC, Peptide90 approved these changes

2024-08-09 11:13 UTC, merged