Port Morale System (DO NOT MERGE)
Simple-Station/Einstein-Engines pull request #620
Opened 2024-07-31 18:34 UTC by VMSolidus

# Description

I apparently got blackout drunk last night, and for reasons now known only to God, asked White Dream for permission to port their Morale System. They graciously provided us permission to port it. 

![morale code permission](https://github.com/user-attachments/assets/c3d089fa-3e0f-4402-8757-c47e911c3554)

I'm setting this to DO NOT MERGE because I actually genuinely don't know what this system does yet, and the code is likely going to require significant cleanup to meet our repository standards.

# TODO

- [ ] Find out what this system does, and why Drunk Solidus asked White Dream for permission to port it.
- [ ] Cleanup the code so that it suits our repo standards.
- [ ] Move it out of /White namespace.

# Changelog

:cl:
- add: Morale System?

2024-08-03 02:54 UTC, VMSolidus commented
ALRIGHT, FINISHED AND READY FOR REVIEW. LET'S GO.

2024-08-03 03:05 UTC, VMSolidus commented
All tests passed first try, holy shit.

2024-08-03 03:48 UTC, VMSolidus commented
Mood System now not only lives in Shared, but it also now has Contest System entries.

![image](https://github.com/user-attachments/assets/9f1f4385-6dc7-47c2-a149-355526e6e94a)

2024-08-04 14:31 UTC, DangerRevolution requested changes

2024-08-04 14:31 UTC, DangerRevolution commented on Resources/Locale/en-US/mood/mood-alerts.ftl
> +alerts-mood-meh-name = Нехорошо
```suggestion
alerts-mood-meh-name = Mediocre
```
Sigma kept the Russian name in......

2024-08-04 14:31 UTC, DangerRevolution commented on Resources/Locale/en-US/mood/mood-alerts.ftl
> +alerts-mood-meh-desc = The world is full of threats and pain, and my hopes are slowly dying.
```suggestion
alerts-mood-meh-desc = The world is full of dangers and pain, and my hopes are slowly dying.
```
Not sure, this sentence doesn't translate well into English

2024-08-04 14:31 UTC, DangerRevolution commented on Resources/Locale/en-US/mood/mood-alerts.ftl
> +alerts-mood-exceptional-desc = I feel strong and hopeful for better days, despite the threats that lurk around me.
```suggestion
alerts-mood-exceptional-desc = Strength and hope fills me, despite the threats that lurk around me.
```

2024-08-04 14:31 UTC, DangerRevolution commented on Resources/Locale/ru-RU/mood/mood.ftl
remove before merge

2024-08-04 14:31 UTC, DangerRevolution commented on Resources/Locale/ru-RU/mood/mood-alerts.ftl
remove before merge

2024-08-04 14:32 UTC, DangerRevolution commented on Resources/Textures/Shaders/White/saturationscale.swsl
base game folder pls

2024-08-04 16:38 UTC, VMSolidus commented
I'm going to temporarily mark this as draft, due to technical issues I was forced to revert back to the last working version of this PR, since migrating it to Shared broke the system. I still desire ContestSystem integrations, which does mean a Shared migration, but for now I can focus on other parts of Refactoring Morale until we get a better solution.

2024-08-06 08:01 UTC, DangerRevolution submitted a review, later dismissed

2024-08-09 17:43 UTC, angelofallars commented
> Petting an animal gives them the petting related buff rather than the humanoid.

Fixed with https://github.com/VMSolidus/Einstein-Engines/pull/3

2024-08-09 17:44 UTC, DangerRevolution submitted a review, later dismissed

2024-08-09 21:32 UTC, angelofallars reviewed
- Adding/removing moodlets should not require raising an event. It should be with `AddMoodlet` and `RemoveMoodlet` methods.
- `generic_postiveEffects.yml` -> `generic_positiveEffects.yml`
- In my local testing, the client did not have the `NetMoodComponent` component.
- The event definitions should probably be placed in `MoodSystem.cs`, the same place where they are raised to be consistent with other systems I've seen.

- The moodlet numbers don't seem that impactful. A character that is both starving and thirsty will have 36 mood, which is not enough to trigger a change in movement speed. A blanket doubling the mood change of all need moodlets and all other moodlets whose change is less than 10 would probably be a step in the right direction. 
  - Your speed only slows down when your mood is Terrible or less (20/100) but I think it should start at 40/100.

2024-08-10 20:00 UTC, VMSolidus commented
> * Adding/removing moodlets should not require raising an event. It should be with `AddMoodlet` and `RemoveMoodlet` methods.
> 
>     * `generic_postiveEffects.yml` -> `generic_positiveEffects.yml`
> 
>     * In my local testing, the client did not have the `NetMoodComponent` component.
> 
>     * The event definitions should probably be placed in `MoodSystem.cs`, the same place where they are raised to be consistent with other systems I've seen.
> 
>     * The moodlet numbers don't seem that impactful. A character that is both starving and thirsty will have 36 mood, which is not enough to trigger a change in movement speed. A blanket doubling the mood change of all need moodlets and all other moodlets whose change is less than 10 would probably be a step in the right direction.
>       
>       * Your speed only slows down when your mood is Terrible or less (20/100) but I think it should start at 40/100.

Actually It didn't occur to me that the growth starts at 20 or less, I actually wrote the math assuming it started at <50!!!
Because I made it linearly decrease towards -25% below 50, and geometric curve towards +15% above 50

2024-08-10 20:16 UTC, VMSolidus commented
I've changed the thresholds for speed up and speed down to 40 & 60, so that speed modification will occur more readily.

2024-08-10 20:30 UTC, VMSolidus commented
![image](https://github.com/user-attachments/assets/c0873640-b261-4f97-8fee-f07990e5326d)

The fuck? Oh, pointless test.

2024-08-10 20:54 UTC, VMSolidus commented
> ![image](https://private-user-images.githubusercontent.com/16548818/356836915-c0873640-b261-4f97-8fee-f07990e5326d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMjI5MDcsIm5iZiI6MTcyMzMyMjYwNywicGF0aCI6Ii8xNjU0ODgxOC8zNTY4MzY5MTUtYzA4NzM2NDAtYjI2MS00Zjk3LThmZWUtZjA3OTkwZTUzMjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDIwNDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYTZiNTJiYzVhODdjMTY0MWIyMTg4OTg4NmUzMDE0ODc3ZDNkNGM3NzI5YzczYTk3NmZhMTMxNzg2NTUxZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hEn9grVWklOl-WdP2iRakfF0xqNGmK77T9POyS0P654)
> 
> The fuck? Oh, pointless test.

https://github.com/user-attachments/assets/b62f42ea-4e84-4ee9-a96d-4a7089e9fc91

For my own sanity I went and fact checked the test to make sure it's actually a nothingburger. I was right, there's literally no issue with having Mood modifying movement speed interfering with the slipping system. The test actually did have a pointless Assert.

2024-08-10 21:03 UTC, angelofallars reviewed
LGTM. Because two negative moodlets can now trigger a speed change, I feel like this is ready to playtest. Then we can work on refactoring, more moodlets, and more traits.

2024-08-10 21:16 UTC, DangerRevolution approved these changes

2024-08-16 08:03 UTC, DEATHB4DEFEAT requested changes

2024-08-16 08:03 UTC, DEATHB4DEFEAT commented on Content.Server/Mood/MoodSystem.cs
> +    //   Recalculate the mood level of an entity by summing up all moodlets.
```suggestion
    //      Recalculate the mood level of an entity by summing up all moodlets.
```

2024-08-16 08:03 UTC, DEATHB4DEFEAT commented on Content.Server/Mood/MoodSystem.cs
> +        if (ev.Cancelled)
```suggestion

        if (ev.Cancelled)
```

2024-08-16 08:03 UTC, DEATHB4DEFEAT commented on Content.Server/Mood/MoodSystem.cs
> +    #region HealthStatusCheck
```suggestion
```

2024-08-16 08:03 UTC, DEATHB4DEFEAT commented on Content.Server/Mood/MoodSystem.cs
> +    #endregion
```suggestion
```

2024-08-16 08:03 UTC, DEATHB4DEFEAT commented on Content.Shared/Mood/MoodEffectPrototype.cs
> +}
These should be validated

2024-08-20 00:42 UTC, OldDanceJacket approved these changes

2024-08-20 08:16 UTC, merged