Sanek31 1
Simple-Station/Einstein-Engines pull request #659
Opened 2024-08-03 06:05 UTC by sanek31

-->

# Description

-->

Adds the ability to partially pierce armour.
Example:
Armor with 70% protection, when hit by a bullet with 50% penetration and 20 damage, the final damage will be 13 (as if the protection was 35%).

---

-->

- [x] Add a partial armor ignore system

---

-->

<details><summary><h1>Media</h1></summary>
<p>

![Example Media Embed](https://media.discordapp.net/attachments/1249281731719069736/1249281732105080874/finnaly.mp4?ex=66ae9587&is=66ad4407&hm=a26fb7ee1f5ad84de3b69c084f7dd835475defc8e644c02f67018f2ce94f0097&format=webp&width=550&height=289)

</p>
</details>

---

# Changelog

-->

:cl: sanek31
- add: Added partial armor ignore system.

2024-08-03 11:01 UTC, DangerRevolution commented
Why would 70% protection, with 50% piercing reduce protection to 35%?

2024-08-03 11:07 UTC, dge21 commented
because 35 is is 50% of 70

2024-08-03 11:08 UTC, DangerRevolution commented
> because 35 is is 50% of 70

It's too early in the morning, sorry lmaoo 😭😭😭😭😭😭

2024-08-03 11:09 UTC, DangerRevolution approved these changes
This needs dual @VMSolidus @OldDanceJacket approval before merge

2024-08-04 09:27 UTC, DangerRevolution commented
test fail valid it seems like?

2024-08-04 10:28 UTC, Mnemotechnician commented on Content.Shared/Damage/DamageSpecifier.cs
> +        public static DamageSpecifier ApplyModifierSet(DamageSpecifier damageSpec, DamageModifierSet modifierSet, float br = 1)
the parameter should have a meaningful name.

2024-08-04 10:28 UTC, Mnemotechnician commented on Content.Shared/Damage/DamageSpecifier.cs
> +        public static DamageSpecifier ApplyModifierSets(DamageSpecifier damageSpec, IEnumerable<DamageModifierSet> modifierSets, float br = 1)
Same as the above - those are public methods.

2024-08-04 10:28 UTC, Mnemotechnician commented on Content.Shared/Damage/Systems/DamageableSystem.cs
> +                    }
```suggestion
                    damage = DamageSpecifier.ApplyModifierSet(damage, modifierSet, bypassResistance?.Value ?? 1f);
```

2024-08-04 10:28 UTC, Mnemotechnician commented on Content.Shared/Damage/DamageSpecifier.cs
> +                    newValue *= 1-coefficient*br; // coefficients can heal you, e.g. cauterizing bleeding
This is sussy and probably will never work as intended, instead making damage heal you.

2024-08-04 10:30 UTC, Mnemotechnician commented
Also, test fails are completely legitimate. You have type errors in your code and something tells me this was not tested...

2024-08-04 11:48 UTC, WarMechanic reviewed
im not a big fan of 'armour pierce' because it ultimately means that a bullet will have a final say in whether someone takes damage. that is to say if you pitted super armour and 100% armour pierce together, armour pierce will always win regardless of how strong the armour was.

really i think we should go for new damage calculation entirely, an 'armour contest' if you will.

2024-08-04 11:57 UTC, sanek31 commented
Messed up the code. Going to rewrite it

2024-08-05 09:38 UTC, sanek31 commented
Trying to do it locally , but for some reason it's doesn't works for melee weapons.

2024-08-05 21:36 UTC, DangerRevolution commented
> Trying to do it locally , but for some reason it's doesn't works for melee weapons.

You can find any help you need in our Discord if that's useful to you :)

2024-08-06 20:29 UTC, VMSolidus commented
> Trying to do it locally , but for some reason it's doesn't works for melee weapons.

Melee weapons work on a different system entirely from guns, and the two have almost no overlap at all.

2024-08-08 06:03 UTC, Pspritechologist requested changes
I would probably suggest not taking this route for armour penetration. Generic armour penetration can be added by simply modifying DamageSpecifier to take a 'piercing' field of some kind. This field is used when applying damages and what not with an armour value coming from elsewhere. Adding the piercing value in this way allows you to do it while modifying no other functions or APIs and while automatically adding support backwards for anything that deals damage.

2024-08-10 16:14 UTC, sanek31 commented
ok

2024-08-14 06:32 UTC, closed without merging

2024-08-14 07:33 UTC, DEATHB4DEFEAT commented
> I'll close for now, I'll make another pull request when I'm done.

Reopen this one