New Plant Trait : Bluespace Slips
Simple-Station/Einstein-Engines pull request #674
Opened 2024-08-05 00:33 UTC by dootythefrooty

# Description

Adds a new trait which plants can mutate to have. 
It teleports both the slippee and the produce to a random location within a radius determined by how potent the produce is.
Inert unless the plant also has the slippery trait. 

~~Probably very stinky code considering this is my first time dealing with c#.~~

---
<details><summary><h1>Media</h1></summary>
<p>

https://github.com/user-attachments/assets/cd22756d-ea5e-4a30-8043-c991549c9019

</p>
</details>

---

# Changelog

:cl:
- add: Added Bluespace Slips, a plant trait that teleports you randomly if you slip.

2024-08-05 17:38 UTC, VMSolidus commented on Content.Server/Botany/Systems/TeleportingTraitSystem.cs
> +        _xform.SetWorldPosition(args.Slipped, otherPos);
_random.NextVector2 lets you create a random vector with a specific magnitude. Set the magnitude to comp.ProduceTeleportRadius. WorldPosition. 
You can also do _xform.SetWorldPosition(uid, Transform(uid).Coordinates + _random.NextVector2(comp.ProduceTeleportRadius, comp.ProduceTeleportRadius))

Don't quote me on if ifs Coordinates or LocalCoordinates being the one you need, you should probably test this. But Transform(uid) just *contains* both LocalCoordinates and WorldCoordinates, you don't need to query it via TransformSystem.

2024-08-06 19:47 UTC, VMSolidus requested changes

2024-08-06 19:47 UTC, VMSolidus commented on Content.Server/Botany/Systems/TeleportingTraitSystem.cs
> +        _puddle.TrySpillAt(uid, vanishSolution, out _);
```suggestion
        if (!_random.Prob(comp.DeletionChance))
            return;
        Solution vanishSolution = new();
        vanishSolution.AddReagent("Slime", comp.Potency / 2);
        _puddle.TrySpillAt(uid, vanishSolution, out _);
        QueueDel(uid);
```
Probably good practice to do the QueueDel after you call a function that requires said entity exists in order to work. :trollface:

2024-08-06 19:47 UTC, VMSolidus commented on Content.Server/Botany/Components/TeleportingTraitComponent.cs
> +        [DataField("produceTeleportRadius")]
```suggestion
        [DataField]
```

2024-08-06 19:47 UTC, VMSolidus commented on Content.Server/Botany/Components/TeleportingTraitComponent.cs
> +        [DataField("potencyDivide")]
```suggestion
        [DataField]
```

2024-08-06 19:47 UTC, VMSolidus commented on Content.Server/Botany/Components/TeleportingTraitComponent.cs
> +        ///
```suggestion
        /// <summary>
        ///     Teleportation radius of produce.
        /// </summary>
```

2024-08-06 19:47 UTC, VMSolidus commented on Content.Server/Botany/Components/TeleportingTraitComponent.cs
> +        ///
```suggestion
        /// <summary>
        ///     How much to divide the potency.
        /// </summary>
```

2024-08-06 19:47 UTC, VMSolidus commented on Content.Server/Botany/Components/TeleportingTraitComponent.cs
> +        ///
```suggestion
        /// <summary>
        ///     Potency of fruit.
        /// </summary>
```

2024-08-06 19:47 UTC, VMSolidus commented on Content.Server/Botany/Components/TeleportingTraitComponent.cs
> +        [DataField("potency")]
```suggestion
        [DataField]
```

2024-08-06 19:47 UTC, VMSolidus commented on Content.Server/Botany/Components/TeleportingTraitComponent.cs
> +        ///
```suggestion
        /// <summary>
        ///     Chance of deletion.
        /// </summary>
```

2024-08-06 19:47 UTC, VMSolidus commented on Content.Server/Botany/Components/TeleportingTraitComponent.cs
> +        [DataField("deletionChance")]
```suggestion
        [DataField]
```

2024-08-06 19:47 UTC, VMSolidus commented on Content.Server/Botany/SeedPrototype.cs
> +    [DataField("teleporting")] public bool Teleporting;
```suggestion
    [DataField] public bool Teleporting;
```

2024-08-06 20:38 UTC, VMSolidus requested changes

2024-08-06 20:38 UTC, VMSolidus commented on Content.Server/Botany/Components/TeleportingTraitComponent.cs
> +        ///
```suggestion
        /// </summary>
```

2024-08-06 20:38 UTC, VMSolidus commented on Content.Server/Botany/Components/TeleportingTraitComponent.cs
> +        ///
```suggestion
        /// </summary>
```

2024-08-06 20:38 UTC, VMSolidus commented on Content.Server/Botany/Components/TeleportingTraitComponent.cs
> +        ///
```suggestion
        /// </summary>
```

2024-08-06 20:38 UTC, VMSolidus commented on Content.Server/Botany/Components/TeleportingTraitComponent.cs
> +        ///
```suggestion
        /// </summary>
```

2024-08-07 23:52 UTC, VMSolidus approved these changes

2024-08-07 23:53 UTC, DangerRevolution approved these changes

2024-08-07 23:54 UTC, DangerRevolution commented
plant update now where's the zombies?

2024-08-07 23:54 UTC, merged