New Trait: Oni Damage Bonuses
Simple-Station/Einstein-Engines pull request #676
Opened 2024-08-05 06:23 UTC by angelofallars

# Description

Adds three new 1-point traits for Onis that **redistribute** your damage bonuses, allowing you to specialize in Slash or Piercing instead of Blunt, or be a generalist who is equally effective with all melee Brute weapons. The three new traits are **Swashbuckler**, **Spearmaster**, and **Weapons Generalist**.

| Traits / Damage Bonus  | Blunt | Slash | Piercing |
|------------------------|-------|-------|----------|
| Base Oni (No Traits)   | 35%   | 20%   | 20%      |
| **Swashbuckler**       | 20%   | 35%   | 20%      |
| **Spearmaster**        | 20%   | 20%   | 35%      |
| **Weapons Generalist** | 25%   | 25%   | 25%      |

# Changelog

:cl: Skubman
- add: Add three new 1-point traits for Onis that allow you to specialize in Slash or Piercing damage or be a melee weapons generalist.

2024-08-05 11:08 UTC, DangerRevolution requested changes

2024-08-05 11:08 UTC, DangerRevolution commented on Resources/Prototypes/Traits/categories.yml
No new categories until we get scrolling; stick this in physical

2024-08-05 11:08 UTC, DangerRevolution commented on Resources/Locale/en-US/traits/categories.ftl
No new categories until we get scrolling; stick this in physical

2024-08-05 11:08 UTC, DangerRevolution commented on Content.Server/Traits/Assorted/OniDamageModifierComponent.cs
IMO, this should be (one day) a more generic system that can give any species these modifiers; obviously changing the oni modifier to be more generic. Unrelated to this PR though, just giving thoughts for sauce.

2024-08-05 11:11 UTC, angelofallars commented on Content.Server/Traits/Assorted/OniDamageModifierComponent.cs
We just need to extract the melee stuff from the OniSystem and it'll be generic

2024-08-05 11:29 UTC, angelofallars commented on Resources/Prototypes/Traits/categories.yml
Resolved with 75c01358206722e8895b3127ada4dee5929040ef

2024-08-05 11:29 UTC, angelofallars commented on Resources/Locale/en-US/traits/categories.ftl
Resolved with 75c01358206722e8895b3127ada4dee5929040ef

2024-08-06 07:58 UTC, DangerRevolution approved these changes

2024-08-06 19:50 UTC, VMSolidus approved these changes

2024-08-06 19:50 UTC, merged