convert harpy singing into a trait
Simple-Station/Einstein-Engines pull request #714
Opened 2024-08-10 16:48 UTC by Mnemotechnician

# Description
Makes harpies even more generic than they were by making their singing into a trait that certain other species can take.

Singer a 3-point positive trait. For now it's only available for vulps and felinids as they are naturally more vocal than other species.

Also refactored harpy singing system a bit.

# TODO

- [ ] Find out whatever causes this. Not critical, but probably should be fixed... 
<details><p>

![image](https://github.com/user-attachments/assets/8e0a6bf5-5fa3-4a0a-8937-2931dfe4ee62)

</p></details>

<details><summary><h1>Media</h1></summary>
<p>

![image](https://github.com/user-attachments/assets/018b6cf3-d510-46e2-8c38-4bd49e1929bd)

![image](https://github.com/user-attachments/assets/f27bd451-b3c2-4a22-ab50-35c2f4ecbcb3)

</p>
</details>

# Changelog
:cl:
- add: Added a new positive trait - singer. It allows you to play midi songs without an instrument, similarly to harpies.

2024-08-10 16:54 UTC, DangerRevolution commented
remove it from the trait menu

2024-08-10 16:55 UTC, Mnemotechnician commented
> remove it from the trait menu

why so?

2024-08-10 16:55 UTC, DangerRevolution commented
e

> > remove it from the trait menu
> 
> why so?

i updated the comment, should make more sense

2024-08-10 16:56 UTC, Mnemotechnician commented
> Generic Trait = Only whatever instrument the Microphone is Harpy = All instruments

It only gives microphone and some second instrument I forgot

2024-08-10 16:57 UTC, VMSolidus requested changes

2024-08-10 16:57 UTC, VMSolidus commented on Content.Client/Traits/SingerSystem.cs
> +using Content.Shared.Traits.Assorted.Systems;
Nah. This isn't getting merged.

2024-08-10 16:57 UTC, Mnemotechnician commented on Content.Client/Traits/SingerSystem.cs
> +using Content.Shared.Traits.Assorted.Systems;
oops

2024-08-10 16:58 UTC, Mnemotechnician commented on Content.Client/Traits/SingerSystem.cs
> +using Content.Shared.Traits.Assorted.Systems;
wait, what's your problem with that?

2024-08-10 16:59 UTC, DangerRevolution requested changes
Making the component generic is good; I have no idea how MIDI works but there should be some way to assign instruments per component. Ideally, the singer system is just the microphone instrument and then you can reuse it and add more instruments for Harpy

2024-08-10 17:00 UTC, Mnemotechnician commented
> Making the component generic is good; I have no idea how MIDI works but there should be some way to assign instruments per component. Ideally, the singer system is just the microphone instrument and then you can reuse it and add more instruments for Harpy

![image](https://github.com/user-attachments/assets/f5a63970-0306-4d23-b600-ab018631aca6)

2024-08-10 17:01 UTC, DangerRevolution commented
> > Making the component generic is good; I have no idea how MIDI works but there should be some way to assign instruments per component. Ideally, the singer system is just the microphone instrument and then you can reuse it and add more instruments for Harpy
> 
> ![image](https://private-user-images.githubusercontent.com/69920617/356826127-f5a63970-0306-4d23-b600-ab018631aca6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMDk1MzUsIm5iZiI6MTcyMzMwOTIzNSwicGF0aCI6Ii82OTkyMDYxNy8zNTY4MjYxMjctZjVhNjM5NzAtMDMwNi00ZDIzLWI2MDAtYWIwMTg2MzFhY2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDE3MDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NzgyNTU1MGUxYjIyMDYxNzRlYWZhNzAzMTgzYjc3MWI1ZTBlMzNmOTliMDBmYWNhMzFhMTEzOWQ1YTY1YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ADl1x77ZJDbIqmUw4Op_qndC6gKuiUOBWnIKtnfPVY4)

:O

2024-08-10 17:02 UTC, DangerRevolution commented on Resources/Prototypes/Traits/skills.yml
> +    - type: Instrument
```suggestion
    - type: Instrument
```
I only looked at the C# sorry

2024-08-10 17:02 UTC, DangerRevolution commented on Resources/Prototypes/Traits/skills.yml
> +        "Acoustic": { 24: 0 } # All of them use synthesizer samples anyway...
```suggestion
```

2024-08-10 17:02 UTC, DangerRevolution commented on Resources/Prototypes/Traits/skills.yml
> +    - !type:CharacterSpeciesRequirement
???????????

2024-08-10 17:11 UTC, DangerRevolution requested changes
cost higher, remove species requirement

2024-08-10 17:11 UTC, DangerRevolution commented on Resources/Prototypes/Traits/skills.yml
> +  points: -3
```suggestion
  points: -6
```

2024-08-10 17:11 UTC, DangerRevolution commented on Resources/Prototypes/Traits/skills.yml
> +  requirements:
Remove the species requirement

2024-08-10 17:11 UTC, DangerRevolution commented on Resources/Prototypes/Entities/Mobs/Species/harpy.yml
> +
```suggestion
```

2024-08-10 17:12 UTC, VMSolidus requested changes

2024-08-10 17:12 UTC, VMSolidus commented on Resources/Prototypes/Traits/skills.yml
> +  points: -3
```suggestion
  points: -1
```

2024-08-10 17:12 UTC, VMSolidus commented on Resources/Prototypes/Traits/skills.yml
> +        - Felinid
```suggestion
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Harpy
```

2024-08-10 17:16 UTC, DangerRevolution commented on Resources/Prototypes/Traits/skills.yml
> +  points: -3
why?

2024-08-10 17:17 UTC, Mnemotechnician commented
Fuck, uh... Turns out prototypedata class is apart of robust toolbox, I edited it locally, but the change wasn't committed... which is now a test fail.

I need to find a way to fix that...

2024-08-10 17:37 UTC, VMSolidus commented on Resources/Prototypes/Traits/skills.yml
> +  points: -3
It's an extremely minor trait.

2024-08-10 18:53 UTC, Mnemotechnician commented
This works fine now. Singing types are now defined separately from the trait and can be re-used later, which makes things like singing parrots as easy to implement as adding `type: Singer, proto: NormalSinging` to them.

2024-08-10 21:02 UTC, DangerRevolution commented
test fail valid

2024-08-12 09:48 UTC, DangerRevolution commented
test fail still valid

2024-08-12 16:17 UTC, Mnemotechnician commented
I'll look into it, but later

2024-08-14 17:32 UTC, VMSolidus approved these changes

2024-08-15 06:06 UTC, DangerRevolution approved these changes

2024-08-15 06:06 UTC, merged