Oni Horn Markings
Simple-Station/Einstein-Engines pull request #726
Opened 2024-08-12 23:37 UTC by dootythefrooty

# Description

---

Three new Oni horn markings,] two of which have three tone support. There was a distinct lack of large horns, which I tried my hand at.

<details><summary><h1>Media</h1></summary>
<p>

![display](https://github.com/user-attachments/assets/cb0604e8-941c-48fd-8fb8-205893b87c5c)

</p>
</details>

---

# Changelog

:cl:
- add: Added crowned, tall bull, and tall curved Oni horns.

2024-08-13 05:01 UTC, VMSolidus requested changes

2024-08-13 05:01 UTC, VMSolidus commented on Resources/Prototypes/Entities/Mobs/Customization/Markings/oni_horns.yml
> +  - sprite: Mobs/Customization/oni/oni_horns48x48.rsi
```suggestion
  - sprite: Mobs/Customization/Oni/oni_horns48x48.rsi
```

2024-08-13 05:01 UTC, VMSolidus commented on Resources/Prototypes/Entities/Mobs/Customization/Markings/oni_horns.yml
> +    state: tall_curved_3tone_3
```suggestion
  sprites:
  - sprite: Mobs/Customization/Oni/oni_horns48x48.rsi
    state: tall_curved_3tone_1
  - sprite: Mobs/Customization/Oni/oni_horns48x48.rsi
    state: tall_curved_3tone_2
  - sprite: Mobs/Customization/Oni/oni_horns48x48.rsi
    state: tall_curved_3tone_3
```

2024-08-13 05:01 UTC, VMSolidus commented on Resources/Prototypes/Entities/Mobs/Customization/Markings/oni_horns.yml
> +  - sprite: Mobs/Customization/oni/oni_horns48x48.rsi
```suggestion
  - sprite: Mobs/Customization/Oni/oni_horns48x48.rsi
```

2024-08-13 05:01 UTC, VMSolidus commented on Resources/Prototypes/Entities/Mobs/Customization/Markings/oni_horns.yml
> +  - sprite: Mobs/Customization/oni/oni_horns48x48.rsi
```suggestion
  - sprite: Mobs/Customization/Oni/oni_horns48x48.rsi
    state: tall_bull_3tone_1
  - sprite: Mobs/Customization/Oni/oni_horns48x48.rsi
    state: tall_bull_3tone_2
  - sprite: Mobs/Customization/Oni/oni_horns48x48.rsi
```

2024-08-13 05:01 UTC, VMSolidus commented on Resources/Prototypes/Entities/Mobs/Customization/Markings/oni_horns.yml
> +  - sprite: Mobs/Customization/oni/oni_horns.rsi
```suggestion
  - sprite: Mobs/Customization/Oni/oni_horns.rsi
```

2024-08-13 17:10 UTC, DangerRevolution requested changes
Test fail valid

2024-08-14 02:30 UTC, VMSolidus approved these changes

2024-08-14 09:05 UTC, DangerRevolution approved these changes

2024-08-14 09:05 UTC, merged