Implement Mind Contests
Simple-Station/Einstein-Engines pull request #757
Opened 2024-08-20 19:34 UTC by VMSolidus

# Description

Now that the initial Psionic Refactor is out of the way, this is my first new standalone Psionics PR, filling in the MindContest function that was added over a month ago(but was set to always return 1f as a placeholder). 

Mind Contests are unique among the Contests System in that they do not treat the lack of a Psionic Component as a failure condition, and instead as a variable.

No changelog because MindContests are not currently used anywhere, all I'm doing is adding the actual function logic.

2024-08-21 09:05 UTC, DEATHB4DEFEAT requested changes

2024-08-21 09:05 UTC, DEATHB4DEFEAT commented on Content.Shared/Contests/ContestsSystem.cs
> +        /// </remarks> exist
```suggestion
```

2024-08-21 09:05 UTC, DEATHB4DEFEAT commented on Content.Shared/Contests/ContestsSystem.cs
> +        ///     MaybeMassContest, in case your entity doesn'so be ready to meet god if you bypass the clamp.
?
```suggestion
        ///     MaybeMassContest, in case your entity isn't ready to meet god if you bypass the clamp.
```

2024-08-21 09:05 UTC, DEATHB4DEFEAT commented on Content.Shared/Contests/ContestsSystem.cs
Remove all the empty param tags

2024-08-21 09:17 UTC, DEATHB4DEFEAT approved these changes

2024-08-23 03:16 UTC, OldDanceJacket approved these changes

2024-08-23 03:16 UTC, merged