Added Jukebox (#26736)
Simple-Station/Einstein-Engines pull request #802
Opened 2024-08-25 18:52 UTC by DJB1gYAPPA

* Added Jukebox, along with music for jukebox

* Fixed Jukebox meta.json copyright

* Removed songs I couldn't find a license for.

* Renamed files to solve check failures from spaces

* Added missing attributions.yml

* Fixed lack of description in Jukebox

* Jukebox is now constructable.

* Change Jukebox menu to FancyWindow

* Moved Jukebox messages out of jukebox component

* Removed Jukebox OnValueChanged.

* JukeboxComp now uses AutoGenerateComponentState

* Removed state code, since it's auto generated

* Fixed various Jukebox code to match conventions.

* Updated Standard.yml to match changed song list.

* fixes

* Jukebox workin

* Fix

* Polishing

* Finalising

* Revert

* bad

* jukey

* Reviews

* name

* Update submodule to 218.2.0

---------

# Description

Description.

---

# TODO

- [ ] Task
- [x] Completed Task

---

<details><summary><h1>Media</h1></summary>
<p>

![Example Media Embed](https://example.com/thisimageisntreal.png)

</p>
</details>

---

# Changelog

:cl:
- add: Added fun :D
- tweak: Tweaked fun
- fix: Fixed fun!
- remove: Removed fun :(

2024-08-26 01:13 UTC, VMSolidus commented
![image](https://github.com/user-attachments/assets/7144ab85-6307-4b8b-93a2-e84b9999e00a)

Test fail is legitimate.

2024-08-26 01:39 UTC, VMSolidus commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +      - JukebocCurcuitBoard
```suggestion
      - JukeboxCircuitBoard
```

2024-08-26 07:19 UTC, DangerRevolution commented
Fill out the PR please; add a changelog and (optionally) add a video of it working.

2024-08-26 10:16 UTC, DJB1gYAPPA commented
> Fill out the PR please; add a changelog and (optionally) add a video of it working.

I can not get a local build to work for me, however, it works for everyone else. I wont be able to add a video of it working, or a snapshot of what it looks like in game

2024-08-26 21:25 UTC, VMSolidus approved these changes

2024-08-29 22:49 UTC, FoxxoTrystan requested changes
Please make a better Changlog, but overall.
Good job!

2024-09-02 02:14 UTC, FoxxoTrystan approved these changes

2024-09-02 02:28 UTC, merged