Default TOML File
Simple-Station/Einstein-Engines pull request #818
Opened 2024-08-29 19:49 UTC by VMSolidus

# Description

We've had the DeltaV TOML files for awhile now, and it's come up that we very strongly need to update the defaults. Someone who actually knows what they're doing(I'm not a server host, I'm just the guy who codes a ton of random things), please let me know if I've gotten anything wrong here.

2024-08-29 23:25 UTC, DEATHB4DEFEAT requested changes

2024-08-29 23:25 UTC, DEATHB4DEFEAT commented on Resources/ConfigPresets/EinsteinEngines/default.toml
> +round_end_pacifist = true
```suggestion
```

2024-08-29 23:25 UTC, DEATHB4DEFEAT commented on Resources/ConfigPresets/EinsteinEngines/default.toml
> +hostname           = "Default EE Server Name, please change this to your intended server name"
```suggestion
hostname           = "Einstein Engines (change this)"
```

2024-08-29 23:25 UTC, DEATHB4DEFEAT commented on Resources/ConfigPresets/EinsteinEngines/default.toml
> +rich_main_icon_id = "einstein-engines"
We need to PR the EE icon to the assets repo

2024-08-29 23:25 UTC, DEATHB4DEFEAT commented on Resources/ConfigPresets/EinsteinEngines/default.toml
> +id = "einstein-engines"
```suggestion
[build]
fork_id = "EinsteinEngines"

[server]
```

2024-08-29 23:25 UTC, DEATHB4DEFEAT commented on Resources/ConfigPresets/EinsteinEngines/default.toml
> +discord    = "https://discord.gg/zgQVdEPJ8w"
```suggestion
discord    = "https://discord.gg/X4QEXxUrsJ"
```

2024-08-29 23:25 UTC, DEATHB4DEFEAT commented on Resources/ConfigPresets/EinsteinEngines/default.toml
> +limit    = 10.0
```suggestion
limit = 10.0
```

2024-08-29 23:25 UTC, DEATHB4DEFEAT commented on Resources/ConfigPresets/EinsteinEngines/default.toml
> +soft_max_players   = 100
```suggestion
soft_max_players   = 60
```

2024-09-02 20:10 UTC, DEATHB4DEFEAT approved these changes

2024-09-04 17:21 UTC, stellar-novas approved these changes

2024-09-08 06:56 UTC, merged