Update Clothing Assignments of Suit/Skirt
Simple-Station/Einstein-Engines pull request #857
Opened 2024-09-04 18:37 UTC by Tirochora

# Description

Changes some outfits, notably the Operative Jumpskirt, Kimono, Dark/Light Monastic Robes, and the Gladiator Uniform to be assigned as skirts, rather than suits. This allows harpies to wear them. In addition, the UnsensoredClothingSkirtBase base now possesses the 'ClothMade' tag, allowing moths to eat outfits with this base.

---

# Changelog

:cl:
- tweak: Fixes a few typos in outfit descriptions
- fix: The Kimono, Dark/Light Monastic Robes, Gladiator Uniform, and Operative Jumpskirt should be properly considered jumpskirts, and are by extension wearable for harpies. 
- fix: Moths should be able to eat outfits with the UnsensoredClothingSkirtBase parent.

2024-09-05 00:28 UTC, Tirochora commented
Ah, right. I forgot to mention that this also changes all of the base colored jumpskirts to be proper skirts, but I don't suppose that's of much use since there's a separate PR that went through for that.

2024-09-06 16:21 UTC, VMSolidus requested changes

2024-09-06 16:21 UTC, VMSolidus commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
> +#     sprite: Clothing/Uniforms/Jumpsuit/kimono.rsi
```suggestion
```

If you are moving these to a different location, you do not need to leave the originals commented.

2024-09-08 14:32 UTC, VMSolidus approved these changes

2024-09-09 03:48 UTC, OldDanceJacket approved these changes

2024-09-09 04:13 UTC, merged