weather block marker, rad markers and invisible walls
Simple-Station/Einstein-Engines pull request #862
Opened 2024-09-06 09:00 UTC by Peptide90

Ported from Nuclear14 by request of @OldDanceJacket as they wanted the weather blocking markers. Tought you may as well get the rest of the stuff for rad markers and invisible walls too. Useful for planets.

2024-09-06 18:23 UTC, VMSolidus requested changes

2024-09-06 18:23 UTC, VMSolidus commented on Resources/Prototypes/Entities/Markers/environmental.yml
> +      - sprite: _Nuclear14/Markers/environment.rsi
```suggestion
      - sprite: Markers/environment.rsi
        state: base-green
        shader: unshaded
      - sprite: Markers/environment.rsi
```

2024-09-06 18:23 UTC, VMSolidus commented on Resources/Prototypes/Entities/Markers/environmental.yml
> +      - sprite: _Nuclear14/Markers/environment.rsi
```suggestion
      - sprite: Markers/environment.rsi
        state: base-blue
        shader: unshaded
      - sprite: Markers/environment.rsi
```

2024-09-06 18:23 UTC, VMSolidus commented on Resources/Prototypes/Entities/Markers/environmental.yml
> +    sprite: _Nuclear14/Markers/environment.rsi
```suggestion
    sprite: Markers/environment.rsi
```

2024-09-10 10:41 UTC, Peptide90 commented
My bad for copy pasting

2024-09-11 17:54 UTC, VMSolidus approved these changes

2024-09-14 17:50 UTC, DEATHB4DEFEAT approved these changes

2024-09-14 17:50 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Entities/Markers/environmental.yml
> +  - type: BlockWeather
```suggestion
  - type: BlockWeather

```

2024-09-14 17:50 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Entities/Markers/environmental.yml
> +          bounds: "-0.5,-0.5,0.5,0.5"
Isn't that upside down? Probably doesn't matter much.
```suggestion
          bounds: "-0.5,0.5,-0.5,0.5"
```

2024-09-14 17:59 UTC, VMSolidus approved these changes

2024-09-14 19:55 UTC, VMSolidus commented
![image](https://github.com/user-attachments/assets/be92cdf2-f3c1-4962-981b-3ba8daf9def3)

HOW THE FUCK DID THIS BREAK THE PR?

2024-09-14 20:06 UTC, merged

2024-09-16 18:19 UTC, Peptide90 commented
> ![image](https://private-user-images.githubusercontent.com/16548818/367540396-be92cdf2-f3c1-4962-981b-3ba8daf9def3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MTEwNDcsIm5iZiI6MTcyNjUxMDc0NywicGF0aCI6Ii8xNjU0ODgxOC8zNjc1NDAzOTYtYmU5MmNkZjItZjNjMS00OTYyLTk4MWItM2JhOGRhZjlkZWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE4MTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjYzg2ZDY0ZjEzNWQ0MzE3NTgyZTRhYmJjNDA4M2Y4N2MzODI3YjllNGJjMjEzZDA4NThiZTk2YWE4ZjY2Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QVCAR4CyG2yH3ilfZ-x2T75wRXzb6qw0Pi0ipcRzwCE)
> 
> HOW THE FUCK DID THIS BREAK THE PR?

Odd that it is literally identical to N14 but it works there no errors.