remove the justice department
Simple-Station/Einstein-Engines pull request #867
Opened 2024-09-06 19:33 UTC by Elijahrane

# Description

Removes the justice department.

# Changelog

:cl: Rane
- remove: Removed the Justice Department.

2024-09-06 19:36 UTC, ShatteredSwords commented
The whole point of porting Justice was so EE could port stuff from Delta without any issues 🙃

2024-09-06 19:45 UTC, gluesniffler commented
based

2024-09-06 21:49 UTC, VMSolidus requested changes

2024-09-06 21:49 UTC, VMSolidus commented on Resources/Prototypes/DeltaV/Entities/Clothing/Uniforms/jumpsuits.yml
> -    sprite: DeltaV/Clothing/Uniforms/Jumpsuit/cjformal.rsi
Leave stuff like clothing item assets in, please. They can just be added as loadout items for Lawyers to take.

2024-09-06 21:49 UTC, VMSolidus commented on Resources/Prototypes/DeltaV/Entities/Clothing/Head/hats.yml
> -- type: entity
Same with hats, cloaks, etc.

2024-09-06 21:59 UTC, VMSolidus requested changes

2024-09-06 21:59 UTC, VMSolidus commented on Resources/Migrations/eeMigration.yml
> +PaperStationWarrant: null
```suggestion
ChiefJusticePDA: null
ChiefJusticeIDCard: null
LockerChiefJustice: null
LockerChiefJusticeFilled: null
SpawnPointChiefJustice: null
DefaultStationBeaconJustice: null
DefaultStationBeaconChiefJustice: null
DefaultStationBeaconProsecutor: null
RubberStampChiefJustice: null
AirlockJustice: Airlock
AirlockJusticeGlass: AirlockGlass
AirlockChiefJusticeLocked: AirlockLawyerLocked
AirlockProsecutorLocked: AirlockLawyerLocked
AirlockChiefJusticeGlassLocked: AirlockLawyerGlassLocked
AirlockProsecutorGlassLocked: AirlockLawyerGlassLocked
AirlockJusticeLocked: AirlockLawyerLocked
AirlockMaintChiefJusticeLocked: AirlockLawyerLocked
AirlockMaintJusticeLocked: AirlockLawyerLocked
AirlockMaintProsecutorLocked: AirlockLawyerLocked
WindoorSecureChiefJusticeLocked: WindoorSecureLawyerLocked
WindoorSecureProsecutorLocked: WindoorSecureLawyerLocked
WindoorSecureJusticeLocked: WindoorSecureLawyerLocked
DoorElectronicsChiefJustice: DoorElectronicsLawyer
DoorElectronicsJustice: DoorElectronicsLawyer
DoorElectronicsProsecutor: DoorElectronicsLawyer
ProsecutorPDA: null
BoxPDAJustice: null
SpawnPointProsecutor: null
SpawnPointClerk: null
ProsecutorIDCard: null
LockerClerk: null
LockerclerkFilled: null
ClerkPDA: null
ClerkIDCard: null
RubberStampNotary: null
EncryptionKeyJustice: null
ClothingHeadsetJustice: null
DoorRemoteJustice: null
SignDirectionalJuistice: null
PaperStationWarrant: null
```
Okay, I've put in a list of all the items I'd like for us to keep, but to instead just be Lawyer Loadout Items.

2024-09-06 23:01 UTC, Flybik commented
I then propose to immediately remove all roles except engineers and force them to build the station during their shift. 😡

2024-10-07 21:11 UTC, FoxxoTrystan commented
Is this PR still getting worked on?

2024-10-07 22:33 UTC, FoxxoTrystan commented
> Presumably I'm supposed to be repobanned so I never bothered to check

Huh? wha?
@VMSolidus ?

2024-10-07 23:39 UTC, VMSolidus commented
> Presumably I'm supposed to be repobanned so I never bothered to check

I literally don't have the ability to repoban people. I also don't care to repoban people unless they're doing something ridiculous like making a PR that replaces every word in the entire repo with a racial slur.

2024-10-08 01:17 UTC, Elijahrane commented
Well I'm not really interested in finishing this PR but I may have something to contribute at a later date, who knows

2024-10-08 01:17 UTC, closed without merging