Evgencheg patch 1
Simple-Station/Einstein-Engines pull request #869
Opened 2024-09-06 20:35 UTC by Evgencheg

# Description

Description.

---

# TODO

- [ ] Task
- [x] Completed Task

---

<details><summary><h1>Media</h1></summary>
<p>

![Example Media Embed](https://example.com/thisimageisntreal.png)

</p>
</details>

---

# Changelog

:cl:
- add: Added fun :D
- tweak: Tweaked fun
- fix: Fixed fun!
- remove: Removed fun :(

2024-09-06 21:16 UTC, Evgencheg commented
FALSE TEST!!!!

2024-09-07 00:26 UTC, DEATHB4DEFEAT requested changes

2024-09-07 00:26 UTC, DEATHB4DEFEAT commented on .github/workflows/changelog.yml
> +  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
The code looks for `GITHUB_TOKEN`

```suggestion
  GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
```

2024-09-07 00:35 UTC, VMSolidus approved these changes

2024-09-07 00:40 UTC, DEATHB4DEFEAT approved these changes

2024-09-07 00:40 UTC, DEATHB4DEFEAT commented on .github/workflows/changelog.yml
> +        ref: master
```suggestion
        ref: ${{ vars.CHANGELOG_BRANCH }}
```

2024-09-07 00:43 UTC, merged