Cherry-pick "Shrimp Mob for Metempsychosis (#862)"
Simple-Station/Einstein-Engines pull request #882
Opened 2024-09-07 10:04 UTC by Mnemotechnician

# Description
Cherry-picks https://github.com/deltaV-Station/delta-v/pull/862 on behalf of the author.

This was not tested; need someone to check if it actually works before merging.

# Changelog
:cl:
- add: A shrimp morphotype was added to the failure pool of the metempsychotic machine.

2024-09-07 11:07 UTC, leonardo-dabepis commented
ah yes the one I coded while high

2024-09-08 07:23 UTC, DEATHB4DEFEAT approved these changes
Shrimply incredible.

2024-09-08 07:23 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/fun.yml
> +  suffix: METEM MACHINE ONLY #for now, only to be used as a very rare result for the metempsychosis machine. If fishing ever gets added, this suffix can be removed.
```suggestion
```

2024-09-08 07:23 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/fun.yml
> +    bloodReagent: BbqSauce #australia reference
```suggestion
    bloodReagent: BbqSauce # Australia reference
```

2024-09-08 14:35 UTC, VMSolidus requested changes

2024-09-08 14:35 UTC, VMSolidus commented on Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/fun.yml
> +    - PyrokinesisPower
```suggestion
```

2024-09-08 14:55 UTC, VMSolidus approved these changes

2024-09-08 14:56 UTC, merged