Physical pulling
Simple-Station/Einstein-Engines pull request #883
Opened 2024-09-07 14:55 UTC by Mnemotechnician

# Description
This is a draft, I still have something to fix.

Fixes pulling being obnoxiously unphysical. Entities now exert a specific amount of force defined as the product of their mass and the SpecificForce set in their PullerComponent. Doing a ctrl-right click now sets a target position where your entity begins to continuously push the pulled entity towards, instead of throwing it or pushing it once (however, it should still be possible to drag people and disposals and the like). Additionally, your entity will properly experience recoil from dragging someone around.

# TODO
- [X] Do stuff
- [ ] Fix stuff
- [ ] Fix aghosts not being able to push (?)
- [ ] Fix pulling giving you free kinetic energy while in spess (how?)
- [ ] Test if throwing felinids into disposals via pulling still works :trollface:

<details><summary><h1>Media</h1></summary>
<p>

https://github.com/user-attachments/assets/2498ef8c-f743-4702-b73c-b2da0c16e9aa

</p>
</details>

# Changelog
TODO CL

2024-09-12 17:22 UTC, Mnemotechnician commented
This wostly morks now, so marking as ready to review.



https://github.com/user-attachments/assets/d1d12b42-da58-4a97-b04c-c95a87fcd8c8

2024-09-17 19:08 UTC, FoxxoTrystan requested changes
Pleasae update the description and CL.

2024-09-17 21:00 UTC, FoxxoTrystan approved these changes

2024-09-17 23:38 UTC, VMSolidus approved these changes

2024-09-17 23:38 UTC, merged