Fix #864 and rehydratable system doing client-side spawn
Simple-Station/Einstein-Engines pull request #888
Opened 2024-09-08 11:35 UTC by Mnemotechnician

# Description
- Resolves #864 by partially reverting #516 
- Adds a _net.IsClient check to RehydratableSystem to avoid spawning duplicate entities on client side

<details><summary><h1>Media</h1></summary>
<p>

https://github.com/user-attachments/assets/e50785a6-b5f7-4484-9097-118bc3a5dfa5

</p>
</details>

---

# Changelog
:cl:
- fix: Cyborg recharging stations finally work again.
- fix: Rehydratable entities (such as monkey cubes) no longer spawn a second client-side entity when rehydrated.

2024-09-08 14:37 UTC, VMSolidus requested changes

2024-09-08 14:37 UTC, VMSolidus commented on Content.Server/Power/Components/ActiveChargerComponent.cs
> +}
```suggestion
namespace Content.Server.Power.Components;

[RegisterComponent]
public sealed partial class ActiveChargerComponent : Component { }
```

2024-09-08 14:43 UTC, VMSolidus approved these changes

2024-09-11 17:54 UTC, VMSolidus approved these changes

2024-09-11 20:02 UTC, OldDanceJacket approved these changes

2024-09-14 17:55 UTC, merged