User-friendly sprinting
Simple-Station/Einstein-Engines pull request #889
Opened 2024-09-08 14:04 UTC by Mnemotechnician

# Description
"Walking by default" is now implemented as a client-side toggle in the settings. Also, fixed walking alerts being shitcode and not displaying the correct walking/running state.

One issue still persists: if you press the "toggle walk" button while typing in the chat, it still resets the walking state to default. I don't know what causes it, probably the input field leaking button-up input events instead of marking them as handled.

<details><summary><h1>Media</h1></summary>
<p>

https://github.com/user-attachments/assets/97d5b495-ea9b-4854-a6b0-84815ed5a332

</p>
</details>

# Changelog
:cl:
- add: You can now choose whether you want to walk or run by default in the settings.

2024-09-09 04:27 UTC, VMSolidus requested changes

2024-09-09 04:27 UTC, VMSolidus commented on Content.Shared/Movement/Events/UpdateInputCVarsMessage.cs
> +}
```suggestion
[Serializable, NetSerializable]
public sealed class UpdateInputCVarsMessage : EntityEventArgs { }
```

2024-09-11 17:54 UTC, VMSolidus approved these changes

2024-09-11 20:02 UTC, OldDanceJacket approved these changes

2024-09-14 05:44 UTC, FoxxoTrystan approved these changes

2024-09-14 05:44 UTC, merged