Non-Destructive Universal Language
Simple-Station/Einstein-Engines pull request #899
Opened 2024-09-10 01:48 UTC by VMSolidus

# Description

UniversalLanguageSpeakerComponent has NUMEROUS issues, which previously were easy to ignore since it was a language only obtainable by Admins. But now that it's both a Psionic Power(And a trait that adds said power), the issues with it have been highlighted. Here's just a FEW

1. UniversalLanguageSpeaker overwrites all known languages, preventing you from speaking anything else
2. It overwrites the ability to use sign language.
3. It also overwrites the Mute trait.

To fix that, I've made it follow *MOSTLY* the logic all the other languages use, so that it's less of a special snowflake case. Now if you have access to it, it will appear in your language list alongside other languages, rather than fully replacing the entire list. That way you can intentionally choose not to speak in a language understood by all.

# Changelog

:cl:
- fix: UniversalLanguageSpeaker(And Xenoglossy by extension) will now appear in your language menu alongside other known languages, rather than replace all known languages. You can effectively now choose whether or not to speak it, or to use a normal language.
- add: Traits can now add Languages directly.

2024-09-10 05:31 UTC, FoxxoTrystan commented
Reading this from a laptop, i suggest letting @Mnemotechnician a read as currently unable to do it correctly.

2024-09-10 05:53 UTC, Alithsko commented
I'm the one who brought this to light to OP, and it was worse than overwriting mute as it gave you the message that you cannot speak with no other mute friendly choices like sign, which made it a strict downgrade if you get it, happened to me in a game so this is a godsend

2024-09-10 12:47 UTC, Mnemotechnician requested changes
On a side note, I hate how this PR is straight up hardcoding this behavior in the trait system, but I guess it's acceptable for now since we do not have a proper system in place... Maybe in the future we can refactor it to accept polymorphic actions instead, similarly to e.g. reagent effects, or damage behaviors, or interactions...

2024-09-14 19:53 UTC, VMSolidus commented
https://github.com/user-attachments/assets/4dbdfff5-d41a-468c-8229-94e29d75dac1

I have finished fixing this PR, and finished testing to verify that everything works correctly.

2024-09-15 20:57 UTC, VMSolidus commented
I ALSO REQUIRE THIS PR IN ORDER TO CONTINUE WORKING ON PSIONICS.

2024-09-18 04:28 UTC, DEATHB4DEFEAT approved these changes

2024-09-18 04:28 UTC, DEATHB4DEFEAT commented on Content.Server/Language/LanguageSystem.cs
> +    }
```suggestion
    }

```

2024-09-19 23:30 UTC, VMSolidus commented
![image](https://github.com/user-attachments/assets/bc1d9519-fb4d-4373-b0ba-7d8a18ded073)

Translator on: 
![image](https://github.com/user-attachments/assets/76059930-587b-4b27-8e0b-6cec6c958aa2)

Translator off:
![image](https://github.com/user-attachments/assets/80526554-28b8-442a-8542-85821ab97304)

Done here,

2024-09-20 01:29 UTC, Mnemotechnician requested changes
Do not remove the optional component parameters. Passing components around instead of fetching them anew every time they are needed is the preferred style in ss14. You can use `Entity<SomeComp>` instead of EntityUid if you want prettier code.

2024-09-20 01:29 UTC, Mnemotechnician commented on Content.Server/Language/LanguageSystem.cs
> -        LanguageSpeakerComponent? speaker = null)
Do not remove those. If it bothers you so much, make them into `Entity<LanguageSpeakerComponent?, LanguageKnowledgeComponent?>`.

2024-09-20 01:29 UTC, Mnemotechnician commented on Content.Server/Language/LanguageSystem.cs
> -    public void UpdateEntityLanguages(EntityUid entity, LanguageSpeakerComponent? languages = null)
Same here.

2024-09-20 01:29 UTC, VMSolidus commented
> Do not remove the optional component parameters. Passing components around instead of fetching them anew every time they are needed is the preferred style in ss14. You can use `Entity<SomeComp>` instead of EntityUid if you want prettier code.

No.

2024-09-20 01:47 UTC, FoxxoTrystan approved these changes
Could have been nicer then just "no"
But at least this works.

2024-09-20 01:47 UTC, VMSolidus commented
> Could have been nicer then just "no" But at least this works.

Yep, and I'm going to go immediately start work on Language Menu now.

2024-09-20 01:47 UTC, merged