Penlight-Fixes
Simple-Station/Einstein-Engines pull request #900
Opened 2024-09-10 17:03 UTC by SleepyScarecrow

# Description

Tweaked penlights some.  You can no longer examine random objects, you cannot examine your own eyes, and the penlight now needs to be actually on in order to use. Also tweaked the messages to be more accurate.

--

# Changelog

:cl: Tilkku
- tweak: Penlight Exam Messages
- fix: Penlights now need to be on in order to examine
- fix: Penlights can no longer be used on self

2024-09-10 17:05 UTC, SleepyScarecrow commented
https://github.com/user-attachments/assets/3254d534-6117-4122-b397-aee8109ea779

2024-09-10 17:16 UTC, SleepyScarecrow commented
why did that check fail, i cannot tell if that's my fault lol

2024-09-11 03:09 UTC, VMSolidus requested changes

2024-09-11 03:09 UTC, VMSolidus commented on Content.Server/Medical/PenLightSystem.cs
> +        if (target == null || !args.CanReach || !HasComp<MobStateComponent>(target) || !_powerCell.HasDrawCharge(uid, user: args.User))
```suggestion
        if (args.Handled
            || args.Target is not {} target
            || target == null 
            || !args.CanReach 
            || !HasComp<MobStateComponent>(target) 
            || !_powerCell.HasDrawCharge(uid, user: args.User))
```

2024-09-11 03:09 UTC, VMSolidus commented on Content.Server/Medical/PenLightSystem.cs
> +            return;
```suggestion
        if (!_uiSystem.TryGetUi(penlight, PenLightUiKey.Key, out var ui)
            || !HasComp<EyeComponent>(target)
            || !HasComp<DamageableComponent>(target))
            return;
```

2024-09-11 20:02 UTC, VMSolidus approved these changes

2024-09-11 20:02 UTC, merged