Port Ghost Bar
Simple-Station/Einstein-Engines pull request #904
Opened 2024-09-11 02:19 UTC by VMSolidus

# Description

This PR ports https://github.com/Goob-Station/Goob-Station/pull/454
By popular request from our Downstreams

# Changelog

:cl:
- add: Ghost Bar has been ported from Goob Station

2024-09-11 02:47 UTC, DEATHB4DEFEAT commented
Put the original PR's media in your description.

2024-09-11 02:47 UTC, VMSolidus commented
> Put the original PR's media in your description.

done

2024-09-11 03:08 UTC, DEATHB4DEFEAT requested changes

2024-09-11 03:08 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/Goobstation/guidebook/ghost-gui.ftl
> +ghost-window-spawn-ghostbar-button-timer = Spawn at Ghost Bar ({$time}s)
```suggestion
ghost-window-spawn-ghostbar-button = Spawn at the Ghost Bar
ghost-window-spawn-ghostbar-button-timer = Spawn at the Ghost Bar ({$time}s)
```

2024-09-14 17:53 UTC, DEATHB4DEFEAT commented on Content.Server/Ghostbar/GhostBarSystem.cs
> +    const string MapPath = "Maps/Ruins/ghostbar.yml";
```suggestion


    const string MapPath = "Maps/Ruins/ghostbar.yml";

```

2024-09-14 17:53 UTC, DEATHB4DEFEAT commented on Content.Server/Ghostbar/GhostBarSystem.cs
> +
```suggestion


    public override void Initialize()
    {
        SubscribeLocalEvent<RoundStartingEvent>(OnRoundStart);
        SubscribeNetworkEvent<GhostBarSpawnRequestEvent>(SpawnPlayer);
        SubscribeLocalEvent<GhostBarPlayerComponent, MindRemovedMessage>(OnPlayerGhosted);
    }


```

2024-09-18 10:09 UTC, Peptide90 commented
Thunderdome next for the station to watch ghosts fight it out? :)

2024-10-19 08:43 UTC, DEATHB4DEFEAT approved these changes
do that one unresolved thing

2024-10-20 07:07 UTC, Aidenkrz commented
> Thunderdome next for the station to watch ghosts fight it out? :)

Bad idea, putting ghost players in the same map as the station will always lead to them finding ways to break out.

I do plan on adding onto ghost bar in the future, giving it a secondary section with a gladiator arena that the ghost bar people can watch.
The main bar everyone will spawn with pacifism, the gladiator arena people will spawn with random combat loadouts.

2024-10-20 07:09 UTC, Aidenkrz requested changes
As the person who made this, ghost bar has some issues that need to be fixed before it should be merged. For some reason, this carries over the identity of the player completely, so if someone has a kill objective on the player, and they respawn at ghost bar, it will mark as failed. It's probably an easy fix, but i haven't bothered to look into it.

Checking out how objectives identify a target as dead should reveal how to fix it.

2024-10-20 07:10 UTC, Aidenkrz commented
I may modify this myself to fix it.

2024-10-27 09:34 UTC, Peptide90 commented
> > Thunderdome next for the station to watch ghosts fight it out? :)
> 
> Bad idea, putting ghost players in the same map as the station will always lead to them finding ways to break out.
> 
> I do plan on adding onto ghost bar in the future, giving it a secondary section with a gladiator arena that the ghost bar people can watch. The main bar everyone will spawn with pacifism, the gladiator arena people will spawn with random combat loadouts.

THUNDERDOME! :) It's red vs blue if you don't know where the players select their loadouts and battle it out with hammers and swords and stuff. Then link back to the station for people to watch.

2024-10-31 02:10 UTC, Aidenkrz commented
> > > Thunderdome next for the station to watch ghosts fight it out? :)
> > 
> > 
> > Bad idea, putting ghost players in the same map as the station will always lead to them finding ways to break out.
> > I do plan on adding onto ghost bar in the future, giving it a secondary section with a gladiator arena that the ghost bar people can watch. The main bar everyone will spawn with pacifism, the gladiator arena people will spawn with random combat loadouts.
> 
> THUNDERDOME! :) It's red vs blue if you don't know where the players select their loadouts and battle it out with hammers and swords and stuff. Then link back to the station for people to watch.

I actually already designed most of it, with a gladiator role/loadout + handheld TVs and body cams
Only issue that i hate is that i couldn't figure out how to get device networks to work across grids, Frontier peeps might know more about it

2024-11-09 17:11 UTC, bruhmogus commented
ragh!! the arcade machines should be rotated unless the media is just outdated

2024-11-23 14:41 UTC, PuroSlavKing commented
when?

2024-11-23 20:03 UTC, v0idRift commented
+1

2024-12-02 20:49 UTC, Aidenkrz commented
> As the person who made this, ghost bar has some issues that need to be fixed before it should be merged. For some reason, this carries over the identity of the player completely, so if someone has a kill objective on the player, and they respawn at ghost bar, it will mark as failed. It's probably an easy fix, but i haven't bothered to look into it.
> 
> Checking out how objectives identify a target as dead should reveal how to fix it.

This was fixed on goob btw

2024-12-22 09:14 UTC, BL02DL commented
Wouldn't it be better to make it look like a ghost role rather than a button?

2025-01-01 18:57 UTC, Vonsant commented
Antagonist targets appear on people in the ghost bar.

2025-01-31 08:32 UTC, angelofallars commented
Already implemented in https://github.com/Simple-Station/Einstein-Engines/pull/1675, closing

2025-01-31 08:32 UTC, closed without merging