Longarms Require Wielding
Simple-Station/Einstein-Engines pull request #913
Opened 2024-09-12 00:23 UTC by VMSolidus

# Description

Take 1, I hope it's this simple. This is an important balancing feature that means you can't use longarms (Rifles, Machine Guns, Shotguns, etc.) without holding them in two hands. I might revisit this later and create options that can bypass this requirement, but for now this is needed so that Nukies in EE don't just "Buy Jugsuit, L6, Eshield, Auto-Win".

# Changelog

:cl:
- add: All "Long-arms", Rifles, Light Machine Guns, Shotguns, now require wielding to use.

2024-09-14 05:35 UTC, FoxxoTrystan requested changes
What about the sawn-off shotgun and the handmade pistol?
in shotgun category.

2024-09-18 04:29 UTC, DEATHB4DEFEAT approved these changes

2024-09-20 20:14 UTC, VMSolidus commented
> What about the sawn-off shotgun and the handmade pistol? in shotgun category.

Sawn-off, pistol, and improvised shotgun now all don't require wielding.

2024-09-20 20:15 UTC, FoxxoTrystan approved these changes

2024-09-20 20:35 UTC, merged