Harpy Flight System
Simple-Station/Einstein-Engines pull request #919
Opened 2024-09-14 17:12 UTC by gluesniffler

# Description

This PR adds a generic system which gives an entity the ability to fly. Increasing their speed in exchange for a continuous stamina drain, which can, and **will** stamcrit them if left unchecked. 

---

# Technical Details?

We normally dont have this section but I'd like to outline the changes since I messed with quite a few systems:

- Introduces a `FlightComponent` which can be added to any entity in YML, needs to be tied to an action with an event of type type `ToggleFlightEvent` This component holds properties for:
    - Toggling animations on and off, either at the entity level or the layer level.
    - Altering shader animation properties
    - Altering speed, stamina drain, sounds played, delay between sounds, etc etc.
- Adds a `FlyingVisualizerSystem` that can take a given `AnimationKey` which points to a shader, and optionally can apply it to either the entire sprite, or a given layer. 
- Adds a check in `SharedGravitySystem` for making the entity weightless when it has the `FlightComponent` and is flying.
- Adds a check in `SharedCuffableSystem` to disable cuffing when the target has the `FlightComponent` and is flying.
- Introduces a new field in the `StaminaComponent` which serves as a dictionary for persistent drains, with the key being the source (UID) of where it came from. The drains can also indicate if they should apply the stamina slowdown or not (relevant for both this PR, and for an eventual sprinting PR)

---

<details><summary><h1>Media</h1></summary>
<p>

[![Flight Demo](https://i.ytimg.com/vi/Wndv9hYaZ_s/maxresdefault.jpg)](https://youtu.be/Wndv9hYaZ_s "Flight Demo")
</p>
</details>

---

# Changelog

:cl: Mocho
- add: Harpies are now able to fly on station for limited periods of time, moving faster at the cost of stamina.

2024-09-14 17:48 UTC, v0idRift commented
Love this! Excited to see how this enhances gameplay! Birb

2024-09-14 17:58 UTC, VMSolidus requested changes

2024-09-14 17:58 UTC, VMSolidus commented on Content.Client/Flight/Components/FlightVisualsComponent.cs
> +    public ShaderInstance Shader = default!;
```suggestion
    /// <summary>
    ///     How long does the animation last
    /// </summary>
    [DataField]
    public float Speed;

    /// <summary>
    ///     How far it goes in any direction.
    /// </summary>
    [DataField]
    public float Multiplier;

    /// <summary>
    ///     How much the limbs (if there are any) rotate.
    /// </summary>
    [DataField]
    public float Offset;

    /// <summary>
    ///     Are we animating layers or the entire sprite?
    /// </summary>
    public bool AnimateLayer = false;
    public int? TargetLayer;

    [DataField]
    public string AnimationKey = "default";

    [ViewVariables(VVAccess.ReadWrite)]
    public ShaderInstance Shader = default!;
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Client/Flight/FlightSystem.cs
> +                return;
```suggestion
            if (!_entityManager.TryGetComponent(uid, out SpriteComponent? sprite)
                || !args.IsAnimated
                || !_entityManager.TryGetComponent(uid, out FlightComponent? flight))
                return;
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Client/Flight/FlightSystem.cs
> +{
```suggestion
namespace Content.Client.Flight;
```
You are *also* going to need to move the entire document down an indent after doing this. Ctrl-A and Shift-Tab to do the entire document all at once.

2024-09-14 17:58 UTC, VMSolidus commented on Content.Client/Flight/FlightSystem.cs
> +}
```suggestion
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Client/Flight/FlightSystem.cs
> +                }
```suggestion
                if (layer.Rsi?.Path.ToString() == targetLayer)
                    return index;
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Client/Flight/FlightSystem.cs
> +            }
```suggestion
            if (!args.IsFlying)
                RemComp<FlightVisualsComponent>(uid);
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Client/Flight/FlyingVisualizerSystem.cs
> +        entity.Comp.GetScreenTexture = shader is not null;
```suggestion
        if (animateLayer && layer is not null)
            entity.Comp.LayerSetShader(layer.Value, shader);

        entity.Comp.GetScreenTexture = shader is not null;
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Client/Flight/FlyingVisualizerSystem.cs
> +    }
```suggestion

    /// <summary>
    ///     This function can be used to modify the shader's values while its running.
    /// </summary>
    private void OnBeforeShaderPost(EntityUid uid, FlightVisualsComponent comp, ref BeforePostShaderRenderEvent args)
    {
        SetValues(comp, comp.Speed, comp.Offset, comp.Multiplier);
    }
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Server/Flight/FlightSystem.cs
> +{
```suggestion
namespace Content.Server.Flight;
```
Just like before, you're going to need to drop the entire file down a tab indent.

2024-09-14 17:58 UTC, VMSolidus commented on Content.Server/Flight/FlightSystem.cs
> +}
```suggestion
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Server/Flight/FlightSystem.cs
> +                }
```suggestion
                if (component.TimeUntilFlap > 0f)
                    continue;
                    
                _audio.PlayPvs(component.FlapSound, uid);
                component.TimeUntilFlap = component.FlapInterval;
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Server/Flight/FlightSystem.cs
> +                }
```suggestion
                if (!CanFly(uid, component))
                    return;
                    
                var doAfterArgs = new DoAfterArgs(EntityManager, 
                    uid, component.ActivationDelay, 
                    new FlightDoAfterEvent(), uid, target: uid)
                {
                    BlockDuplicate = true,
                    BreakOnTargetMove = true,
                    BreakOnUserMove = true,
                    BreakOnDamage = true,
                    NeedHand = true
                };

                if (!_doAfter.TryStartDoAfter(doAfterArgs))
                    return;
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Server/Flight/FlightSystem.cs
> +            }
```suggestion
            else
                ToggleActive(uid, false, component);
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Server/Flight/FlightSystem.cs
> +        }
```suggestion
        private bool CanFly(EntityUid uid, FlightComponent component)
        {
            if (TryComp<CuffableComponent>(uid, out var cuffableComp) && !cuffableComp.CanStillInteract)
            {
                _popupSystem.PopupEntity(Loc.GetString("no-flight-while-restrained"), uid, uid, PopupType.Medium);
                return false;
            }
            
            if (HasComp<ZombieComponent>(uid))
            {
                _popupSystem.PopupEntity(Loc.GetString("no-flight-while-zombified"), uid, uid, PopupType.Medium);
                return false;
            }
            return true;
        }
```
You're also going to need to add a string for no-flight-while-zombified.

2024-09-14 17:58 UTC, VMSolidus commented on Content.Server/Flight/FlightSystem.cs
> +                ToggleActive(args.Target, false, component);
```suggestion
            if (!component.On 
                || args.NewMobState is MobState.Critical or MobState.Dead)
                return;
                
            ToggleActive(args.Target, false, component);
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Server/Flight/FlightSystem.cs
> +            }
```suggestion
            if (!component.On)
                return;

            ToggleActive(args.Target, false, component);
            if (!TryComp<StaminaComponent>(uid, out var stamina))
                return;
                
            Dirty(uid, stamina);
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Server/Flight/FlightSystem.cs
> +                ToggleActive(uid, false, component);
```suggestion
            if (!component.On)
                return;

            ToggleActive(uid, false, component);
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Server/Flight/FlightSystem.cs
> +                ToggleActive(uid, false, component);
```suggestion
            if (!component.On)
                return;
                
            ToggleActive(uid, false, component);
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Server/Flight/FlightSystem.cs
> +        }
```suggestion
        {
            if (!component.On 
                || !args.FellAsleep)
                return;

            ToggleActive(uid, false, component);
            if (!TryComp<StaminaComponent>(uid, out var stamina))
                return;
                
            Dirty(uid, stamina);
        }
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Server/Flight/FlightSystem.cs
> +
```suggestion
        #endregion
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Shared/Damage/Components/StaminaComponent.cs
> +    public Dictionary<EntityUid, (float DrainRate, bool ModifiesSpeed)> ActiveDrains = new();
```suggestion
    /// <summary>
    ///     A dictionary of active stamina drains, with the key being the source of the drain,
    ///     DrainRate how much it changes per tick, and modifiesSpeed if it should slow down the user.
    /// </summary>
    [DataField, AutoNetworkedField]
    public Dictionary<EntityUid, (float DrainRate, bool ModifiesSpeed)> ActiveDrains = new();
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Shared/Damage/Systems/StaminaSystem.cs
> +        }
```suggestion
        else
            stamina.ActiveDrains.Remove(actualSource);
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Shared/Damage/Systems/StaminaSystem.cs
> +            }
```suggestion
            if (comp.ActiveDrains.Count > 0)
                foreach (var (source, (drainRate, modifiesSpeed)) in comp.ActiveDrains)
                    TakeStaminaDamage(uid, 
                        drainRate * frameTime, 
                        comp, 
                        source: source, 
                        visual: false, 
                        allowsSlowdown: modifiesSpeed);
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Shared/Damage/Systems/StaminaSystem.cs
> +            }
```suggestion
            if (comp.ActiveDrains.Count == 0)
                TakeStaminaDamage(uid, -comp.Decay, comp);

```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Shared/Flight/Events.cs
> +}
```suggestion
namespace Content.Shared.Flight.Events;

[Serializable, NetSerializable]
public sealed partial class DashDoAfterEvent : SimpleDoAfterEvent { }

[Serializable, NetSerializable]
public sealed partial class FlightDoAfterEvent : SimpleDoAfterEvent { }

[Serializable, NetSerializable]
public sealed class FlightEvent : EntityEventArgs
{
    public NetEntity Uid { get; }
    public bool IsFlying { get; }
    public bool IsAnimated { get; }
    public FlightEvent(NetEntity uid, bool isFlying, bool isAnimated)
    {
        Uid = uid;
        IsFlying = isFlying;
        IsAnimated = isAnimated;
    }
}
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Shared/Flight/FlightComponent.cs
> +}
```suggestion
namespace Content.Shared.Flight;

/// <summary>
///     Adds an action that allows the user to become temporarily
///     weightless at the cost of stamina and hand usage.
/// </summary>
[RegisterComponent, NetworkedComponent(), AutoGenerateComponentState]
public sealed partial class FlightComponent : Component
{
    [DataField(customTypeSerializer: typeof(PrototypeIdSerializer<EntityPrototype>))]
    public string? ToggleAction = "ActionToggleFlight";

    [DataField, AutoNetworkedField]
    public EntityUid? ToggleActionEntity;

    /// <summary>
    ///     Is the user flying right now?
    /// </summary>
    [DataField, AutoNetworkedField]
    public bool On;

    /// <summary>
    ///     Stamina drain per second when flying
    /// </summary>
    [DataField, AutoNetworkedField]
    public float StaminaDrainRate = 6.0f;

    /// <summary>
    ///     DoAfter delay until the user becomes weightless.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float ActivationDelay = 1.0f;

    /// <summary>
    ///     Speed modifier while in flight
    /// </summary>
    [DataField, AutoNetworkedField]
    public float SpeedModifier = 2.0f;

    /// <summary>
    ///     Path to a sound specifier or collection for the noises made during flight
    /// </summary>
    [DataField]
    public SoundSpecifier FlapSound = new SoundCollectionSpecifier("WingFlaps");

    /// <summary>
    ///     Is the flight animated?
    /// </summary>
    [DataField]
    public bool IsAnimated = true;

    /// <summary>
    ///     Does the animation animate a layer?.
    /// </summary>
    [DataField]
    public bool IsLayerAnimated;

    /// <summary>
    ///     Which RSI layer path does this animate?
    /// </summary>
    [DataField]
    public string? Layer;

    /// <summary>
    ///     Whats the speed of the shader?
    /// </summary>
    [DataField]
    public float ShaderSpeed = 6.0f;

    /// <summary>
    ///     How much are the values in the shader's calculations multiplied by?
    /// </summary>
    [DataField]
    public float ShaderMultiplier = 0.01f;

    /// <summary>
    ///     What is the offset on the shader?
    /// </summary>
    [DataField]
    public float ShaderOffset = 0.25f;

    /// <summary>
    ///     What animation does the flight use?
    /// </summary>

    [DataField]
    public string AnimationKey = "default";

    /// <summary>
    ///     Time between sounds being played
    /// </summary>
    [DataField]
    public float FlapInterval = 1.0f;

    public float TimeUntilFlap;
}
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Shared/Flight/SharedFlightSystem.cs
> +
```suggestion
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Shared/Flight/SharedFlightSystem.cs
> +}
```suggestion
namespace Content.Shared.Flight;

public abstract class SharedFlightSystem : EntitySystem
{
    [Dependency] private readonly SharedActionsSystem _actionsSystem = default!;
    [Dependency] private readonly SharedVirtualItemSystem _virtualItem = default!;
    [Dependency] private readonly StaminaSystem _staminaSystem = default!;
    [Dependency] private readonly SharedHandsSystem _hands = default!;
    [Dependency] private readonly MovementSpeedModifierSystem _movementSpeed = default!;

    public override void Initialize()
    {
        base.Initialize();

        SubscribeLocalEvent<FlightComponent, ComponentStartup>(OnStartup);
        SubscribeLocalEvent<FlightComponent, ComponentShutdown>(OnShutdown);
        SubscribeLocalEvent<FlightComponent, RefreshMovementSpeedModifiersEvent>(OnRefreshMoveSpeed);
    }

    #region Core Functions
    private void OnStartup(EntityUid uid, FlightComponent component, ComponentStartup args)
    {
        _actionsSystem.AddAction(uid, ref component.ToggleActionEntity, component.ToggleAction);
    }

    private void OnShutdown(EntityUid uid, FlightComponent component, ComponentShutdown args)
    {
        _actionsSystem.RemoveAction(uid, component.ToggleActionEntity);
    }

    public void ToggleActive(EntityUid uid, bool active, FlightComponent component)
    {
        component.On = active;
        component.TimeUntilFlap = 0f;
        _actionsSystem.SetToggled(component.ToggleActionEntity, component.On);
        RaiseNetworkEvent(new FlightEvent(GetNetEntity(uid), component.On, component.IsAnimated));
        _staminaSystem.ToggleStaminaDrain(uid, component.StaminaDrainRate, active, false);
        _movementSpeed.RefreshMovementSpeedModifiers(uid);
        UpdateHands(uid, active);
        Dirty(uid, component);
    }

    private void UpdateHands(EntityUid uid, bool flying)
    {
        if (!TryComp<HandsComponent>(uid, out var handsComponent))
            return;

        if (flying)
            BlockHands(uid, handsComponent);
        else
            FreeHands(uid);
    }

    private void BlockHands(EntityUid uid, HandsComponent handsComponent)
    {
        var freeHands = 0;
        foreach (var hand in _hands.EnumerateHands(uid, handsComponent))
        {
            if (hand.HeldEntity == null)
            {
                freeHands++;
                continue;
            }

            // Is this entity removable? (they might have handcuffs on)
            if (HasComp<UnremoveableComponent>(hand.HeldEntity) && hand.HeldEntity != uid)
                continue;

            _hands.DoDrop(uid, hand, true, handsComponent);
            freeHands++;
            if (freeHands == 2)
                break;
        }
        if (_virtualItem.TrySpawnVirtualItemInHand(uid, uid, out var virtItem1))
            EnsureComp<UnremoveableComponent>(virtItem1.Value);

        if (_virtualItem.TrySpawnVirtualItemInHand(uid, uid, out var virtItem2))
            EnsureComp<UnremoveableComponent>(virtItem2.Value);
    }

    private void FreeHands(EntityUid uid)
    {
        _virtualItem.DeleteInHandsMatching(uid, uid);
    }

    private void OnRefreshMoveSpeed(EntityUid uid, FlightComponent component, RefreshMovementSpeedModifiersEvent args)
    {
        Logger.Debug("Refreshing movement speed!");
        if (!component.On)
            return;

        args.ModifySpeed(component.SpeedModifier, component.SpeedModifier);
    }

    #endregion
}
public sealed partial class ToggleFlightEvent : InstantActionEvent { }
```

2024-09-14 17:58 UTC, VMSolidus commented on Content.Shared/Gravity/SharedFloatingVisualizerSystem.cs
> +        }
```suggestion
        if (!args.IsFlying 
            || !args.IsAnimated)
            return;

        FloatAnimation(uid, floating.Offset, floating.AnimationKey, floating.AnimationTime);
```

2024-09-14 17:58 UTC, VMSolidus commented on Resources/Locale/en-US/flight/flight_system.ftl
> +no-flight-while-restrained = You can't fly right now.
Add a localization for no-flight-while-zombified

2024-09-16 04:41 UTC, VMSolidus approved these changes

2024-09-16 04:41 UTC, OldDanceJacket approved these changes

2024-09-16 04:41 UTC, merged

2025-12-08 11:51 UTC, Toby222 commented
Hoi
We're currently porting this to DeltaV and noticed there's no attribution on the wing flap sounds, any idea what the source is?