[Port] StepTriggerGroup From WhiteDream
Simple-Station/Einstein-Engines pull request #929
Opened 2024-09-18 00:16 UTC by VMSolidus

# Description

This is a port of https://github.com/WWhiteDreamProject/wwdpublic/pull/53 from White Dream. This PR improves the StepTriggerImmune component by making it operate on a more granular Blacklist system, such that StepTriggerImmune entities can further clarify via prototypes which kinds of floor traps they are immune to, such as landmines/mousetraps, and not have blanket immunity to everything. Because it turns out things like Lava and Soap also were caught by the immunity, when really we just wanted Harpies & Felinids to not trigger landmines. 

<details><summary><h1>Media</h1></summary>
<p>

> # Описание
> Необходимо настроить модификатор урона, чтобы IPC не получали урон от осколков стекла.
> 
> Иммунитет StepTriggerImmuneComponent доработан. Теперь имеются несколько типов (types): Lava - тип тайла, наступив на который появляется урон. Это собственно лава и LiquidPlasma Landmine - мины. Chasm - дырка в карте, куда можно провалиться Mousetrap - Мышеловка SlipTile - Все, что должно подскальзывать игроков, имеющее размер тайла SlipEntity - Все, что должно подскальзывать игроков, имеющее развер энтити. Разделено для баланса. Самые ловки могут игнорировать мелкие предметы (энтити), т.е. уворачиваться от них. Но большие по площади вещи (тайлы по типу разлитой воды, бананиума) просчитываются отдельно.
> 
> # Изменения
> * [x]  Улучшить StepTriggerSystem (Immune)
> * [x]  Добавлены типы триггера. - Lava Landmine Shard Chasm Mousetrap SlipTile SlipEntity
> * [x]  Исправить осколки у IPC
> * [x]  Исправить отсутствие урона от лавы и падение в дыры у фелинидов и гарпий.
> 
> 🆑 Hell_Cat
> 
> * Feature: StepTriggerSystem is improved | Улучшена StepTriggerSystem
> * fix: IPC: Immunity for shards and SpiderWeb | Иммунитет осколкам.
> * fix: Felinid | Фелиниды : Immunity for Shard Landmine Mousetrap SlipEntities | Иммунитет для осколков, жидкости, мин, мышеловок, мыла и бананов.
> * fix: Harpy | Гарпия : Immunity for Shards Landmine Mousetrap | Иммунитет для осколков, жидкости, мин и мышеловок.
> * fix: Mice | Мыши : Don't blow up on landmines | Мыши не подрываются на минах.

</p>
</details>

# Changelog

:cl: Hell_Cat
Feature: StepTriggerSystem is improved | Улучшена StepTriggerSystem
fix: IPC: Immunity for shards and SpiderWeb | Иммунитет осколкам.
fix: Felinid | Фелиниды : Immunity for Shard Landmine Mousetrap SlipEntities | Иммунитет для осколков, жидкости, мин, мышеловок, мыла и бананов.
fix: Harpy | Гарпия : Immunity for Shards Landmine Mousetrap | Иммунитет для осколков, жидкости, мин и мышеловок.
fix: Mice | Мыши : Don't blow up on landmines | Мыши не подрываются на минах.

2024-09-18 00:36 UTC, FoxxoTrystan submitted a review, later dismissed
diona need glass immunity (and slip but they already got (noslips).

infact, should noslip shoses just have also whitelists?

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Effects/chemistry_effects.yml
> +    triggerGroups: # WD EDIT
```suggestion
    triggerGroups:
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +      - Landmine # END
```suggestion
  - type: StepTriggerImmune
    whitelist:
      types:
      - Landmine
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Mobs/Player/ipc.yml
> +  - type: StepTriggerImmune #WD EDIT
```suggestion
  - type: StepTriggerImmune
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Mobs/Species/harpy.yml
> +    whitelist: # WD EDIT
```suggestion
    whitelist:
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Objects/Devices/mousetrap.yml
> +      triggerGroups: # WD EDIT
```suggestion
      triggerGroups:
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Objects/Devices/pda.yml
> +    triggerGroups: # WD EDIT
```suggestion
    triggerGroups:
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Objects/Fun/dice.yml
> +    triggerGroups: # WD EDIT
```suggestion
    triggerGroups:
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Objects/Materials/shards.yml
> +    triggerGroups: # WD EDIT
```suggestion
    triggerGroups:
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Objects/Misc/land_mine.yml
> +    triggerGroups: # WD EDIT
```suggestion
    triggerGroups:
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Objects/Specific/Janitorial/soap.yml
> +    triggerGroups: # WD EDIT
```suggestion
    triggerGroups:
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Objects/Specific/Janitorial/soap.yml
> +    triggerGroups: # WD EDIT
```suggestion
    triggerGroups:
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Objects/Specific/Janitorial/soap.yml
> +    triggerGroups: # WD EDIT
```suggestion
    triggerGroups:
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Tiles/bananium.yml
> +    triggerGroups: # WD EDIT
```suggestion
    triggerGroups:
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Tiles/chasm.yml
> +    triggerGroups: # WD EDIT
```suggestion
    triggerGroups:
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Tiles/lava.yml
> +    triggerGroups: # WD EDIT
```suggestion
    triggerGroups:
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Tiles/liquid_plasma.yml
> +    triggerGroups: # WD EDIT
```suggestion
    triggerGroups:
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/felinid.yml
> +    whitelist: # WD EDIT
```suggestion
    whitelist:
```

2024-09-18 00:36 UTC, FoxxoTrystan commented on Resources/Prototypes/Traits/skills.yml
> +      whitelist: # WD EDIT
```suggestion
      whitelist:
```

2024-09-18 00:37 UTC, VMSolidus commented
> diona need glass immunity (and slip but they already got (noslips).
> 
> infact, should noslip shoses just have also whitelists?

Noslip is its own separate thing, and Diona have it. Also Diona have ShoesRequiredStepTriggerImmune so they don't care about glass.

2024-09-18 00:38 UTC, FoxxoTrystan commented
Also that is some cursed CL

2024-09-18 00:39 UTC, VMSolidus commented
> Also that is some cursed CL

Yep lol. But when porting from another codebase, we are supposed to preserve the original CL. I kinda like how they do it with bilingual changes. :)

2024-09-18 00:43 UTC, FoxxoTrystan commented
its funny and  i understood it so, okay!
just dont forget diona

2024-09-18 04:31 UTC, DEATHB4DEFEAT commented
Do the CL as is normally done

2024-09-18 04:33 UTC, DEATHB4DEFEAT approved these changes

2024-09-19 02:13 UTC, FoxxoTrystan requested changes
Not stale, please provide this to Dionas.
Before they had a special component or tag, witcth may got removed with the time, but again they are wood, sshould not be affected by glass.
```
- type: StepTriggerImmune
    whitelist:
      types:
      - Shard
```

2024-09-19 02:14 UTC, VMSolidus commented
> Not stale, please provide this to Dionas. Before they had a special component or tag, witcth may got removed with the time, but again they are wood, sshould not be affected by glass.
> 
> ```
> - type: StepTriggerImmune
>     whitelist:
>       types:
>       - Shard
> ```

Done

2024-09-19 02:18 UTC, FoxxoTrystan approved these changes

2024-09-19 02:47 UTC, OldDanceJacket approved these changes

2024-09-19 03:29 UTC, merged