More Quick Construction Recipes And Upgrades
Simple-Station/Einstein-Engines pull request #945
Opened 2024-09-21 17:41 UTC by gluesniffler

# Description

This PR adds a few new recipes to Quick Construction (accessed by pressing Z on commonly used construction materials/items, such as rods, glass, steel, plasma, etc etc). Along with simple nesting for grouping items up under categories, akin to how the RCD works. Which allows engineers to massively speed up pipe laying work, disposal rebuilding, setting up the supermatter, etc etc.

First time doing UI code, apologies for the shitcode in advance :godo:

---

<details><summary><h1>Media</h1></summary>
<p>

https://github.com/user-attachments/assets/9d540d7f-7e4f-4a43-874d-5ea069011a37

</p>
</details>

---

# Considerations

Is this powergamey? Probably. Is it fucking awesome? Hell yeah. Some servers might question the fact that everyone can build stuff this fast now that they dont have to deal too much with the construction menu for the most common things... And might want to lock it behind traits or given as a job freebie, like CPR for doctors. 

Other servers might appreciate it if they are looking for more action to happen over the round, and giving everyone the ability to deal with breaches and repairs quicker is probably a step into that direction. I'll be observing for feedback and adjust accordingly.

It also shouldn't invalidate any eventual RPDs, or other devices of the kind since this is just a shortcut for construction, you still require materials and a doafter for most of them. 

---

# Changelog

:cl: Mocho
- add: Added a lot of recipes to the quick construction menus. Give it a shot by pressing Z with different construction materials in your hand!

2024-09-21 18:01 UTC, gluesniffler commented
YAML Linter my beloathed... fixing.

2024-09-21 22:38 UTC, VMSolidus requested changes

2024-09-21 22:38 UTC, VMSolidus commented on Content.Shared/ShortConstruction/ShortConstructionComponent.cs
> +    public ShortConstructionCategory? Category { get; set; }
```suggestion
    [DataField]
    public ProtoId<ConstructionPrototype>? Prototype { get; set; }

    [DataField]
    public ShortConstructionCategory? Category { get; set; }
```

2024-09-21 22:38 UTC, VMSolidus commented on Content.Shared/ShortConstruction/ShortConstructionComponent.cs
> +    public List<ShortConstructionEntry> Entries { get; set; } = new();
```suggestion
    [DataField]
    public string Name { get; set; } = string.Empty;

    [DataField]
    public SpriteSpecifier Icon { get; set; } = default!;

    [DataField]
    public List<ShortConstructionEntry> Entries { get; set; } = new();
```

2024-09-21 22:38 UTC, VMSolidus commented on Content.Client/ShortConstruction/UI/ShortConstructionMenuBUI.cs
> +        }
```suggestion
        if (_entManager.TryGetComponent<ShortConstructionComponent>(Owner, out var crafting))
            CreateMenu(crafting.Entries);
```

2024-09-22 17:24 UTC, VMSolidus approved these changes
https://github.com/user-attachments/assets/f168863f-ac69-4605-9071-7f5fed63df33

I've tested this ingame to verify that this feature works correctly and as advertised. I will say that this makes me a little giddy as someone who was once an engineer main. It means that proper "Combat engineering" is entirely viable since you can skip the clunky construction menu and go straight to building barriers.

2024-09-23 02:36 UTC, FoxxoTrystan approved these changes

2024-09-23 02:37 UTC, FoxxoTrystan commented
oops removed solidus review

2024-09-24 00:56 UTC, merged