batch changes
Simple-Station/Einstein-Engines pull request #956
Opened 2024-09-23 20:30 UTC by fenndragon

# Description

This is a batch of changes I made for Floof station being ported over to the upstream branch

---

# Changelog

:cl:
- add: Added multiple passive xenos 
- add: Added Friend-shaped and other xeno test subjects. 
- add: Added multiple new Reagent slimes
- add: Added multiple ventcritter events for more variety 
- fix: Fixed the critstate of multiple Xenos
- tweak: changed the base Rouny sprite to be more updated.

2024-09-23 20:40 UTC, SleepyScarecrow requested changes
just nitpicky directory stuff from me :3

2024-09-23 20:40 UTC, SleepyScarecrow commented on Resources/Prototypes/Floof/Body/Organs/Friendstomach.yml
have to remove floof folder

2024-09-23 20:40 UTC, SleepyScarecrow commented on Resources/Prototypes/Floof/Body/Prototypes/Friendshaped.yml
have to remove floof folder

2024-09-23 21:48 UTC, SleepyScarecrow approved these changes

2024-09-23 23:14 UTC, Mnemotechnician requested changes
The entire changelog should be just 1-2 entries, and should not include technical details.

2024-09-23 23:32 UTC, fenndragon commented
> The entire changelog should be just 1-2 entries, and should not include technical details.

better?

2024-09-23 23:48 UTC, Mnemotechnician commented
It should also be descriptive for someone who's reading it in the menu. "Added new neutral xeno prototypes for admins to use in events" or something similar would be good.

2024-09-23 23:57 UTC, fenndragon commented
> It should also be descriptive for someone who's reading it in the menu. "Added new neutral xeno prototypes for admins to use in events" or something similar would be good.

I listed a bit better what all was added but I did it in one entry, better?

2024-09-24 00:03 UTC, Mnemotechnician approved these changes
Yea, that's fine now.

2024-09-24 18:38 UTC, FoxxoTrystan reviewed
Except for Rouney Sprite, i dont think those additions are needed.

Those Neutral things were things you done mostly for floof, il let solidus view it.

2024-09-24 22:34 UTC, fenndragon commented
> Except for Rouney Sprite, i dont think those additions are needed.
> 
> Those Neutral things were things you done mostly for floof, il let solidus view it.

it was requested.

2024-09-24 22:38 UTC, fenndragon commented
> Except for Rouney Sprite, i dont think those additions are needed.
> 
> Those Neutral things were things you done mostly for floof, il let solidus view it.

Also, how is additional events and reagent slimes not needed? this is literally just additional content.

2024-09-24 22:41 UTC, VMSolidus approved these changes
Wuh>? This is fine though?

2024-09-24 22:49 UTC, VMSolidus commented
Or well, it would be when the Linter fail is fixed. That's legitimate.

2024-09-24 22:52 UTC, fenndragon commented
> Or well, it would be when the Linter fail is fixed. That's legitimate.

whoops forgot to change the texture paths, my bad

2024-09-25 00:56 UTC, fenndragon commented
went ahead and just added 3 more events and fixed the event text in the locale while I was thinking about it

2024-09-25 09:22 UTC, FoxxoTrystan reviewed
New Events in general just remove all the uniquness of anomalies that can spawn it ect...
And some of them does not fit, i would not approve something like this, review goes to others for it.

2024-09-25 09:22 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Mobs/NPCs/Rslimes.yml
> +      prob: 0.01
Im not gona request Changes but not gona approve this, i was against this on floof, will be here.

Those are only for anomalies.

2024-09-25 09:22 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml
> +      prob: 0.005
Same thing, those if i recall are used for asteroids/salvage

2024-09-25 09:22 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml
> +      prob: 0.005
Anomaly Stuff again

2024-09-25 09:22 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml
> +      prob: 0.01
Space Stuff

2024-09-25 09:22 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml
> +      prob: 0.01
Carps should not come out of vents, pehaps spawn outside of the station but not inside.

2024-09-25 09:22 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml
> +      prob: 0.01
Bear, Kangaroo, this is again, Salvage spawns.

2024-09-25 09:22 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml
> +      prob: 0.01
This is again anomly spawns

2024-09-25 09:42 UTC, fenndragon commented
> New Events in general just remove all the uniquness of anomalies that can spawn it ect... And some of them does not fit, i would not approve something like this, review goes to others for it.

that's fine, and I was going to leave it at that but it was then requested as a feature personally by others to port it upstream so that's what I'm doing.

2024-09-25 17:07 UTC, SleepyScarecrow approved these changes

2024-09-25 23:37 UTC, VMSolidus approved these changes

2024-09-26 01:27 UTC, SleepyScarecrow approved these changes

2024-09-26 15:05 UTC, OldDanceJacket approved these changes

2024-09-26 15:06 UTC, merged