Windows And Tables Resprites!
Simple-Station/Einstein-Engines pull request #958
Opened 2024-09-24 22:49 UTC by FoxxoTrystan

# Description

Changes Windows, Tables Sprites, and fixes the state for the airalarm.

Directional windows needed to be updated as we updated the previous ones, tables looked ugly and needed an update, its was provided.

Airalarm has its danger state set to warning, and the other inverted, this fixes it too.

---

# TODO

- [x] AirAlarm State Fix
- [x] Window/Windoor Sprite
- [x] Tables

---

<details><summary><h1>Media</h1></summary>
<p>

![image](https://github.com/user-attachments/assets/aa05ca6e-5d1c-4ade-9158-78cfb7ced31d)

</p>
</details>

---

# Changelog

:cl:
- tweak: Directional Windows and Tables has gotten new sprites!
- fix: AirAlarm Inverted Alert States has been fixed!

2024-09-24 22:53 UTC, FoxxoTrystan commented on Resources/Prototypes/Entities/Structures/Furniture/Tables/tables.yml
Me when i touch the "Format Document" button.

2024-09-24 23:58 UTC, VMSolidus approved these changes
Oh those look really nice!

2024-09-28 02:37 UTC, DEATHB4DEFEAT requested changes
Remove single-frame delays from metas and put the delays on one line per direction

2024-09-28 02:46 UTC, FoxxoTrystan commented
Really...

Meta File Formatting, you dying that?
Format File.

2024-09-28 02:47 UTC, DEATHB4DEFEAT commented
ooh right I can make my edited changes in VSCode into review comments

2024-09-28 02:56 UTC, DEATHB4DEFEAT commented
![image](https://github.com/user-attachments/assets/9b9ae1a4-1515-498c-b6dd-e57c0b3bf44f)
guh

2024-09-28 02:56 UTC, DEATHB4DEFEAT commented on Resources/Textures/Structures/Wallmounts/air_monitors.rsi/meta.json
> +                ]
```suggestion
                [ 0.2, 0.2, 0.2, 0.2, 0.2, 0.2 ],
                [ 0.2, 0.2, 0.2, 0.2, 0.2, 0.2 ],
                [ 0.2, 0.2, 0.2, 0.2, 0.2, 0.2 ],
                [ 0.2, 0.2, 0.2, 0.2, 0.2, 0.2 ]
```

2024-09-28 02:56 UTC, DEATHB4DEFEAT commented on Resources/Textures/Structures/Furniture/Tables/r_glass.rsi/meta.json
> +            ]
```suggestion
            "name": "full"
        },
        {
            "name": "state_0",
            "directions": 4
        },
        {
            "name": "state_1",
            "directions": 4
        },
        {
            "name": "state_2",
            "directions": 4
        },
        {
            "name": "state_3",
            "directions": 4
        },
        {
            "name": "state_4",
            "directions": 4
        },
        {
            "name": "state_5",
            "directions": 4
        },
        {
            "name": "state_6",
            "directions": 4
        },
        {
            "name": "state_7",
            "directions": 4
```

2024-09-28 02:57 UTC, DEATHB4DEFEAT commented on Resources/Textures/Structures/Wallmounts/air_monitors.rsi/meta.json
> +                ]
```suggestion
                [ 0.5, 0.5 ],
                [ 0.5, 0.5 ],
                [ 0.5, 0.5 ],
                [ 0.5, 0.5 ]
            ]
        },
        {
            "name": "fire_3",
            "directions": 4,
            "delays": [
                [ 0.3, 0.3 ],
                [ 0.3, 0.3 ],
                [ 0.3, 0.3 ],
                [ 0.3, 0.3 ]
```

2024-09-28 02:57 UTC, DEATHB4DEFEAT commented on Resources/Textures/Structures/Wallmounts/air_monitors.rsi/meta.json
> +            ]
```suggestion
            "directions": 1
        },
        {
            "name": "auth_on",
            "directions": 1,
            "delays": [ [ 0.1, 0.1 ] ]
```

2024-09-28 10:24 UTC, FoxxoTrystan commented
![image](https://github.com/user-attachments/assets/9e364aeb-cdbe-46d2-bc35-f702e8c13d60)

Just for file format this is pain, gosh.
What Format File VSCode Setting are you using so you dont trouble me with this ever again?

2024-10-04 00:24 UTC, OldDanceJacket approved these changes

2024-10-04 00:25 UTC, merged