Floof station contributions
Simple-Station/Einstein-Engines pull request #982
Opened 2024-09-29 18:12 UTC by fenndragon

# Description

updated the spawn tables for events to fix some of the issues run into 

Dangerous things spawn less often, helpful things spawn more. 

---

# Changelog

:cl:
-Tweak: Tweaked the spawnrate of certain mobs within the ventcritters rule.

2024-09-29 18:35 UTC, VMSolidus requested changes

2024-09-29 18:35 UTC, VMSolidus commented on Resources/Prototypes/Entities/Mobs/NPCs/Rslimes.yml
>        prob: 0.002
```suggestion
```

2024-09-29 18:40 UTC, VMSolidus requested changes

2024-09-29 18:40 UTC, VMSolidus commented on Resources/Prototypes/Entities/Mobs/NPCs/Rslimes.yml
> +      prob: 0.003
```suggestion
      prob: 0.001
```

2024-09-29 18:40 UTC, VMSolidus commented on Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml
> +      prob: 0.008
```suggestion
      prob: 0.0075
```

2024-09-29 18:40 UTC, VMSolidus commented on Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml
> +      prob: 0.008
```suggestion
      prob: 0.0075
```

2024-09-29 18:40 UTC, VMSolidus commented on Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml
> +      prob: 0.008
```suggestion
      prob: 0.0075
```

2024-09-29 18:40 UTC, VMSolidus commented on Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml
> +      prob: 0.008
```suggestion
      prob: 0.0075
```

2024-09-29 18:40 UTC, VMSolidus commented on Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml
> +      prob: 0.001
```suggestion
      prob: 0.0001
```

2024-09-29 18:40 UTC, VMSolidus commented on Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml
> +      prob: 0.008
```suggestion
      prob: 0.002
```

2024-09-29 18:40 UTC, VMSolidus commented on Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml
> +      prob: 0.008
```suggestion
      prob: 0.002
```

2024-09-30 16:25 UTC, VMSolidus approved these changes

2024-10-02 01:32 UTC, OldDanceJacket approved these changes

2024-10-02 01:34 UTC, merged